### ISSUE TITLE
Stock updates trigger index operations when there is nothing to update

### ISSUE THREAD

**Issue by paulvandermeijs** [algolia/algoliasearch-magento-2#1007]
**Do you want to request a *feature* or report a *bug*?**
bug

**Steps to reproduce**
1. Make sure indexing is set to "Update by Schedule"
2. Empty all change log tables and make sure all indexers are up to date.
```sql
# Empty change logs
TRUNCATE TABLE algolia_additional_sections_cl;
TRUNCATE TABLE algolia_categories_cl;
TRUNCATE TABLE algolia_delete_products_cl;
TRUNCATE TABLE algolia_pages_cl;
TRUNCATE TABLE algolia_products_cl;
TRUNCATE TABLE algolia_queue_runner_cl;
TRUNCATE TABLE algolia_suggestions_cl;
TRUNCATE TABLE amasty_order_attribute_values_cl;
TRUNCATE TABLE catalog_category_product_cl;
TRUNCATE TABLE catalog_product_attribute_cl;
TRUNCATE TABLE catalog_product_category_cl;
TRUNCATE TABLE catalog_product_price_cl;
TRUNCATE TABLE cataloginventory_stock_cl;
TRUNCATE TABLE catalogrule_product_cl;
TRUNCATE TABLE catalogrule_rule_cl;
TRUNCATE TABLE catalogsearch_fulltext_cl;
TRUNCATE TABLE customer_dummy_cl;
TRUNCATE TABLE design_config_dummy_cl;
TRUNCATE TABLE inventory_cl;
UPDATE mview_state SET version_id = 0;
```
3. Update stock for a product to another value but same stock status. Assuming the API is used:
```http
PUT /rest/all/V1/products/<your_sku>/stockItems/<your_stock_item_id> HTTP/1.1
Host: <your_host>
Content-Type: application/json
Authorization: Bearer <your_bearer_token>
Content-Type: text/plain

{
    "stockItem": {
        "qty": 100
    }
}
```
4. Check change log tables / index status. There should now be a single item in the backlog.
5. Run cron.
6. Index operation is queued / sent to Algolia.

**Bug: What is the current behavior?**
For each stock change an index operation is sent to Algolia, even though the actual stock value is not stored by Algolia and the stock status, which is stored, might not have changed. I assume this happens because on a update a change is registered in the change log table but the nature of the change is unclear to Algolia and an update is triggered even though there might be nothing to update.

**Bug: What is the expected behavior?**
When an update is made that doesn't change the data that is stored by Algolia no index operation should be triggered.

**Bug: What is the proposed solution?**
This problem could be solved by hashing the data that is sent to Algolia and store it. Then before either queued or sent to Algolia the stored hash can be compared to the hash for the data that is about to be sent to Algolia and if the hash doesn't change the index update can be ignored.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
