### ISSUE TITLE
Update instructions from 1.13.1 -> 2.0.0

### ISSUE THREAD

**Issue by kunzi** [algolia/algoliasearch-magento-2#1017]
Could you provide detailed update instructions to update from 1.13.1 to 2.0.0. I'm unable to update the extension with composer because of some dependencies.

**Comment by bsuravech** [comment]
Hi @kunzi,

Thanks for reaching out. Can you clarify which dependencies are preventing you from updating to v2.x? 

If you are looking to update from v1.x to v2.x, please review the release notes as well as read this guide on how to migrate changes:

https://github.com/algolia/algoliasearch-magento-2/releases/tag/2.0.0

https://www.algolia.com/doc/integration/magento-2/getting-started/upgrading/?language=php#upgrading-from-v1-to-v2

Let us know.

**Comment by kunzi** [comment]
In the end I removed the installation and re-installed it and it worked. There was some other php-related extension from you included that should have also been updated and I was not able to update that either as there too was some dependency issue.

**Comment by bsuravech** [comment]
Thanks for the follow up, @kunzi. We'll check our external modules to see if they need updated compatibility. 

We're going to close out this issue. We are going to be centralising our support. If you have any questions or further issues, please feel free to contact us through [support@algolia.com](mailto:support@algolia.com).
