### ISSUE TITLE
Possible bug: `Environment emulation nesting is not allowed`

### ISSUE THREAD

**Issue by JamesJJ** [algolia/algoliasearch-magento-2#1018]
I'm seeing `Environment emulation nesting is not allowed` in my logs, and I'm not sure that it's related to Algolia...

However, looking at the code it seems that perhaps the fifth argument (`$emulationInfo`) in the call to `rebuildStoreProductIndexPage(...)` in [Data.php line 327](https://github.com/algolia/algoliasearch-magento-2/blob/991efb244509c3f0c9cf1719e9d9cb6058017ac8/Helper/Data.php#L327) should *not* be `null`, given that `startEmulation` has already been called in [Data.php line 301](https://github.com/algolia/algoliasearch-magento-2/blob/991efb244509c3f0c9cf1719e9d9cb6058017ac8/Helper/Data.php#L301) ?

```php
    public function rebuildStoreProductIndex($storeId, $productIds)
    {
        // ...

        $this->startEmulation($storeId);  // L301

        // ...
        try {
            // ...
            if ($size > 0) {
               // ...

                while ($page <= $pages) {
                    $this->rebuildStoreProductIndexPage(
                        $storeId,
                        $collection,
                        $page,
                        $this->configHelper->getNumberOfElementByPage(),
                        null,   // L327
                        $productIds
                    );
                   // ...
```

```php
    public function rebuildStoreProductIndexPage(
        $storeId,
        $collectionDefault,
        $page,
        $pageSize,
        $emulationInfo = null,
        $productIds = null,
        $useTmpIndex = false
    ) {

        // ...
        if ($emulationInfo === null) {
            $this->startEmulation($storeId);
        }
       // ...
```

**Comment by damcou** [comment]
Hello @JamesJJ ,

Thanks for reaching out.
Unfortunately, I wasn't able to reproduce the behaviour you mentioned.
Could you please specify which Magento version and which version of the extension you are using ?
Did you have a chance to figure out if the error was triggered by another third party extension maybe ?

Regarding the code you mentioned, you're right , calling `startEmulation() ` more than once can be confusing, but this method checks if the emulation is already running by itself so the emulation nesting shouldn't happen only with the extension : https://github.com/algolia/algoliasearch-magento-2/blob/991efb244509c3f0c9cf1719e9d9cb6058017ac8/Helper/Data.php#L678-L680 .

**Comment by JamesJJ** [comment]
Hi @damcou, Many thanks for your reply!

Given the check at L678 I expect that the error must be caused by something else.

The magento version would have been 'open source' version 2.3.2-p2.

I'm not sure about the Algolia plugin version, and I can't check as the corresponding project has been re-assigned to a different colleague -- For now I will  close this issue - Thanks again for checking this.
