### ISSUE TITLE
Index dates as Unix timestamps

### ISSUE THREAD

**Issue by tvweinstock** [algolia/algoliasearch-magento-2#1019]
**Do you want to request a *feature* or report a *bug*?**
Feature

Add a created_at attribute that is in the format of a Unix timestamp

**Feature: What is your use case for such a feature?**

In order to [sort or custom rank an index based on a date](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/sort-an-index-by-date/) Algolia requires dates in the form of numeric timestamps and not strings. 
It would be great to have the attribute created_at or any other date attributes generated by Magento converted into timestamps before indexing to Algolia. 

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
Convert date strings to Unix timestamp.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Latest

**Comment by bsuravech** [comment]
Thanks @tvweinstock for the feedback! We've tagged the issue as feedback and have ported this over to our productboard. 

The recommend solution right now is to create an observer on the dispatched event [`algolia_after_create_product_object`](https://www.algolia.com/doc/integration/magento-2/customize/custom-back-end-events/?language=php#dispatching-after-fetching-products-attributes-for-indexing) to convert the createdAt attribute to the unix timestamp.
