### ISSUE TITLE
div class class/id missing in facet wrappers

### ISSUE THREAD

**Issue by MagePsycho** [algolia/algoliasearch-magento-2#102]
I can see that facet wrappers are created without any id or class.
It would be better to add the attribute name along with some prefix or postfix.

`container: facet.wrapper.appendChild(document.createElement('div'))`

to something like

```
var facetDiv = document.createElement('div');
var facetDiv.className = 'some-wrapper-' + facet.attribute;
...
container: facet.wrapper.appendChild(facetDiv)
...
```

So that it's easier to customize the facet blocks as per attributes.

**Comment by JanPetr** [comment]
Thanks for suggestion @MagePsycho, implemented #105.
It'll be part of the next release and I'm closing the issue now.

If there is still something you'd like to add, feel free to reopen.
