### ISSUE TITLE
IE11 Compatibility

### ISSUE THREAD

**Issue by BrentRobert** [algolia/algoliasearch-magento-2#1020]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**
Algolia doesn't work in IE11. No autocomplete and crashes other javascript eg add to cart on product detail page.

**Bug: What is the expected behavior?**
Algolia works in IE11

**Bug: What is the proposed solution?**
Remove ES6 Syntax. In a quick sweep I found usage of Promises and default parameters in functions. 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
M2.3.5-p1 and version 2.0.0

**Comment by bsuravech** [comment]
Hi @BrentRobert, 

Thanks for submitting this issue. We have added to our community board for review and to investigate further. We are closing our Issues section to centralise our support. If you have any further feedback or questions, please feel free to reach us over at [support@algolia.com](mailto:support@algolia.com).

We will be sure to tag this issue for you to follow if we have any upcoming fixes to correct this issue. Thank you!
