### ISSUE TITLE
Don't import full jQuery UI

### ISSUE THREAD

**Issue by palviggi-flagbit** [algolia/algoliasearch-magento-2#1023]
**Bug: What is the current behavior?**
The full jQueryUI is being imported, but only a part is used, affecting the performance of the site on category pages. On the console there's this warning from Magento
"Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site."

**Bug: What is the expected behavior?**
No warning, only neccessary dependency used.

**Bug: What is the proposed solution?**
in view/frontend/web/navigation/range-slider-widget.js change "jquery/ui" to "jquery-ui-modules/widget"

The jquery UI change was introduced in 2.3.3 (102.0.3), which conflicts with the current supported versions. I don't know if it's possible to make a js only load on a specific version, or if it would need 2 versions of the module to maintain support

It is also used when only enabling Backend Facet Rendering, I don't know if it's used enough

**Comment by bsuravech** [comment]
Hi @palviggi-flagbit,

Thanks for your feedback! We know that removing jQuery from the bundle is a highly requested feedback for our frontend features. We will review your proposed solution as inspiration for future improvements. 

We have added this issue to our community board and our productboard for future improvements to our extension. If you have any further feedback or questions, please feel free to reach us at [support@algolia.com](mailto:support@algolia.com).  Thank you!
