### ISSUE TITLE
Incorrect path for images settings in ConfigHelper.php

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#103]
Paths are incorrect  in lines https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/ConfigHelper.php#L55-L57.
They should be start from algoliasearch_images 
In https://github.com/algolia/algoliasearch-magento-2/blob/master/etc/adminhtml/system.xml#L363 and https://github.com/algolia/algoliasearch-magento-2/blob/master/etc/config.xml#L55 this name is used.

**Comment by JanPetr** [comment]
Hey, thanks for the report @vmalyk, fixed in #103.
It'll be part of the next release. If you spot any issue with that feel free to reopen.
