### ISSUE TITLE
Don't load jquery for magento 2

### ISSUE THREAD

**Issue by alexgran** [algolia/algoliasearch-magento-2#1035]
**Do you want to request a *feature* or report a *bug*?**
One could argue both ;)

**Bug: What is the current behavior?**
algoliaBundle.min.js includes jquery, which makes a significant amount of the size of the bundle.

**Bug: What is the expected behavior?**
All mage2 stores that use a magento-theme (I guess 99%+), already include jquery. 

**Bug: What is the proposed solution?**
Use magento requireJs to depend on jquery, and then use this instead of bundling it.

**Feature: What is your use case for such a feature?**
Page load speed increases quite a bit.

**Comment by bsuravech** [comment]
Hi @alexgran! 

Thank you for your feedback! We have added this issue to our community board and our productboard for future improvements to our extension. If you have any further feedback or questions, please feel free to reach us at [support@algolia.com](mailto:support@algolia.com). Thanks!
