### ISSUE TITLE
Updating the qty (MSI) programatically issue

### ISSUE THREAD

**Issue by atty31** [algolia/algoliasearch-magento-2#1037]
**Bug Description**
When using MSI  and updating the inventory source qty, like (code sample):
....
/** @var \Magento\Inventory\Model\SourceItem */
$inventorySourceItem->setQuantity($quantity);
/** @var \Magento\Inventory\Model\ResourceModel\SourceItem */
$this->inventorySourceItemResourceModel->save($inventorySourceItem);
... 
and **don't** save the product, then the wrong qty is going to be  processed by the queue and send to Algolia (visible in the indices side) 

**Workaround:**
Update the qty programatically (MSI) and **manually** save the product from the adminpanel.  Or do product save (without changing anything from the adminpanel)

**Current Magento version:** 2.3.4 or 2.3.5
**Current Algolia modules version:**

- algolia/algoliasearch-inventory-magento-2: 1.0.0
- algolia/algoliasearch-magento-2 : 1.13.1

Would you please take a look on this ?  Thank you

**Comment by bsuravech** [comment]
Hi @atty31,

Thanks for submitting this feedback. At this time, products are not triggered by the inventory source save event in the extension. We have added your feedback to our Community Board for consideration for future improvements.

For now, I would recommend creating an observer around that save event to reindex the productID. You can use this class as inspiration: `\Algolia\AlgoliaSearch\Model\Indexer\ProductObserver`.

We are going to close our Issues section to consolidate our support. For any feedback, bug reporting, and issues, please reach out to us over at [support@algolia.com](mailto:support@algolia.com). 

Thanks for your submission!
