### ISSUE TITLE
Duplicate items in the Indexing Queue.

### ISSUE THREAD

**Issue by stephan-cream** [algolia/algoliasearch-magento-2#1046]
**System information**
Magento 2: Community edition 2.3.5
PHP: 7.3
Algolia Search module: 1.13.1

**Pre-requisites**
- Single storeview
- Indexing enabled.
- Indexing Queue enabled (under Stores -> Configuration -> Algolia Search -> Indexing Queue / Cron).

**I want to report a bug**
There are duplicate items in the Indexing Queue.

**What is the current behaviour?**
When i save a single product 10 times in a short period (within 5 minutes), there are 10 items in the Indexing Queue.
This leads to an increased operation count which is undesirable.
Even more so when you have multiple storeviews.
10 items x 3 storeviews = 30 operations, while 1 sync per storeview which would only require 3 operations would be enough.

**What is the expected behaviour?**
The expected behaviour is that there is only a single item in the Indexing Queue for the saved product.
Having duplicates serves no purpose, as the latest product data is synced to Algolia even if only the first item in the queue is run.
A method (such as rebuildStoreProductIndex) should only be run once per product.
Any given product should only occur once per storeview and method, only when the product is no longer in the queue and updated should it be added to the queue.

**What is the proposed solution?**
Add duplicates prevention logic so that a product is not being synced unnecessarily.
Do this by checking if a product id is in the queue already with the given method & storeview combination.
E.g:

**This should NOT be able to occur, as it is a duplicate which serves no purpose.**
job_id|created|locked_at|pid|class|method|data|max_retries|retries|error_log|data_size|is_full_reindex
------|-------|---------|---|-----|------|----|-----------|-------|---------|---------|---------------
1|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":1,"product_ids":[6230]}|3|0||1|0
2|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":1,"product_ids":[6230]}|3|0||1|0

**This should be allowed as it is for multiple storeviews.**
job_id|created|locked_at|pid|class|method|data|max_retries|retries|error_log|data_size|is_full_reindex
------|-------|---------|---|-----|------|----|-----------|-------|---------|---------|---------------
1|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":1,"product_ids":[6230]}|3|0||1|0
3|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":2,"product_ids":[6230]}|3|0||1|0

**This should NOT be able to occur, 6230 needs to be removed from the item with id 4.**
job_id|created|locked_at|pid|class|method|data|max_retries|retries|error_log|data_size|is_full_reindex
------|-------|---------|---|-----|------|----|-----------|-------|---------|---------|---------------
1|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":1,"product_ids":[6230]}|3|0||1|0
4|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":1,"product_ids":[6229, 6230]}|3|0||1|0

**This should be allowed as it is for multiple storeviews.**
job_id|created|locked_at|pid|class|method|data|max_retries|retries|error_log|data_size|is_full_reindex
------|-------|---------|---|-----|------|----|-----------|-------|---------|---------|---------------
1|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":1,"product_ids":[6230]}|3|0||1|0
5|2020-06-24 11:00:18|NULL|NULL|Algolia\AlgoliaSearch\Helper\Data|rebuildStoreProductIndex|{"store_id":2,"product_ids":[6229, 6230]}|3|0||1|0

**Comment by bsuravech** [comment]
Hi @stephan-cream,

Thanks for submitting your feedback here regarding duplicated items in the indexing queue. As the indexing queue handles not only product data indexing, the current strategy for the indexing queue is to batch jobs and merge based on method and store ID before each run is executed. You are right that duplicated items added later in the queue that aren't batched in this first merge, but will be processed in a later run. This is a flaw that we recognize in the indexing queue. 

We hear your feedback and have added it to our community board as well as our internal productboard for future improvements to the indexing queue. If you have any further feedback or questions, please feel free to reach out us at [support@algolia.com](mailto:support@algolia.com). Thank you for your thorough issue! We really appreciate your insights on this.
