### ISSUE TITLE
Reindexing fails when not all stores need algolia

### ISSUE THREAD

**Issue by palviggi-flagbit** [algolia/algoliasearch-magento-2#1053]
We have a multistore setup. Not all stores will use algolia, and those that use it are with different AppID, so default is left empty.

**Bug: What is the current behavior?**
Indexing fails with message:
`You need to configure your Algolia credentials in Stores > Configuration > Algolia Search.`

**Bug: What is the expected behavior?**
Indexing/Reindexing should work normally.

**Bug: What is the proposed solution?**
Don't check for the credentials at the start of the index process, it should be checked on each store after we check if indexing is enabled for that store.
The code that actually uses the appid should be checked to make sure it's using the current store config.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia Extension 2.0.0

**Comment by bsuravech** [comment]
Hi @palviggi-flagbit! Thanks for opening an issue. At this time the extension is not compatible with multi AppIDs. We recommend that you have different prefixes per store if that helps with sorting your indexes within the single app. 

We have heard this feedback before and we are aware of this issue. We will send this over to our own Community Board for future improvements as well as our internal productboard. 

If you have any future questions or feedback, please feel free to reach us over at [support@algolia.com](mailto:support@algolia.com). Thanks for your contributions and for this!

**Comment by palviggi-flagbit** [comment]
If it's not compatible with multiple appIDs, at least the credentials should not have the store_view scope then :(

Having different prefixes helps with sorting the data (it is actually mandatory to avoid the pages index showing data from different domains mixed together), but it doesn't help when different stores have a different paid plan.
