### ISSUE TITLE
Error When Reindex in 1.0.3 with Magento EE 2.1.2

### ISSUE THREAD

**Issue by mhistihori** [algolia/algoliasearch-magento-2#111]
After installing and config the module, Iam trying to reindex. I got this SQL error.

> Algolia Search Products indexer process unknown error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'backend.entity_id' in 'field list', query was: SELECT CONCAT(backend.store_id, '-', backend.entity_id), `backend`.`value` FROM `catalog_category_entity_varchar` AS `backend`
 INNER JOIN `catalog_category_entity` AS `category` ON backend.entity_id = category.entity_id AND (category.created_in <= 1 AND category.updated_in > 1) WHERE (backend.attribute_id = '45') AND (category.level > 1)
Algolia Search Categories indexer process unknown error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'backend.entity_id' in 'field list', query was: SELECT CONCAT(backend.store_id, '-', backend.entity_id) AS `key`, `category`.`path`, `backend`.`value` FROM `catalog_category_entity_int` AS `backend`
 INNER JOIN `catalog_category_entity` AS `category` ON backend.entity_id = category.entity_id AND (category.created_in <= 1 AND category.updated_in > 1) WHERE (backend.attribute_id = '46') ORDER BY `backend`.`store_id` ASC, `backend`.`entity_id` ASC

Algolia Search Pages index has been rebuilt successfully in 00:00:01
Algolia Search Suggestions index has been rebuilt successfully in 00:00:00
Algolia Search Suggestions index has been rebuilt successfully in 00:00:00
Algolia Search Queue Runner index has been rebuilt successfully in 00:00:00
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:04
Catalog Rule Product index has been rebuilt successfully in 00:00:03
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product/Target Rule index has been rebuilt successfully in 00:00:04
Target Rule/Product index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:01

**Comment by JanPetr** [comment]
Hello @mhistihori,
thanks for the report. Yes, there is a bad dependency and the column is not set correctly. It'll be fixed in the new version, PR is #97.
You can update the extension from `dev-master` with composer and it'll be fixed.
