### ISSUE TITLE
Algolia filter expand and collapse

### ISSUE THREAD

**Issue by ia-gaurav** [algolia/algoliasearch-magento-2#1153]
i want siderbar filter options to be collapsed by default , click event to expand it, let us know steps for same

**Comment by bsuravech** [comment]
Hi @ia-gaurav, 

Please reachout to [support@algolia.com](mailto:support@algolia.com) with your questions regarding customisation. We are reserving the Issues for BUGS only. 

To help you out, please review this documentation on how the extension implements panel options and how to extend it:
https://www.algolia.com/doc/integration/magento-2/getting-started/upgrading/?client=php#collapsible

If you have any further questions, please reach out to our support inbox. Thanks.
