### ISSUE TITLE
Enhancement for algolia_subproducts_index event

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#118]
Hi,
In helper ProductHelper.php method getObject adds type_id after event algolia_subproducts_index.
Would be great to add it before event and have this information about type into this event. Because if need to add some data that depends on type(swatches for configurable or additional data about bundle products) - need to reload product into Observer and check its' type. 
For fix need move [line](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L806) before line 800 in ProductHelper.php.
It`s  applicable for Magento 1 extension  too.

**Comment by JanPetr** [comment]
Hello @vmalyk,
sorry for the late answer. I implemented it in #136 and it'll be part of the next release.
