### ISSUE TITLE
[Magento 2.1] Missing client and version file are missing in this extension

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-magento-2#121]
A user reports that files are missing in the extension.

Using Magento 2.1.

Update: 

The PHP API Client is missing, composer does not seem to work for the user.

Installation steps:

- step1: downloaded extension from marketplace,
- step2 : uploaded unzip file under code folder
- step3: run php bin/magento setup:upgrade
- step4: run php bin/magento setup:static-content:deploy

**Comment by JanPetr** [comment]
Hey @rayrutjes, this is not supported way on how to install the extension.

There is a friction between copying files and composer install, co we support only composer installation. Either by composer directly or via Magento's Component Manager.
The installation is documented here: https://community.algolia.com/magento/doc/m2/getting-started/#install-the-extension
