### ISSUE TITLE
Even if disabled instand search is disabled sort indicies are created

### ISSUE THREAD

**Issue by rafal-kos** [algolia/algoliasearch-magento-2#123]
Hello,

I have question : if instant search pages are disable should module create sort indicies? In code of ```ProductHelper``` I see something like that :

````
$sorting_indices = $this->config->getSortingIndices($storeId);

        if (count($sorting_indices) > 0) {
}
````

Shouldn't be there also some check if instant pages are enabled/disabled?

**Comment by JanPetr** [comment]
Hello @rafal-kos,

you are right. Right now, if IS is not enabled there is no need for creating sort indices. Thanks for the report.

I will keep the issue open and address it in upcoming versions.
