### ISSUE TITLE
Easier integration with Ultimo theme

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento-2#125]

**Comment by progressiveparts** [comment]
@JanPetr - have you got any further with this??

**Comment by JanPetr** [comment]
Hello @progressiveparts, little bit. We're working on it, should be soon, but I don't have any precise ETA currently. Bear with us for a little bit more

**Comment by progressiveparts** [comment]
Hey @JanPetr , thanks for getting back to us. Look forward to seeing what you've got, we're struggling with this integration! cheers.

**Comment by simonmaass** [comment]
i am trying to include algolia with the ultimo theme - could you maybe provide ur challenges and solutions?

**Comment by simonmaass** [comment]
for example the moment i click on a product in the auto-completion menu from algolia search i can see that behind the dropdown the ultimo auto-completion menu is visible - any idea how i can disable this?
