### ISSUE TITLE
Product Miscount in Categories

### ISSUE THREAD

**Issue by richdynamix** [algolia/algoliasearch-magento-2#127]
I am investigating an issue as reported here #99 so I decided to turn on "Show in Menu" to check if products would appear in the category. This did in fact fix the issue but there seems to be a mismatch of products. In this category Magento reports **34** products, as does the Algolia dashboard, however I only see **29** in the results in the category. 

I also noticed that Algolia reports this category as `include_in_menu: null` within the dashboard. As I did just change this in Magento I decided to check other categories and they are all showing this value as `null`

<img width="293" alt="screen shot 2016-12-13 at 07 42 10" src="https://cloud.githubusercontent.com/assets/1104549/21131697/0b45d7bc-c108-11e6-9335-af980c6bc788.png">

<img width="390" alt="screen shot 2016-12-13 at 07 42 31" src="https://cloud.githubusercontent.com/assets/1104549/21131699/0d32b644-c108-11e6-8e78-d1aefde555d4.png">

<img width="308" alt="screen shot 2016-12-13 at 07 42 52" src="https://cloud.githubusercontent.com/assets/1104549/21131702/108d3f4e-c108-11e6-9d0f-be801bed0925.png">

Thanks again.

**Comment by JanPetr** [comment]
Hello @richdynamix,

it might happen when some products in the category are disabled, out of stock or invisible. Might that be the case on your side?

**Comment by richdynamix** [comment]
@JanPetr 

Unfortunately this is not the issue. These are the default checks Magento does when determining if a product should be shown in the category page. If I turn off the instant search replacement for Magento categories and use the default Magento category then the correct number of products are returned. Is there another check being used to determine the visibility here? Are you taking into account if a product has been marked to not track stock in the admin?

**Comment by JanPetr** [comment]
Hello @richdynamix,

sorry for the late answer.
No, there shouldn't be any extra check. Do you know which exact products are not being indexed in the category? Can you investigate how they are different from those which actually are indexed?
Thanks!

**Comment by JanPetr** [comment]
As I didn't hear from you anymore, I'm closing the issue. Feel free to reopen.
