### ISSUE TITLE
Rating summary missing in results

### ISSUE THREAD

**Issue by richdynamix** [algolia/algoliasearch-magento-2#129]
The review rating summary is missing from the category and search result pages. I have added the `rating_summary` to the attributes configuration in Magento and I have reindexed the data but this is not shown in the frontend. The `rating_summary` has been indexed as seen here - 

<img width="226" alt="screen shot 2016-12-16 at 08 23 43" src="https://cloud.githubusercontent.com/assets/1104549/21256240/17225eee-c369-11e6-8660-f7a32568db24.png">

And I can see where it is suppose to be used in the frontend `hit` template - 

<img width="783" alt="screen shot 2016-12-16 at 08 23 58" src="https://cloud.githubusercontent.com/assets/1104549/21256255/2bb5a97e-c369-11e6-8af9-7d595fcd3e83.png">

I am not sure if this is an issue in the retrieval of the object or in the JavaScript itself. It's worth noting that I don't see any products in your demo site that has the `rating_summary` stars. I do see it on your Magento 1 demo though.

Is this a known issue?

**Comment by richdynamix** [comment]
Having looked into this a little further it would appears there is no CSS property to add the stars background image. The width of the background image is being applied from the summary but no CSS to pull in the correct styles.

**Comment by JanPetr** [comment]
Hello @richdynamix,
so I got that the `rating_summary` attribute is retrieved and rendered correctly to HTML, right?

Indeed there is missing CSS for rating starts. We will add it in upcoming versions, thank you for reporting. If you've written the CSS code yourself, feel free to send a PR. I'll be happy to merge.
