### ISSUE TITLE
Indexed URLs are wrong

### ISSUE THREAD

**Issue by vkranjith** [algolia/algoliasearch-magento-2#132]
The indexed URLs for categories and products are wrong in Magento 2.1.3. I didn't check it in other versions.

The URL is supposed to be [http://magento_ce_213.test.com/bruno-compete-hoodie.html](http://magento_ce_213.test.com/bruno-compete-hoodie.html) 
But gives [http://magento_ce_213.test.com/**magento**/bruno-compete-hoodie.html](http://magento_ce_213.test.com/magento/bruno-compete-hoodie.html) 

You can notice that the second URL has additionally "magento/" in-between. 
Is there any setting to remove this?

Thanks,
Ranjith

**Comment by JanPetr** [comment]
Hello @vkranjith,

sorry for the late answer. The extension [fetches product's URL directly from Magento](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L561), without any modifications. Isn't it possible you have set wrong base URLs in **Stores > Configuration > General > Web > Base URLs**?

<img width="840" alt="screenshot 2017-01-09 15 44 05" src="https://cloud.githubusercontent.com/assets/1058144/21788265/818e7156-d682-11e6-9390-175e68bd5b5c.png">

**Comment by dhduc** [comment]
Hi guys,
This issue still happens, the details as below:
- I push index to remote host by bin/magento: 
```
php bin/magento indexer:reindex algolia_products
```
The URL of product return [/magento/minerva-lumatech-trade-v-tee.html](/magento/minerva-lumatech-trade-v-tee.html), it should be [/minerva-lumatech-trade-v-tee.html](/minerva-lumatech-trade-v-tee.html).

- By another way, I using n98 magerun v2 for magento 2 alternative for bin/magento:
```
n982 indexer:reindex algolia_products
```
In this case, the URL of product return [n982/minerva-lumatech-trade-v-tee.html](n982/minerva-lumatech-trade-v-tee.html).

Please investigate, thanks.

**Comment by JanPetr** [comment]
Great catch @dhduc, thanks a lot for that! 💯 
I wrote a FAQ entry to our documentation page: https://community.algolia.com/magento/faq/#the-indexed-urls-from-my-magento-2-store-are-wrong-there-is-additional-magento-in-the-middle-of-indexed-urls

Thanks a lot again.

I'm closing the issue now, but if you have any other remarks or questions, feel free to reopen.
