### ISSUE TITLE
Missing product default_original_formated price

### ISSUE THREAD

**Issue by dhduc** [algolia/algoliasearch-magento-2#148]
Hi guys,
I'm working on Algolia search for Magento 2, I set a product with a special price and push its index to the remote host:

![remote](https://cloud.githubusercontent.com/assets/11469236/22146545/965985ae-df37-11e6-8a39-34fde06a111a.png)

But the result object return not contain **default_original_formated** data:

![result](https://cloud.githubusercontent.com/assets/11469236/22146746/4a8e9bf4-df38-11e6-9b5e-97f5f036ab7a.png)

Is there any thing wrong happen in this case? 

Thanks.

**Comment by JanPetr** [comment]
Hello @dhduc,
thanks for the report. 
Could you send us an e-mail to support+magento@algolia.com and providing us with your APP ID and, if possible, a live website where I could reproduce the issue? Thanks!

**Comment by dhduc** [comment]
Hi @JanPetr,
I have just sent a report email to the inbox support+magento@algolia.com, please check with email by subject '[Report Issue] Missing product default_original_formated price'. Thanks.

**Comment by JanPetr** [comment]
Thanks for sending a message there, @dhduc.
I responded and fixed the issue in #151.

Closing the issue now.
