### ISSUE TITLE
The configuration for isAddToCartEnabled not working

### ISSUE THREAD

**Issue by dhduc** [algolia/algoliasearch-magento-2#150]
Hi guys,
I want to turn off the displaying **Add To Cart** button on each product in Instant Search Page,
I set the its configuration in Algolia Search Configuration is No, but not working.
I found out the reason as below:
- The Javascript consider the "0" value is False value, but the result of the expression if ("0") also return True, so it not working.

You can check this on the my test site: [http://magento2.newbie-dev.net/gear/bags.html](http://magento2.newbie-dev.net/gear/bags.html)

Please check. Thanks.

**Comment by JanPetr** [comment]
Thanks for the report @dhduc, I fixed it in #150. Feel free to apply the patch or update to `dev-master`.
