### ISSUE TITLE
Fishpig Wordpress integration

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento-2#153]
Just a suggestion: it would be nice if there was a integration for the [Fishpig Wordpress Integration](https://fishpig.co.uk/magento-2/wordpress-integration/) plugin so blog posts are searchable too, just like Magento pages.

**Comment by JanPetr** [comment]
Good idea, will get to it :)

**Comment by JanPetr** [comment]
@royduin Wouldn't it work to install [Algolia WP plugin](https://community.algolia.com/wordpress/), index WP content through this plugin and then just add a new datasource to Magento's autocomplete menu which targets the WP indices?

**Comment by royduin** [comment]
That could work, but the Fishpig module integrates the post into Magento so the URL's change. For example in the Wordpress backend a post url/permalink is: http://website.com/wp/post, but the post can be accessed with http://website.com/blog/post through Magento because "blog" is configured as home url in Magento.

**Comment by royduin** [comment]
Meanwhile I've created a module to solve this issue: https://github.com/just-better/magento2-algolia-wordpress-integration

**Comment by JanPetr** [comment]
Hey @royduin,

I'm closing the issue in favor of your module. Great job there! ❤️

**Comment by SyedMuneebb** [comment]
FishPig WordPress Magento integration module can solve your issue. I have tested and implemented this plugin in Magento 2. Also, created a tutorial on it: [Guide for Magento WordPress Integration](https://magenticians.com/magento-wordpress-integration/)

Hope it will help!

**Comment by royduin** [comment]
Spam 👆🏻

**Comment by bentideswell** [comment]
> That could work, but the Fishpig module integrates the post into Magento so the URL's change. For example in the Wordpress backend a post url/permalink is: http://website.com/wp/post, but the post can be accessed with http://website.com/blog/post through Magento because "blog" is configured as home url in Magento.

I know I'm a little late but I've had a few support emails referencing the above quote so I just wanted to clear up that [Magento WordPress Integration](https://fishpig.co.uk/magento/wordpress-integration/) doesn't change the URLs and what ever the URL is configured as in WordPress is the URL that will be used in Magento. This is true for all WordPress content (posts, terms etc).

Your solution sounds great though and using the REST API is always a simple yet effective solution.

**Comment by bentideswell** [comment]
This doesn't change the URL. This just allows you to set the WordPress Home URL to be the Magento base URL. The URLs produced by my module/Magento still match those configured in WordPress exactly.

**Comment by royduin** [comment]
It's a while back I was working on this but it's not changing de urls literally. I though this was the reason:

In most cases the Magento store is running on `/` and Wordpress is installed in for example `/blog` so urls will be; `/blog/post` but with the root extension it will be `/post` but I don't want Algolia to have `/blog/post` in the index which is what https://github.com/algolia/algoliasearch-wordpress will do as @JanPetr suggested. That's the reason we've created the module so just `/post` will be indexed.

**Comment by royduin** [comment]
Sounds logical but in that case we could just use https://github.com/algolia/algoliasearch-wordpress, it's too long ago for me, I've really no other idea why we've created that module. It had something to do with the urls.

**Comment by bentideswell** [comment]
I'm not sure and I haven't looked into it. You're welcome to look into it and if you do have issues, get in touch. I would be happy to help.

I only commented because several people have seen your comment and emailed me for clarification and I wanted to stop this from happenening.
