### ISSUE TITLE
Magento 2 Algolia Search not working from Amasty Layered Navigation 

### ISSUE THREAD

**Issue by lukaszborowiec** [algolia/algoliasearch-magento-2#157]
If I have installed Amasty Layered Navigation and Search Algoli in one shop. I can't filter products in category view. Used Filter return all products from collection. If I remove Algoli Search from shop filter working good. How can I solve the problem?

**Comment by JanPetr** [comment]
Hey @lukaszborowiec, thank you for the report.

To be honest, the extension is not tested with "Amasty Layered Navigation". We will investigate and see what we can do to make those two extensions to work together.

**Comment by lukaszborowiec** [comment]
Hey @JanPetr, how goes investigation in this issue?

**Comment by JanPetr** [comment]
Hello @lukaszborowiec,

I'm on it right now, but I'm kind of stuck and I'd really appreciate your help. Could I ask you few quesitons?

The category page you're referring to is rendered by Magento and should be power by Magento (Amasty Layer Navigation)? Or should it be power by Algolia?

When you disable the Algolia module, it starts to work just like that or do you have to do anything besides disabling Algolia? Like some kind of reindex or something?

Thank you for any help!

**Comment by lukaszborowiec** [comment]
Hey @JanPetr,
Q1: Category page should be power by Amasty Layered Navigation.
Q2: When Algolia is disabled, I cleaning the cache and run category reindex.

**Comment by JanPetr** [comment]
Hello @lukaszborowiec,

thanks for your answers.
So when you just disable Algolia the categories still show "wrong" products?
You need to clean the cache and do category reindex to make it work properly?

It looks like there is some indexing collision between Algolia and Amasty category indexing, so when you have Algolia enabled Amasty cannot index categories properly and therefore "wrong" products are shown on category page.
Do you know if Amasty Layered Navigation adds its own category indexer or does it use standard Magento indexers?
<img width="1301" alt="screenshot 2017-03-14 09 56 49" src="https://cloud.githubusercontent.com/assets/1058144/23892873/ac495162-089c-11e7-9a8b-6dffa928d745.png">

Thanks a lot for your help!

**Comment by JanPetr** [comment]
Hello @lukaszborowiec,

could you try to apply #193 if it fixes your issue? Thanks!

**Comment by lukaszborowiec** [comment]
Hello @JanPetr,
yes I can try check this solution!
Thanks for your help!

**Comment by JanPetr** [comment]
Perfect, let me know how it goes!

**Comment by JanPetr** [comment]
Hello @lukaszborowiec,

the issue should be finally fixed by #200. Can you give it a try and let me know how it goes? Thanks!

**Comment by theflyingfork** [comment]
Hi There,

We've run into a similar issue here too. Does not seem like solution is available yet?

We've decided to implement Algolia Search plugin for Magento 2 on our site to replace the default search functionality.

This is now working for basic searching of the catalog, however the refine filters provided by Amasty Advanced Layered Navigation plugin on the search results page are now not filtering the results as they used to. https://amasty.com/improved-layered-navigation-for-magento-2.html 

for example on https://theflyingfork.com.au/catalogsearch/result/?q=mug choosing to refine/filter the results by any of the filters displayed on the right for example Price does not filter the displayed results correctly to just those in the price range. 

We basically need to have the ability to have the search autocomplete suggest functionality of Algolia combined with the ability to refine these results on the Search result page using the Amasty plugin which we have working / looking the way we want. eg this see it working on the Category page here: https://theflyingfork.com.au/crockery/bevande?cat=191

Please help/advise.

Thanks,

Daniel

**Comment by niners52** [comment]
I am debating on signing up for Algolia but have Amasty Layered Navigation. Was this issue resolved?
