### ISSUE TITLE
category page blank after install algolia search extension

### ISSUE THREAD

**Issue by dungnv** [algolia/algoliasearch-magento-2#16]

**Comment by JanPetr** [comment]
Hello @dungnv, did you only install the extension? Or did you set some specific configurations?
Can you send us a live website with the issue?

**Comment by dungnv** [comment]
Hello Jan,

We have install newest version and configuration in admin, the quick suggestion working correct now but missing image: http://inika.convert.build/
the category page blank.

Thanks.

**Comment by JanPetr** [comment]
@dungnv, are there any errors in your browser's console? I'm not able to access the webpage, authorization required. Can you drop us an e-mail to support+magento@algolia.com?

**Comment by JanPetr** [comment]
@dungnv Any update on your issue?
