### ISSUE TITLE
Algolia sortable breaks admin attribute option table

### ISSUE THREAD

**Issue by dannynimmo** [algolia/algoliasearch-magento-2#161]
The file `view/adminhtml/layout/default.xml` loads Algolia's JS bundle, and includes a JS snippet at the bottom of the page.

This causes conflicts with Magento 2 core table sorting in the admin, for example in the attribute config page:

![screenshot of error](https://cloud.githubusercontent.com/assets/4489348/23288683/f80afe3c-fa98-11e6-880a-d5562ea4c672.png)

I think this block & JS bundle should only be loaded on the system configuration page, and ideally only apply to Algolia tables.

**Comment by JanPetr** [comment]
Thank you for the report @dannynimmo, we will take a look.
