### ISSUE TITLE
Backend Not Working

### ISSUE THREAD

**Issue by Moinashraf** [algolia/algoliasearch-magento-2#164]
Hello,

I have an issue for backend.If I setup this module the admin panel break up.

**Comment by JanPetr** [comment]
Hello @Moinashraf,

Can you see any error message? What exactly doesn't work? Would you mind sharing with me a screenshot of not-working page?

**Comment by apmson** [comment]
looks like you used a wrong js file with a wrong path.
I only found algoliaAdminBundle.min.js

Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/algoliaAdminBundle.js'

**Comment by JanPetr** [comment]
Hello @apmson,
thanks for that. I fixed it yesterday and released as 1.0.8 version. Feel free to update.

I'm closing the issue now. If your issue doesn't relate to the JS one, feel free to reopen @Moinashraf.
