### ISSUE TITLE
Categories Filter issues

### ISSUE THREAD

**Issue by apmson** [algolia/algoliasearch-magento-2#173]
"categories_without_path" only showing the second level when you are already on first, second or third level category page.(Disjunctive)

**Comment by JanPetr** [comment]
Hello @apmson,

could you please provide me with more information? I'm not sure I quite understand.
Screenshot or live website could help.

Thanks!

**Comment by JanPetr** [comment]
Hello @apmson,

as I didn't hear from you anymore I'm closing the issue. Feel free to reopen.
