### ISSUE TITLE
Reindexing of products data is not happening properly because of rating_summary. 

### ISSUE THREAD

**Issue by kanhaiya5590** [algolia/algoliasearch-magento-2#180]
Reindexing of products data is not happening properly because of rating_summary. 
If we add rating summary attribute in magento2 admin panel like

`ALGOLIA SEARCH -> Products ->Attributes -> rating_summary`

and after that we do reindex, only few products added to algolia which have no rating record in `review_entity_summary` table.

I checked Data helper `vendor\algolia\algoliasearch-magento-2\Helper\` [Data.php](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Data.php#L525-L527)

I feel some issue will be related to joinField  "left|inner".

**Comment by JanPetr** [comment]
Hello @kanhaiya5590,

thanks for the report. Looks like it's `inner join` issue indeed. I'll investigate and come back to you.

**Comment by JanPetr** [comment]
Hello @kanhaiya5590,

would you mind sharing with me what exact version of MySQL you use? Thank you for your help!

**Comment by JanPetr** [comment]
Feel free to update to `dev-master` @kanhaiya5590, the issue should be fixed :) Thanks for report 💯
