### ISSUE TITLE
Absolute URL to indexed images are wrong when using /pub as Magento's document root

### ISSUE THREAD

**Issue by stianmartinsen** [algolia/algoliasearch-magento-2#182]
If I'm using Magento's /pub folder as document root for the vhost setup, the absolute URL for the product images are wrong:

The indexed URL `http://magento:81/pub/media/catalog/product/cache//75x75/beff4985b56e3afdbeabfc89641a4582/1/8/1844-adidas-originals-graphic-t-shirt-for-men-5.jpg` throws a 404, because I'm already in the pub folder.

---------

Also, is it possible to make Algolia index the image URLs as relative URLs instead of absolute? In case anyone in my dev team has a different root URL or run on a different port.

**Comment by JanPetr** [comment]
Hey @stianmartinsen,

thanks for the report. It looks like it's the same issue as @toddhainsworth wants to fix with #179 Can you confirm that?

The reason behind indexing absolute URLs is for example CDNs, when the domain is not the same one as the main store's domain. I'm not sure how to approach it safely with relative URLs indexed.

**Comment by stianmartinsen** [comment]
Yes, that seems to address the issue. I guess this can be closed.

Still, I'm a little bit confused about whether or not this fix is required. I thought requests to /pub/* were supposed to be picked up by the nginx-config (in my case) and redirected to the correct folder..?

From the nginx config:

```nginx
location /pub/ {
    location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
        deny all;
    }
    alias $MAGE_ROOT/pub/; <---------
}
```

**Comment by stianmartinsen** [comment]
The alias I was talking above indeed works, I just had the wrong $MAGE_ROOT after moving my installation. So I guess #179 isn't really necessary..?

**Comment by JanPetr** [comment]
Thanks @stianmartinsen for additional info.
It seems it's not necessary anymore. Let's close it for now.

Thank you! :) 💯
