### ISSUE TITLE
getPriceKey function not returning any value on hit.phtml

### ISSUE THREAD

**Issue by vaimeo** [algolia/algoliasearch-magento-2#19]
everything seems to be fine just getPriceKey not resturing anything and its not using \Algolia\AlgoliaSearch\Block\Instant\Hit $block

**Comment by JanPetr** [comment]
Hello @vaimeo,
I'm not able to reproduce your issue. Do you use the latest revision? When it does not return anything?

**Comment by JanPetr** [comment]
Hey @vaimeo,
sorry for the wrong information. I tested it on Autocomplete templates. Now I reproduced. Fix is coming!
