### ISSUE TITLE
Algolia Search adapter returns wrong items count number in product list

### ISSUE THREAD

**Issue by nntoan** [algolia/algoliasearch-magento-2#192]
Hello,

As the title said, Algolia Search is returning wrong item count number in product list page (catalogsearch page too). To reprocedure this issue. You can following the steps below:

1. Install Magento 2 with Sample Data (important)
2. Reindex all first time before install Algolia Search
3. Install Algolia Search latest version via Composer
4. Fill needed information like Credentials then reindex all
5. Go to product list and you will see the wrong item count number.

Any advise?

**Comment by JanPetr** [comment]
Fixed in #200
