### ISSUE TITLE
Multi store with multi currency issue

### ISSUE THREAD

**Issue by dhduc** [algolia/algoliasearch-magento-2#199]
Currently, I using Magento 2.1.5 and Algolia Search extension 1.0.8 with multi-stores and multi-currencies with configuring as below and USD as base currency:

| Store        | Default display currency           | 
| ------------- |:-------------:| 
| US     | USD |
| UK      | GBP      |
| CA  |CAD     |

In the handlePrice function of ProductHelper:

```
$price = $priceInfo->getPrice('regular_price')->getValue();
$price = $this->currencyDirectory->currencyConvert($price, $baseCurrencyCode, $currency_code);
```

https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L384

The price of the product after reindex is wrong, in the UK store, the price for USD will be multiplied by the rate of GBP, corresponding to other stores. So I track inside to the getValue() and found out the price was converted from base currency to default display currency.

After that, the currencyConvert function will convert price again from $baseCurrencyCode to $currency_code.

**Comment by JanPetr** [comment]
Hello @dhduc,

so it looks like that the `$price = $this->currencyDirectory->currencyConvert(...)` line breaks the price for you as the correct price is already returned by the first `getValue()` line?

**Comment by dhduc** [comment]
I mean that the ``` $priceInfo->getPrice('regular_price')->getValue()``` get wrong price, it multiplied by the rate of store currency.

**Comment by JanPetr** [comment]
Thanks @dhduc,

so in the end `$priceInfo->getPrice('regular_price')->getValue()` gets the right price, but it's converted once more which results in indexing wrong price.
I'll investigate and come back to you when I have a solution.

**Comment by JanPetr** [comment]
Hello @dhduc,
I just merged a fix to master branch. Feel free to give it a try. I'll appreciate any feedback from your side. Thanks! 👍
