### ISSUE TITLE
Implement tier pricing feature

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento-2#204]

**Comment by webcrew-au** [comment]
+1 need this functionality, like default M2 ie  "$x.xx As low as: $x.xx"

**Comment by theflyingfork** [comment]
Hi algoliasearch-magento-2 developers,

We are seeking the services at a agreed rate of a freelance developer suitably experienced in customisation of algoliasearch-magento-2 instantsearch.js functionality to replicate the our current store catalog browsing, search and brands page functionality whilst maintaining our store's seo/sem optimisations which features the display of tiered pricing in search results.

If this is task is of interest please email relevant magento 2 examples of your work and a brief summary of customisations made to instant-search@theflyingfork.com.au. 

@Moderators - Appologies if this is not the apporpriate forum. Please take this down if in violation forum rules.

Thanks.

**Comment by damcou** [comment]
Added to the features list in our roadmap.
