### ISSUE TITLE
Cannot save settings into temp indices

### ISSUE THREAD

**Issue by phupt** [algolia/algoliasearch-magento-2#206]
Hi 

As i checked, at ProductHelper, you call this code to check if we use Temp Indices

if ($saveToTmpIndicesToo === true) {
            $this->algoliaHelper->setSettings($this->getIndexName($storeId, true), $mergeSettings);
        }
But actually, when we enable queue, you pass $saveToTmpIndicesToo as "1" or "0" instead of true/false.
So this code does not happen and we cannot save setting into Temp. 

As a result, when you move Tmp Indices to Search Indices. I will remove all settings of Search Indices

**Comment by JanPetr** [comment]
Hello @phupt, this issue [was fixed](https://github.com/algolia/algoliasearch-magento-2/pull/186
) in [1.0.9](https://github.com/algolia/algoliasearch-magento-2/releases/). Feel free to upgrade.
