### ISSUE TITLE
JS hooks from M1 version 1.9.0 to M2

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#213]
Please move js hooks from our released module for M1 to M2, but with small improvement: Events in configuration.phtml and all code - Move to Block or model with configuration. For example, You can look module-tax and how Magneto works with this class

**Comment by JanPetr** [comment]
Thanks @vmalyk,

it's on our roadmap. I'll take a look at that module.

**Comment by JanPetr** [comment]
Hello @vmalyk,

I refactored `configuration.phtml` a bit and moved all the logic to `Block` class and added a custom event for modifying the configuration. Can you check #238 and give me your feedback? Anything would be highly appreciated. Thanks! 💯

**Comment by JanPetr** [comment]
And the rest of hooks / events are implemented in #240, if you could find some time to review and provide feedback, it'd be awesome @vmalyk!

**Comment by vmalyk** [comment]
Hello @JanPetr,
I`ve just reviewed and All look perfect, because lates solution provides to add custom widgets without override instantsearch.js and update widgets configuration and add new widgets to search. It`s perfect!

**Comment by JanPetr** [comment]
Thanks for the feedback, I'm about to merge it and I'd like to release a new version soon. I really appreciate your input! 💯

**Comment by JanPetr** [comment]
Merged, will be part of the next release.
