### ISSUE TITLE
Incorrect thumbnail url

### ISSUE THREAD

**Issue by eimantaaas** [algolia/algoliasearch-magento-2#214]
The thumbnail url path in autocomplete menu is incorrect. Algolia adds **pub** directory before media directory that causes broken image url.

Expected result: **media/catalog/product/cache/75x75/beff4985b56e3afdbeabfc89641a4582/p/i/pioneer-toraiz-as-1-4.jpg**
Actual result: **pub/media/catalog/product/cache//75x75/beff4985b56e3afdbeabfc89641a4582/p/i/pioneer-toraiz-as-1-4.jpg**

**Comment by stianmartinsen** [comment]
It is recommended to use the pub folder as the document root on your web server because it's safest not to publicly expose the system files.

If that's not possible in your case, I thought Magento was supposed to redirect both /media/* and /pub/media/* to the same place...? Maybe there is somewthing wrong with your redirects?

**Comment by eimantaaas** [comment]
I'm using the same ngnix config as it comes with Magento nginx.conf.sample so I think that's OK.

Magento returns correct images paths: without **pub** directory.

**Comment by eimantaaas** [comment]
@julienbourdeau No the files are under `/pub/media` dir as should be. But to access specific media file through browser url should be without `pub/` dir.

**Comment by ozzman6154** [comment]
I'm facing the same issue here.  This is for Magento Enterprise Cloud. Has there been any further update regarding this?

**Comment by julienbourdeau** [comment]
I found the reason of the problem. It seems that magento had a few troubles when using `pub/` as the root directory (see https://github.com/magento/magento2/issues/1146)

I'm trying to come up with an easy solution but so far the only thing I can think of is to add an option in the Algolia extension settings. I can't find any other way to know what rootdir is set in the server.

I think I'll do that, unless you know something better.

**Comment by julienbourdeau** [comment]
Hi @ozzman6154 and @eimantaaas,

Would be able to try this fix available here https://github.com/algolia/algoliasearch-magento-2/pull/247 please?
