### ISSUE TITLE
Undefined index: store_id in Queue

### ISSUE THREAD

**Issue by OlgaBurtyka** [algolia/algoliasearch-magento-2#219]
Hi! We run in root magento directory  command `bin/magento indexer:reindex algolia_queue_runner`
and get error

Algolia Search Queue Runner indexer process unknown error:
Notice: Undefined index: store_id in /vendor/algolia/algoliasearch-magento-2/Model/Queue.php on line 344

Do you have idea regarding this notice?

**Comment by OlgaBurtyka** [comment]
and also 
`php bin/magento indexer:reindex algolia_queue_runner
Algolia Search Queue Runner indexer process unknown error:
Warning: array_multisort(): Array sizes are inconsistent in /var/www/emma/emmamason/vendor/algolia/algoliasearch-magento-2/Model/Queue.php on line 355
`

**Comment by JanPetr** [comment]
Thanks @OlgaBurtyka,

I saw your support email with SQL file. I'll investigate and come back to you.

**Comment by JanPetr** [comment]
Sorted out via support e-mails.
The issue was that `data` column in `algoliasearch_queue` table was too small. I created a PR to enlarge it (#228).
Other thing is to investigate how's possible that so many product IDs was in a one row.
