### ISSUE TITLE
Broken charsets in page content after trim tags

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#220]
On indexing page content and trimming tags html charsets are broken and pushed to Algolia account: http://prntscr.com/ez1zm9. After add mb_convert_encoding($s, 'HTML-ENTITIES', 'UTF-8') in line 142: http://prntscr.com/ez20h7

**Comment by JanPetr** [comment]
Thank you for report @vmalyk, I will take a look and fix it soon.
