### ISSUE TITLE
Fatal error in Backend in Magento 2.1.6

### ISSUE THREAD

**Issue by antwake** [algolia/algoliasearch-magento-2#225]
HI there 

I'm on Magento 2.1.6 with Algolia 1.0.4

I followed the instructions here https://community.algolia.com/magento/doc/m2/getting-started/

And I get this error:
`Fatal error: Uncaught Error: Class 'AlgoliaSearch\Version' not found` [...] `public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php on line 28`

thanks!

**Comment by JanPetr** [comment]
Hello @antwake,
it looks like you installed the extension manually and not via Component Manager or Composer.
Can you pls describe how did you install the extension?

**Comment by antwake** [comment]
Yeah, because of my development environment, I need to first unzip the plugin folder on my local env then push it to my Bitbucket repo
So I used composer but only from the 2nd command (`bin/magento module:enable Algolia_AlgoliaSearch`) 

If I follow the exact steps, it definitely works, sorry for the confusion!

I will talk to my developers to find a way to install it by following their procedures.

Thanks for the help!

**Comment by JanPetr** [comment]
You are welcome, glad you made it work. I believe your developers will be able to find a way as well. Happy searching.
