### ISSUE TITLE
Not compatible with AheadWork gift card extension

### ISSUE THREAD

**Issue by dungnv** [algolia/algoliasearch-magento-2#230]
Algolia Search Products indexer process unknown error: Class  does not exist

Not compatible with aheadwork gift card extension https://ecommerce.aheadworks.com/magento-extension-updates/gift-card

**Comment by JanPetr** [comment]
Thanks @dungnv for the report, we will investigate and come back to you.

**Comment by damcou** [comment]
Hi @dungnv , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
