### ISSUE TITLE
[SEO] Only the first page of categories is indexed when instantsearch is on

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-magento-2#231]
If you got this url `example.com/women/tops-women.html` the category is displayed correctly but once you go to next page, the parameters are passed after the `#` in the URL so search engines won't index those page.

It would be good to know if indexing all pages is important and then see if we can improve this.

**Comment by JanPetr** [comment]
How do you know the page is crawled? And the page crawled is the one rendered by IS or by server?
