### ISSUE TITLE
[QUESTION] Result Page

### ISSUE THREAD

**Issue by danielozano** [algolia/algoliasearch-magento-2#243]
Hello, first of all congratulations for the great work on this Magento 2 module.

I don't know if github issues is the best place to write this question so I'm sorry, you can redirect me to any support email or whatever you like.

I'm trying this module, and for me it's extrange the fact that the module doesn't use the algolia search results on the result page. Is this feature part of the future functionality of the module? Or it's out of the scope of your features.

Thank you.

**Comment by danielozano** [comment]
Sorry didnt notice about the override of the search query: `<preference for="Magento\Framework\Search\Adapter\Mysql\Adapter" type="Algolia\AlgoliaSearch\Adapter\Algolia" />`

**Comment by JanPetr** [comment]
Hello @danielozano,

yes, the query is overridden there and you need to enable Make SEO request in the configuration to get results from Algolia.

If you have anymore question, feel free to ask :)
