### ISSUE TITLE
Not working with Multiple Website with same source.

### ISSUE THREAD

**Issue by vishveskrish** [algolia/algoliasearch-magento-2#248]
Hello Team,

We are not getting any result with multi store website.

Not working : https://beta.xxxxx.com/xxxx

Working : https://beta.xxxxx.com/yyyy 

Kindly let us know the reason behind it!

**Comment by ozzman6154** [comment]
Hi,

Try creating another application in Algolia Dashboard and then add this application id and api key to the other website in the extension setting.

**Comment by vishveskrish** [comment]
@Do we need to create new application for all other store-websites  ?

We have multi website setup.

Kindly confirm!

**Comment by vishveskrish** [comment]
@ozzman6154 :

Also we can't able to create new application in trial period.

" You cannot create new applications during the trial period"

**Comment by julienbourdeau** [comment]
Is your website accessible online? 

You should be able to get results from the same application.

**Comment by vishveskrish** [comment]
@julienbourdeau , Yes Our website can be accessible online.


Store1  : http://beta.mayvillagetrading.com/vapesupply/
Store2  : http://beta.mayvillagetrading.com/repairparts

**Comment by JanPetr** [comment]
Hello @vishveskrish,

it looks like you don't have any products indexed for your other websites besides "vepesupplies".
Can you make sure you've reindexed your data properly? Thanks

**Comment by vishveskrish** [comment]
Hello @JanPetr ,

We have done indexing but still showing the same!

**Comment by vishveskrish** [comment]
Just to update you that,
Below both are storeviews not different websites.
Store1 : http://beta.mayvillagetrading.com/vapesupply/
Store2 : http://beta.mayvillagetrading.com/repairparts

**Comment by vishveskrish** [comment]
Hey @JanPetr ,

We are awaiting for your response!

**Comment by JanPetr** [comment]
Hello @vishveskrish,

your indices for other stores besides "vapesupply" are still empty.
Do you have [indexing queue](https://community.algolia.com/magento/doc/m1/indexing/) enabled? Did you set up correctly a queue runner cron job? That could be a problem that your indexing jobs are stacked in a queue, but not processed.

Let me know if it's the case.

**Comment by JanPetr** [comment]
Hello @vishveskrish,

since I didn't hear from you I'm closing the issue. If you still experience the issue, feel free to re-open.
