### ISSUE TITLE
Incorrect block after upgrade to 1.1.0

### ISSUE THREAD

**Issue by rebha** [algolia/algoliasearch-magento-2#250]
Hi!
We get following exception when trying to go to algolia search page in frontend after upgrading to 1.1.0. Looks like the wrong block is used? Algolia\AlgoliaSearch\Block\Algolia instead of Algolia\AlgoliaSearch\Block\Configuration.

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Algolia\AlgoliaSearch\Block\Algolia::isSearchPage

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Algolia\AlgoliaSearch\Block\Algolia::isSearchPage
#0 /home/ateles/workspace/moller/magento/vendor/algolia/algoliasearch-magento-2/view/frontend/templates/internals/configuration.phtml(9): Magento\Framework\DataObject->__call('isSearchPage', Array)

**Comment by JanPetr** [comment]
Thanks for coming back to us :) 👍
