### ISSUE TITLE
After Installation to magento 2.1.6

### ISSUE THREAD

**Issue by AbdulKadir-Agoliya** [algolia/algoliasearch-magento-2#252]
Hi, 
           Move Module to root app/code directory then upgrade command and deploy command but magento admin is blank

**Comment by JanPetr** [comment]
Hello @AbdulKadir-Agoliya,

why would you move the module? Can you install it with Composer?

**Comment by JanPetr** [comment]
Hello @AbdulKadir-Agoliya,

since I didn't hear from you for a while I'm closing the issue.
If you still experience the issue, feel free to reopen.
