### ISSUE TITLE
Wrong type of value isEnabledBackend use at Algolia\AlgoliaSearch\Helper\Data

### ISSUE THREAD

**Issue by tanloi3004** [algolia/algoliasearch-magento-2#255]
In the class used Identical Compare 
`$this->configHelper->isEnabledBackend($storeId) === false`

but the result of the function Algolia\AlgoliaSearch\Helper\ConfigHelper:isEnabledBackend return mixed type
`public function isEnabledBackend($storeId = null)
    {
        return $this->configInterface->getValue(self::ENABLE_BACKEND, ScopeInterface::SCOPE_STORE, $storeId);
    }
`
So the application working does not properly.

**Comment by JanPetr** [comment]
Thanks for the report @tanloi3004! I just made a fix in #256, it'll be merged as soon as checks are finished.
