### ISSUE TITLE
Translation of "Pages" in sidebar in autocomplete 

### ISSUE THREAD

**Issue by rakibabu** [algolia/algoliasearch-magento-2#264]
Hi,

When I want to translate the "Pages" string in Magento 2 with the i18n packages, the string doesn't translate. I think because this is not a translatable string in the code. I found this code below in common.js on line 256:

```
if (section.name !== 'suggestions' && section.name !== 'products') {
	source.templates.header = '<div class="category">' + (section.label ? section.label : section.name) + '</div>';
}
```

Happy to hear from you guys.

Kind regards,

Rakhal Imming

**Comment by JanPetr** [comment]
Hello @rakibabu,

that's true. "Pages" is not translatable, but you can specify this label directly in settings:
![image](https://user-images.githubusercontent.com/1058144/27293407-9ebc6da6-5516-11e7-9580-af944e2edc46.png)

Let me know how it goes for you.
