### ISSUE TITLE
Have the possibility to not index CMS pages

### ISSUE THREAD

**Issue by VincentMarmiesse** [algolia/algoliasearch-magento-2#270]
Hello, 

Could you add an option in the configuration to not index the CMS pages? So it won't index them and won't launch the search query.

Thank you!

**Comment by nntoan** [comment]
Inside the configuration Algolia Search > Autocomplete, there is a section like this do exactly what you want.
![screenshot 2017-06-23 10 06 09](https://user-images.githubusercontent.com/3891429/27465137-bb81a6e4-57fb-11e7-8ef8-9988d436df0c.png)

But it would be nice if there is another options allow us to exclude **ALL** cms pages.

**Comment by JanPetr** [comment]
Hello @VincentMarmiesse and @nntoan,

you can remove Pages from Additional Sections:
<img width="897" alt="screenshot 2017-06-23 09 27 44" src="https://user-images.githubusercontent.com/1058144/27470962-5d418be4-57f6-11e7-8a8c-666d37bb04b0.png">

Then Pages won't be indexed at all.

**Comment by VincentMarmiesse** [comment]
Hello,
@nntoan I saw but as you said you have to specify the pages you don't want to be indexed so it's not really convenient and may cause some issues if someone creates a new page without saving it in this section.

@JanPetr my "Additional sections" section is already empty. I have deleted the index on Algolia and did a `bin/magento indexer:reindex` and the pages index has been created again.

**Comment by nntoan** [comment]
@VincentMarmiesse Exactly, that's why I'm asking for an option to exclude **ALL** cms pages and inside Additional Sections there is nothing to remove as @JanPetr said.

**Comment by JanPetr** [comment]
Hello @VincentMarmiesse and @nntoan,

that's definitely a bug, thanks for bringing it up. 
I fixed it in #271 and it will be released as part of 1.2.0 version early this week.

**Comment by VincentMarmiesse** [comment]
Hello @JanPetr,

I just checked and tested your commit but I have the same issue.

I have deleted my `pages` index and then have performed a `bin/magento indexer:reindex`. The index has been recreated and contains all my pages. I have nothing in my `Excluded Pages` section.

Regards,

**Comment by JanPetr** [comment]
Thanks for the report @VincentMarmiesse,

I'll open a new issue with that and see what I can do about it.
