### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by VincentMarmiesse** [algolia/algoliasearch-magento-2#272]
Hello,

Regularly, some image links are broken and don't display in the autocomplete anymore.

I tried to reindex, delete the Magento image cache and reindex again, still no images :(

If I save a product, its image link is corrected and is displayed correctly. How can I reindex all products images?

Thanks.

**Comment by JanPetr** [comment]
Hello @VincentMarmiesse,

here is the info how the extension indexes images: https://community.algolia.com/magento/faq/#why-are-images-not-showing-up

The best approach is to reindex your products data and don't delete image cache. Otherwise images will be broken.

**Comment by VincentMarmiesse** [comment]
@JanPetr,

Ok I'll avoid to delete the image cache. But even if I perform a full reindex, the images don't come back, how can I fix it?

Thank you.

**Comment by JanPetr** [comment]
It should, can you check that the data was really reindexed?
If you use indexing queue, there might be a delay between the reindex command and the real reindex.

**Comment by VincentMarmiesse** [comment]
@JanPetr Ok it worked! As you said I think the image cache deletion broke something. I did it again and the images showed.
Thank you 👍

**Comment by JanPetr** [comment]
I'm happy you made it work!
