### ISSUE TITLE
Product URL should follow category

### ISSUE THREAD

**Issue by dhduc** [algolia/algoliasearch-magento-2#273]
Hello there,
In instant search page, product URL always display one value, it should follow category.
Example, access to  Men > Tops > Jackets category, the product URL should be /men/tops/jackets/mars-heattech-trade-pullover.html instead of /mars-heattech-trade-pullover.html
Why is this needed? 
In the product, the breadcrumbs can't display full path follow the category when access product from the instant search page.

**Comment by JanPetr** [comment]
Hello @dhduc,

the extension indexes URLs from backend and only one URL is indexed with the extension. Currently we don't plan to modify the URL on the frontend to follow the category as it brings a lot of complexity to the frontend.
However if you want, you can modify the URL with your code by modifying the [`transformData` function of the `hits` widget](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/instantsearch.js#L235-L244).
You can do it by writing [`algoliaHookBeforeWidgetInitialization` function](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/instantsearch.js#L434-L436) and modifying the widget there.

Let me know how it goes for you.
