### ISSUE TITLE
$product->getFinalPrice() acting weird for configurable product

### ISSUE THREAD

**Issue by MagePsycho** [algolia/algoliasearch-magento-2#279]
As the title says, `$product->getFinalPrice()` is giving the price in store currency for the configurable product. But for other product types, it's giving the price in base currency.

And this causes double conversion for the configurable product.

Have you guys any workaround for this issue?

**Comment by JanPetr** [comment]
Hello @MagePsycho,

unfortunately not for now, but we're aware of the price issues.
Can I ask you what version of Magento do you use?

**Comment by MagePsycho** [comment]
@JanPetr Also keep an eye on this post: https://magento.stackexchange.com/questions/182755/bug-or-feature-regular-price-vs-final-price-in-magento2

Thanks
