### ISSUE TITLE
Fatal error: Class 'Magento\Framework\Search\Document' not found

### ISSUE THREAD

**Issue by IlyaGluschenko** [algolia/algoliasearch-magento-2#28]
magento 2.1 on catalog search result page with "Enable Instant Search Results Page" = no
Fatal error: Class 'Magento\Framework\Search\Document' not found in \vendor\algolia\algoliasearch-magento-2\Adapter\Algolia.php on line 134

**Comment by JanPetr** [comment]
Thanks for the report @IlyaGluschenko, I created a PR. Feel free to test it.

**Comment by JanPetr** [comment]
Fixed in 0.8.2
