### ISSUE TITLE
[Question] Number of hits

### ISSUE THREAD

**Issue by danielozano** [algolia/algoliasearch-magento-2#284]
Hi!

We've noticed that only 1000 products are available as result of the search. Taking a look at the code we found it:

```php
    public function getSearchResult($query, $storeId)
    {
        $resultsLimit = $this->configHelper->getResultsLimit($storeId);

        $index_name = $this->productHelper->getIndexName($storeId);

        $number_of_results = 1000;

        if ($this->configHelper->isInstantEnabled()) {
            $number_of_results = min($this->configHelper->getNumberOfProductResults($storeId), 1000);
        }

        $answer = $this->algoliaHelper->query($index_name, $query, [
            'hitsPerPage'            => $number_of_results, // retrieve all the hits (hard limit is 1000)
            'attributesToRetrieve'   => 'objectID',
            'attributesToHighlight'  => '',
            'attributesToSnippet'    => '',
            'numericFilters'         => 'visibility_search=1',
            'removeWordsIfNoResults' => $this->configHelper->getRemoveWordsIfNoResult($storeId),
            'analyticsTags'          => 'backend-search',
        ]);

        $data = [];

        foreach ($answer['hits'] as $i => $hit) {
            $productId = $hit['objectID'];

            if ($productId) {
                $data[$productId] = [
                    'entity_id' => $productId,
                    'score'     => $resultsLimit - $i,
                ];
            }
        }

        return $data;
    }
```

There is any reason for that? We can't get more than 1000 hits as result from algolia?

Another thing is that the method [getResultLimit()](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/ConfigHelper.php#L330) is not usable, because you can't configure it, the limit option (algoliasearch_products/products/results_limit) is not defined on system.xml. Is this a deprecated method, or it's going to be functional on the future?

Thanks for the help.

**Comment by JanPetr** [comment]
Hello @danielozano,

that's correct - Algolia will return maximum number of 1000 results per a search operation. You can find more operation about that in documentation: https://www.algolia.com/doc/api-client/php/search/#search-an-index

You're right about the getResultLimit(), this method should be removed as it's not configurable and doesn't really make sense there. I'll remove it in the next version.
