### ISSUE TITLE
Split Database Magento 2

### ISSUE THREAD

**Issue by keiant25** [algolia/algoliasearch-magento-2#287]
Hello,

I have Split Database Enabled for M2 and the Problem its that this does not work with M2 Enterprise.

Thanks,
Keilor AS

**Comment by erikhansen** [comment]
@Algolio dev - Classy Llama recently added [split database support](http://devdocs.magento.com/guides/v2.1/config-guide/multi-master/multi-master.html) to our ClassyLlama_AvaTax extension. You might find it helpful to reference the PR where we introduced that capability: https://github.com/classyllama/ClassyLlama_AvaTax/pull/59/files

**Comment by julienbourdeau** [comment]
Hi Keilor,

We'll see what we can do but we're currently not able to test on Magento EE.

**Comment by JanPetr** [comment]
Thanks for bringing it up @keiant25.

We're currently in a process of getting an EE license @erikhansen. Thank you for the reference PR, we'll definitely take some inspiration from there.

When we move forward, I'll let you know here. Thanks again!

**Comment by JanPetr** [comment]
Hello @keiant25 and @erikhansen,

we finally got access to Magento EE and I managed to fix the issue with split databases. 
It's implemented in #309.

I'd really appreciate if you'd found some time, gave it a try and shared your feedback with me.

Thanks a lot! 💯

**Comment by erikhansen** [comment]
@JanPetr - Glad you were able to get it working. None of my merchants are using split database mode, so I'll let @keiant25 test it.
