### ISSUE TITLE
Product name doesn't appear in drop-down

### ISSUE THREAD

**Issue by razvan-f** [algolia/algoliasearch-magento-2#296]
Running Algolia search on Magento 2.1.7.

The drop-down doesn't display the product name next to the thumbnail as it's supposed to do.

http://imgur.com/a/VnAlr

The Algolia extension is mostly unchanged so I am thinking it's probably one of the Magento files, any idea where to start ?

Thanks.

**Comment by moneef** [comment]
same issue here 

Magento 2.2.6
Algolia 1.12.0
