### ISSUE TITLE
Console errors: Uncaught SyntaxError: Unexpected string AND Uncaught TypeError: Cannot read property '$' of undefined

### ISSUE THREAD

**Issue by textarea** [algolia/algoliasearch-magento-2#298]
In admin panel, all pages, I have this: errors in console:

first error:
(https://user-images.githubusercontent.com/1927403/29037518-493e2608-7ba4-11e7-893a-9e7ccd96b15b.jpg)

second error:
(https://user-images.githubusercontent.com/1927403/29037529-56524bc6-7ba4-11e7-9851-5fa70b3de350.jpg)

### Preconditions

1. Magento CE 2.1.7 with sample data is installed.

**Comment by JanPetr** [comment]
Hello, did you try to redeploy static files?

**Comment by textarea** [comment]
I found the problem, console errors come when I enable "Embedded (Translation on Admin side)" value on "Stores -> Configuration -> Advanced -> Developer -> JavaScript Settings -> Translation Strategy" option
If I set "Dictionary (Translation on Storefront side)" value then errors disappear.
But it is not only an Algolia library problem, other standard Magento js files get broken
Regards

**Comment by JanPetr** [comment]
Thanks for the explanation @textarea!
