### ISSUE TITLE
Mobile Cart Icon Unable to Be Selected M2.1.8 When Algolia Indexing Active

### ISSUE THREAD

**Issue by jwgraves2** [algolia/algoliasearch-magento-2#304]
When testing Algolia in Luma on M2.1.8, enabling Algolia Index causes iPhone Safari and Chrome issue where the cart no longer is able to be clicked.

**Comment by JanPetr** [comment]
Thanks for the report @jwgraves2,
I'll investigate and come back to you.

**Comment by jwgraves2** [comment]
Eta please

**Comment by jwgraves2** [comment]
Still an issue on 2.2.1. Any updates?

**Comment by jwgraves2** [comment]
https://magento2.algolia.com/ on mobile you can actually see this. Add a product to the cart and try to checkout by clicking cart. Cart is not clickable.
