### ISSUE TITLE
Autocomplete with like (e.g. searching for pants -> displays workpants)

### ISSUE THREAD

**Issue by msbt** [algolia/algoliasearch-magento-2#305]
Hi there,
first of all, thanks for this nice extension! 

Just one issue with the autocompleter as suggested in the title: If you enter "running" in the demo, you get "apollo running short" as a result, but if you enter only part of the name, like "nning" it doesn't find anything. Is there a way to enable that? My shop has some categories with work-clothes and if you're looking for "pants", you don't get "workpants" as a result (it's not in english, but I don't have a better example ready).

Best regards

**Comment by JanPetr** [comment]
Hello @msbt,

Algolia by default works only for a [prefix searches](https://www.algolia.com/doc/guides/textual-relevance/prefix-search/) and won't match words from the middle of the word. There are ways how to work around that - https://www.algolia.com/doc/tutorials/indexing/advanced/how-can-i-make-queries-within-the-middle-of-a-word/

It'd require some coding on your side to modify the indexed records. The description on how to modify those records is here: https://discourse.algolia.com/t/how-to-make-partial-match-queries-work/2457/2

Let me know if that works for you.
