### ISSUE TITLE
Support Magento 2.2

### ISSUE THREAD

**Issue by emiliolodigiani** [algolia/algoliasearch-magento-2#318]
trying to install in magento 2.2 composer throws an error:

```
algolia/algoliasearch-magento-2 1.2.1 requires magento/framework ~100.0
```

Magento 2.2 ships with magento/framework v101

**Comment by JanPetr** [comment]
Thanks for the report Emilio! 💯 
Will do tests on 2.2 and update the composer.json. I'll let you know when it's done.

**Comment by JanPetr** [comment]
Hello Emilio, when you install the extension from `dev-master`, it should work as expected.

`composer require algolia/algoliasearch-magento-2:dev-master`

**Comment by avoelkl** [comment]
Just for completeness: I hope the 2.2 support also includes the support for PHP 7.1:

```
composer require algolia/algoliasearch-magento-2
Using version ^1.2 for algolia/algoliasearch-magento-2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - algolia/algoliasearch-magento-2 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.9) does not satisfy that requirement.
    [...]
```

**Comment by JanPetr** [comment]
Hello @avoelkl,

[PHP 7.1 is supported](https://github.com/algolia/algoliasearch-magento-2/commit/4802e189d9d3ce2f94c6b66475dbb4b074d6f717) since version 1.2.1 of the extension.

**Comment by QuentinFarizonAfrimarket** [comment]
Hello @JanPetr 
PHP 7.1 is indeed supported by algolia/algoliasearch-magento-2
But algolia/algoliasearch-magento-2 requires algolia/algoliasearch-client-php": ">=1.27.0 <2.0", that still does not support PHP 7.1 : https://github.com/algolia/algoliasearch-client-php/blob/1.x/composer.json#L22

Is that planned ?
