### ISSUE TITLE
Compatible to Magento 2.2

### ISSUE THREAD

**Issue by apmson** [algolia/algoliasearch-magento-2#320]
According to magento is released 2.2. When would you make it work with it? Because most of my plugins are already worked with the latest version. But looks like algolia one is only work with "magento/framework" 100.^. Or maybe you just check it but made it required. Because we decided to update our current site to 2.2. Currently just missing this. Thank you so much.

`algolia/algoliasearch-magento-2 1.2.0 requires magento/framework ~100.0 -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.2.0-rc20, 100.1.9, 100.0.18].`

**Comment by apmson** [comment]
Sorry, just check looks like you guys already working for it. Thanks for your hard work.

**Comment by JanPetr** [comment]
Hey @apmson,

you can install the dev-master version to have it working on Magento 2.2 :)

`$ composer require algolia/algoliasearch-magento-2:dev-master`

**Comment by apmson** [comment]
Hi @JanPetr ,

did this this morning, saw it on another post. Thank you so much.

**Comment by JanPetr** [comment]
You are welcome! Happy searching! 💯
