### ISSUE TITLE
Magento 2.2 - update version number Algoliasearch

### ISSUE THREAD

**Issue by Tantuss** [algolia/algoliasearch-magento-2#323]
Please update the version number if you change the support for Magento 2.2.

I have already the algoliasearch-magento-2 version 1.2.1, but it doesn't support Magento 2.2.
So please update the version number, to get the correct composer file, so that support for 2.2 is available.

Current solution is to remove it and re-install it.

**Comment by coresh** [comment]
### Confirmed. Can't installed. Magento version: 2.2.0.

`composer -vvv --ignore-platform-reqs require algolia/algoliasearch-magento-2`

![screenshot-20170930202512-1908x559](https://user-images.githubusercontent.com/9606476/31049191-9b9156b6-a61d-11e7-90ad-5a2e53778888.png)

**Comment by JanPetr** [comment]
Hello @Tantuss and @coresh,

the issue has been already solved. Just install the extension from `dev-master`. 
And today I'll tag a new stable version, so you'll be able to install normally. Thanks for your time and reports!
