### ISSUE TITLE
Upgrade to latest version gives error Warning: array_filter() expects parameter 1 to be array, .. ConfigHelper.php on line 477

### ISSUE THREAD

**Issue by Tantuss** [algolia/algoliasearch-magento-2#325]
When trying to save changes in the admin panel, the follow error is displayed:

Something went wrong while saving this configuration: Warning: array_filter() expects parameter 1 to be array, null given in vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php on line 477

**Comment by kytan91** [comment]
same. 
Algolia Search Products indexer process unknown error:
Warning: array_filter() expects parameter 1 to be array, null given in /home/ec2deal3/public_html/vendor/algolia/algoliasear         ch-magento-2/Helper/ConfigHelper.php on line 477

**Comment by kytan91** [comment]
please help

**Comment by Tantuss** [comment]
The reason is described here: https://github.com/algolia/algoliasearch-magento-2/issues/328
Magento changed the way they store the serialised data.

To solve this, I did do the following:
1. Make sure you create a back and preferable have also the config in another environment, because you have to remove all configuration.

2. Go in the database to the core_config_data table.
Remove everything with path like algoliasearch% 
DELETE FROM core_config_data WHERE path LIKE 'algoliasearch%';

3. Re-configure the extension in the Magento settings. If pages are empty, go to the next one. The empty pages will finally be working if you filled in everything.

But another option, if you do not want to re-configure is to take all data which is serialized in the database and make it json data.
You can find the data quiet easy like this:
SELECT value FROM core_config_data WHERE path LIKE 'algoliasearch%' AND value LIKE 'a:%';

You can put then the data for example in this website to make it from serialized into json: http://www.unserialize.me/

**Comment by JanPetr** [comment]
Hello, the `serialize` issue was solved in #339, feel free to update to `master` branch.

`$ composer require algolia/algoliasearch-magento-2:dev-master`
