### ISSUE TITLE
Release 1.3.0 available or not? 

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#326]
Hi! Look as All is ready for support Magento 2.2 in version 1.3.0, but It`s not available or not tagged commit in composer? Please clarify that or fix release

**Comment by julienbourdeau** [comment]
Hi, 
1.3.0 is almost ready and should be tagged very soon. In the meantime, you can use it by forcing composer to use the master branch.

**Comment by JanPetr** [comment]
Hello @vmalyk, the 1.3.0 version has been released last week. Let me know your thoughts :100:
