### ISSUE TITLE
Magento 2: Algolia issues

### ISSUE THREAD

**Issue by vijaymagento1** [algolia/algoliasearch-magento-2#327]
Hello Algolia support team,
We are getting the following issues in algloia module. Please have a look.
We are using latest version magento 2.2. Please review and let us know the solutions of it.

Issues:- 

**Fatal error: Uncaught Error: Class 'AlgoliaSearch\Client' not found in /home/public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php:47 Stack trace: #0 /home/public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php(32): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->resetCredentialsFromConfig() #1 /home/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->__construct(Object(Magento\Framework\App\Helper\Context), Object(Algolia\AlgoliaSearch\Helper\ConfigHelper), Object(Magento\Framework\Message\Manager)) #2 /home/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Algolia\\Algolia...', Array) #3 /home/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Algolia\\Algolia...') #4 /home/p in /home/public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php on line 47**

Thanks!

**Comment by vijaymagento1** [comment]
We have installed the modules inside this directory.
**app/code/Algolia/AlgoliaSearch**

When i was trying to install the algolia module through the composer it's giving the following issues.

Issuses:- 

[~/public_html]# composer require algolia/algoliasearch-magento-2

Using version ^1.2 for algolia/algoliasearch-magento-2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install algolia/algoliasearch-magento-2 1.2.1
    - Conclusion: don't install algolia/algoliasearch-magento-2 1.2.1
    - Conclusion: don't install algolia/algoliasearch-magento-2 1.2.0|remove magento/framework 101.0.0
    - Conclusion: don't install algolia/algoliasearch-magento-2 1.2.0|don't install magento/framework 101.0.0
    - Installation request for algolia/algoliasearch-magento-2 ^1.2 -> satisfiable by algolia/algoliasearch-magento-2[1.2.0, 1.2.1].
    - algolia/algoliasearch-magento-2 1.2.0 requires magento/framework ~100.0 -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18].
    - Can only install one of: magento/framework[101.0.0, 100.0.2].
    - Can only install one of: magento/framework[101.0.0, 100.0.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.6].
    - Can only install one of: magento/framework[101.0.0, 100.0.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.8].
    - Can only install one of: magento/framework[101.0.0, 100.0.9].
    - Can only install one of: magento/framework[101.0.0, 100.1.0].
    - Can only install one of: magento/framework[101.0.0, 100.0.10].
    - Can only install one of: magento/framework[101.0.0, 100.0.11].
    - Can only install one of: magento/framework[101.0.0, 100.1.1].
    - Can only install one of: magento/framework[101.0.0, 100.0.12].
    - Can only install one of: magento/framework[101.0.0, 100.1.2].
    - Can only install one of: magento/framework[101.0.0, 100.1.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.13].
    - Can only install one of: magento/framework[101.0.0, 100.1.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.14].
    - Can only install one of: magento/framework[101.0.0, 100.1.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.15].
    - Can only install one of: magento/framework[101.0.0, 100.1.6].
    - Can only install one of: magento/framework[101.0.0, 100.1.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.16].
    - Can only install one of: magento/framework[101.0.0, 100.0.17].
    - Can only install one of: magento/framework[101.0.0, 100.1.8].
    - Can only install one of: magento/framework[101.0.0, 100.1.9].
    - Can only install one of: magento/framework[101.0.0, 100.0.18].
    - Installation request for magento/framework (locked at 101.0.0) -> satisfiable by magento/framework[101.0.0].


Installation failed, reverting ./composer.json to its original content.


Thanks

**Comment by syedsaleem086** [comment]
Hello Algolia,

I also facing the same issue. Please let us know when this can be resolved.

**Comment by JanPetr** [comment]
Hello @vijaymagento1 and @syedsaleem086,
can you install via Composer and require `master` branch? Command:

`$ composer require algolia/algoliasearch-magento-2:dev-master`

Master is Magento 2.2 ready 👍
