### ISSUE TITLE
Magento 2.2 Fatal error: Uncaught Error: Class 'AlgoliaSearch\Client' not found in AlgoliaHelper.php on line 47

### ISSUE THREAD

**Issue by vijaymagento1** [algolia/algoliasearch-magento-2#332]
Fatal error: Uncaught Error: Class 'AlgoliaSearch\Client' not found in /home/public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php:47 Stack trace: #0 /home/public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php(32): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->resetCredentialsFromConfig() #1 /home/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->__construct(Object(Magento\Framework\App\Helper\Context), Object(Algolia\AlgoliaSearch\Helper\ConfigHelper), Object(Magento\Framework\Message\Manager)) #2 /home/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Algolia\\Algolia...', Array) #3 /home/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Algolia\\Algolia...') #4 /home/p in /home/public_html/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php on line 47

**Comment by JanPetr** [comment]
Hello @vijaymagento1, did you install the extension via Composer or via Magento's plugin manager? If not, can you do it? It'll install all the required dependencies.

Let me know how it goes.

**Comment by praveen-chelumalla** [comment]
Same Error : 

I am installed manually 

Fatal error: Uncaught Error: Class 'AlgoliaSearch\Version' not found in /var/www/stpl_store/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php:49 Stack trace: #0 /var/www/stpl_store/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->__construct(Object(Magento\Framework\App\Helper\Context), Object(Algolia\AlgoliaSearch\Helper\ConfigHelper), Object(Magento\Framework\Message\Manager), Object(Symfony\Component\Console\Output\ConsoleOutput)) #1 /var/www/stpl_store/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Algolia\\Algolia...', Array) #2 /var/www/stpl_store/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Algolia\\Algolia...') #3 /var/www/stpl_store/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Algolia in /var/www/stpl_store/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php on line 49

**Comment by JanPetr** [comment]
Hello @praveen-chelumalla,

can you install with Composer? Thanks!

**Comment by njenga55** [comment]
Issue is due to the default scout search driver, change the driver in scout config  from algolia to tntsearch driver
