### ISSUE TITLE
Better to have browse() method in Algolia\AlgoliaSearch\Helper\AlgoliaHelper

### ISSUE THREAD

**Issue by MagePsycho** [algolia/algoliasearch-magento-2#337]
Having `query()` is good. But it would be better if we add `browse()` method which will help to fetch all the records (without limitation).
For example:
```
// Class: Algolia\AlgoliaSearch\Helper\AlgoliaHelper
public function browse($indexName, $query, $params)
{
    $this->checkClient(__FUNCTION__);
    return $this->client->initIndex($indexName)->browse($query, $params);
}
```

**Comment by JanPetr** [comment]
Hello @MagePsycho, 

you can do the same by calling `$algoliaHelper->getIndex($indexName)->browse(...);` in your code. Would that work for you?
