### ISSUE TITLE
Not compatible with Aheadworks ShopbyBrand

### ISSUE THREAD

**Issue by SilvanLaroo** [algolia/algoliasearch-magento-2#342]
Hi,

We're using Aheadworks ShopbyBrand for a while now. Since this week we've switched to Algolia Search with the Magento 2 integration. If we enable the Algolia Search extension, the brand page shows all products instead of just the product for that specific brand. Without the Algolia extension enabled the brandpage just shows the products for that specific brand. 

Is this a known issue? Is there a solution to this problem?

Regards,
Silvan

**Comment by SilvanLaroo** [comment]
We've found this code in the ShopbyBrand extension that is responsible for filtering the collection on Brand:
`    /**
     * Add brand attribute filter to product collection
     *
     * @param Collection $collection
     * @return void
     */
    private function addBrandAttributeFilter($collection)
    {
        $brandId = $this->request->getParam('brand_id');
        $brand = $this->brandRepository->get($brandId);
        $collection->addFieldToFilter(
            $brand->getAttributeCode(),
            ['eq' => $brand->getOptionId()]
        );
    }`

This works when Algolia is disabled, but as soon as we enable it all products are shown.

**Comment by SilvanLaroo** [comment]
We've found that this pull-request fixes our issue: https://github.com/algolia/algoliasearch-magento-2/pull/301. I see that this is labeled 'Do not merge', why should this pull request not be merged? Is there another option to fix this?

**Comment by JanPetr** [comment]
Hello Silvain,

this PR is labeled 'Do not merge' because it needs some polishing. But feel free to apply it to your code. In upcoming versions it'll be integrated directly to the extension.
Is that OK for you?

**Comment by JanPetr** [comment]
Hello @SilvanLaroo,

the PR was re-done and is released yet. I'm closing the issue. Thanks for bringing it up!
