### ISSUE TITLE
Loading "Instant Search Results Page" Config replaces "Facets" labels with "Sorts" labels

### ISSUE THREAD

**Issue by Sanfam** [algolia/algoliasearch-magento-2#343]
When loading the the "Instant Search Results" results config page for Algolia 1.3.0 on Magento 2.1.7, the values for "Sorts" overwrite the values for "Facets."  Re-saving this page overwrites the correct values with the incorrect labels pulled from the neighboring form.

Opened, values entered and ready to save:
![image](https://user-images.githubusercontent.com/3504427/32281897-84fdabd8-bef6-11e7-986c-aba00d2fd5e3.png)

Correct values on site after save:
![image](https://user-images.githubusercontent.com/3504427/32282021-dd9bb794-bef6-11e7-9967-246c45b7a9f0.png)

Admin form reloaded after save completes:
![image](https://user-images.githubusercontent.com/3504427/32281922-96a88d08-bef6-11e7-9ac0-ac9efd2ad77d.png)

If the admin re-saves this form as pictured, the site displays the following incorrect results:
![image](https://user-images.githubusercontent.com/3504427/32282476-06f73586-bef8-11e7-93c2-6b2e72b366f0.png)

**Comment by JanPetr** [comment]
Hello @Sanfam,

thanks for the report! 💯 
I manage to reproduce, will push fix soon.

**Comment by Sanfam** [comment]
@JanPetr Excellent.  Glad to be of help!
