### ISSUE TITLE
Grouped products show R0 ($0) on instant search pages and autocomplete

### ISSUE THREAD

**Issue by seagyn** [algolia/algoliasearch-magento-2#344]
When we have a grouped product, all with prices, the instant search page (incl category pages) and autocomplete show a zero price for the product. Usual  behaviour is either From $x or $x - $y.

**Comment by JanPetr** [comment]
Hello @seagyn, what version of the extension do you use? Do you have customer groups enabled?

**Comment by seagyn** [comment]
Hi @JanPetr 

I'm wondering when we change over to the new templates if this will fix this (re: #345).

I do have groups enabled.

**Comment by JanPetr** [comment]
No, it won't as the price wasn't indexed correctly. Now it should be ok with fix in #377
