### ISSUE TITLE
Ability to have "heart" and "compare" on instant search pages

### ISSUE THREAD

**Issue by seagyn** [algolia/algoliasearch-magento-2#345]
It would be helpful to be able to modify the grid views on instant search pages so that we can have them look similar to the themes category pages and the themes default grid view.

**Comment by JanPetr** [comment]
Hello @seagyn,

you can customize IS page - you can override templates and add your own JS. Here's documentation: https://community.algolia.com/magento/doc/m2/customize-instantsearch/
Let me know if something isn't clear.
