### ISSUE TITLE
indexing category not working

### ISSUE THREAD

**Issue by michael-tourneur** [algolia/algoliasearch-magento-2#346]
Hello,

I'm using magento 2.1.9, algolia plugin 1.1 and it seems category is not indexing
those are my categories defined on cms
![screencapture-dev-plukka-admin_94wskv-catalog-category-edit-id-45-key-4df24c177f4c5b1a4cc694795102b5038707a8a738d6695fc037987921a03edd-1509640567460](https://user-images.githubusercontent.com/2604749/32348922-b7d4d016-c015-11e7-9f3c-fff158534d20.png)

and this is my algolia instance for category index
![screencapture-algolia-apps-b4z2cv125q-explorer-browse-magento2_default_categories-1509640733065](https://user-images.githubusercontent.com/2604749/32349030-09da3cfc-c016-11e7-80b1-24a476a5b1d1.png)

**Comment by JanPetr** [comment]
Hello @michael-tourneur,

the extension doesn't index empty categories, so it's expected that your `testCat` is not indexed.
Did you run full category reindex to index all categories? You can do it by running:

`$ php bin/magento indexer:reindex algolia_categories`

**Comment by JanPetr** [comment]
Hello @michael-tourneur,

can you apply the fix from #366 and give it a try?
