### ISSUE TITLE
Condition wrong

### ISSUE THREAD

**Issue by VictorSnow** [algolia/algoliasearch-magento-2#347]
https://github.com/algolia/algoliasearch-magento-2/blob/a6a30acc7960d73759ee0e9b9699e76316e1b17b/Model/Indexer/Product.php#L78

wrong configuration with filter visible product

**Comment by JanPetr** [comment]
@VictorSnow, could you elaborate a bit more on that? What is wrong with the condition? What is the issue you experience?

**Comment by VictorSnow** [comment]
will go wrong when queue is not enabled,  `getProductCollectionQuery` use third param to filter visible product

**Comment by JanPetr** [comment]
That's correct. When the queue is not enabled, the extension fetches all products as it deletes disabled / not-visible products from Algolia. So they need to be fetched.

When queue is enabled, the indexing is done to temporary index where only enabled / visible products are indexed - no need for delete.
