### ISSUE TITLE
Produkt URL containing SID

### ISSUE THREAD

**Issue by avoelkl** [algolia/algoliasearch-magento-2#348]
I just checked the product data in the Algolia Dashboard and found out, that the product URL contains the Session ID (SID) in the product url:

![algolia-sid](https://user-images.githubusercontent.com/1798594/32690019-6bdd8fe6-c6ef-11e7-8aea-24ab8180be8c.png)

The setting in Store > Configuration > General > Web > Session Validation Settings > Use SID on Storefront is currently enabled. This setting "Allows customers to stay logged in when switching between different stores." but this should have nothing to do with the indexed product URL.
Regardless of this setting a session id should never be indexed by Algolia along with the product url.

**Comment by JanPetr** [comment]
Hello @avoelkl,

I just pushed fix to #361. Could you give it a try? Thanks!

**Comment by avoelkl** [comment]
Yes I can confirm the SID is not indexed any more. Thanks!
