### ISSUE TITLE
Search box disappears on Porto theme (Magento 2.2.0)

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento-2#350]

**Comment by sabba987** [comment]
In your porto or magento custom css add:

input#search {
    left: 0px;
}

**Comment by VictorSnow** [comment]
i am using porto theme and algoliasearch. 
it occurs  in magento 2.2.0, 
need to use alia name
`<?php echo $this->getChildHtml("topSearch"); ?>`

**Comment by JanPetr** [comment]
Thank you @sabba987!

@VictorSnow Where did you put this code?

**Comment by VictorSnow** [comment]
Actually i modified the theme template file ` Smartwave_Porto::html/header.phtml`

**Comment by coresh** [comment]
Required:

1: appending to styles (as described @sabba987 ):

input#search {
left: 0px;
}

2:
Navigate to System > Configuration > Algolia Search > Advanced tab and change Search input DOM Selector field to .input-text or #search

src:
https://themeforest.net/item/porto-ultimate-responsive-magento-theme/9725864/comments?utf8=%E2%9C%93&term=algolia&from_buyers_and_authors_only=0#

**Comment by ngz82** [comment]
Thanks, these CSS and config changes make it work on desktop however on mobile the search box is always displayed, instead of activated by the search icon in the mini header.
Anyone have a workaround or fix to make it operate correctly as per the Porto theme mobile UX?

**Comment by erik921** [comment]
Currently running porto 3.0.1 and Mangento 2.2.2
With the above fixes only the search bar disappears or algolia is permanently open.

**Comment by damcou** [comment]
Compatibility with Porto theme has been added to the features list in our roadmap.

**Comment by adarshkhatri** [comment]
Looks it is still not added. Same issue with Magento 2.3.3
