### ISSUE TITLE
Issue with paths send to algolia from Magento 2

### ISSUE THREAD

**Issue by FabienBedotM6Web** [algolia/algoliasearch-magento-2#353]
Hi,

We have a problem with Algolia plugin running on Magento 2.1.2.
We use Algolia to override Magento default CMS to create ProductList pages (you can see an exemple here : http://www.deco.fr/shopping-deco/canape/ - that page is powered by Algolia)

When we started to create some new pages on our site, we saw that the path send to Algolia does not comply with the rightful path expected.

exemple for the Magento Category ID 6940

{
  "requests": [
    {
      "action": "addObject",
      "body": {
        "objectID": 6940,
       "name": "Idées cadeaux de Noël",
        "path": "**E-Shop / Nos Sélections / Tapis**",
        "level": 4,
        "url": "https://www.deco.fr/shopping-deco/selection-idee-noel-cadeau-2017/",
        "include_in_menu": null,
        "_tags": [
          "category"
        ],
        "popularity": 1,
        "product_count": 2,
        "algoliaLastUpdateAtCET": "2017-11-13 17:06:02"
      },
      "objectID": "6940"
    }
  ]
}

In this line, "path": "**E-Shop / Nos Sélections / Tapis**", "Tapis" is not OK at all.
=> The right path in Magento is (and should be) e-Shop / Nos Sélections / Idées cadeaux de Noël". We do not even understand how this path is generated and why it is wrong.

Do you have any ideas ?
Thank you.

**Comment by JanPetr** [comment]
Thank you for the report @FabienBedotM6Web 💯  I'll investigate and come back to you.

**Comment by JanPetr** [comment]
Hello @FabienBedotM6Web, I pushed a fix in #366. Can you give it a try?

**Comment by FabienBedotM6Web** [comment]
Hi Jan,

Thank you for the fix but we are not in condition to try it.
We will send it to the agency who works on our Magento projet.
Best regards,

**Comment by JanPetr** [comment]
OK @FabienBedotM6Web,

I'm closing the issue now. If you realize it still doesn't work, feel free to re-open.
