### ISSUE TITLE
Can't show placeholder image on dropdown search

### ISSUE THREAD

**Issue by dungnv** [algolia/algoliasearch-magento-2#355]
Hi Algolia,

How we show placeholder image on dropdown search ?

Thanks.

**Comment by JanPetr** [comment]
Hello @dungnv,

there is a [Magento issue](https://github.com/algolia/algoliasearch-magento-2/issues/37) which prevents the extension from fetching the right placeholder URL. So as for now, there is no easy way how to fix it. Sorry.
