### ISSUE TITLE
Placeholder is not showing in Search Box

### ISSUE THREAD

**Issue by alphatests** [algolia/algoliasearch-magento-2#356]
Hey,

I added module in Magento 2.1.9

When i search product which does not have image and it is not showing placeholder 

IN console showing this error
Failed to load resource: the server responded with a status of 404 (Not Found) 
file path is like this
pub/static/version1510896959/adminhtml/_view/en_US/Magento_Catalog/images/product/placeholder/.jpg 

How can i get proper placeholder image?

**Comment by JanPetr** [comment]
Hello @alphatests,

there is a [Magento issue](https://github.com/algolia/algoliasearch-magento-2/issues/37) which prevents the extension from fetching the right placeholder URL. So as for now, there is no easy way how to fix it. Sorry.
