### ISSUE TITLE
Active state body class

### ISSUE THREAD

**Issue by thijsvandberg** [algolia/algoliasearch-magento-2#358]
Please add an active state body class, this allows us to add a full page overlay when search is active.

**Comment by JanPetr** [comment]
Hello @thijsvandberg,

I'm not sure I got what you mean. Do you talk about CSS class for `body` tag?
Can you elaborate a bit more and send a screenshot maybe?

Thanks!

**Comment by thijsvandberg** [comment]
Exactly, a body css class. For instance: body.searchautocomplete__active

![image](https://user-images.githubusercontent.com/681323/32941243-690280c0-cb85-11e7-95cc-909e4ce80390.png)

As you can see we added an overlay to let the user focus on the search. We want to accomplish the same effect on https://www.bodyengymshop.nl.

**Comment by JanPetr** [comment]
Hello @thijsvandberg,

this is something what I don't want to bring directly to the extension as it's only used in specific use cases. But you can do it on your own in your custom JS file.

Here's how it can look like:

```js
$(algoliaConfig.autocomplete.selector).each(function () {
	$(this)
	.on('autocomplete:shown', function() {
		$('body').addClass('your-active-class');
	})
	.on('autocomplete:closed', function() {
		$('body').removeClass('your-active-class');
	});
});
```

Would that work for you?

**Comment by thijsvandberg** [comment]
Hi @JanPetr 

This would be a good solution, but I can not get it to work. I am using the latest version.

**Comment by thijsvandberg** [comment]
Hi @JanPetr 

Could you check if the code you provided is working for you?

Thanks!
