### ISSUE TITLE
Search Box and page Showing not exist products

### ISSUE THREAD

**Issue by alphatests** [algolia/algoliasearch-magento-2#364]
Algolia Search box and Search page showing non exist products.

I try to reindex so many time but that products are showing

How to solve this?

**Comment by JanPetr** [comment]
Hello @alphatests,

can you enable [indexing queue](https://community.algolia.com/magento/doc/m2/indexing-queue/) and reindex your catalog with the queue?

**Comment by alphatests** [comment]
Yes that works
