### ISSUE TITLE
Filter removes when click on minicart delete button

### ISSUE THREAD

**Issue by alphatests** [algolia/algoliasearch-magento-2#369]
From home page Search any product

Add any product to cart and on search page filter products and now click on minicart remove item button and see it removes filters from search page also 

Any solution?

**Comment by JanPetr** [comment]
Hello @alphatests,

I'm not sure I got what you mean. Could you maybe record a screencast to show what's happening?

**Comment by alphatests** [comment]
check this https://www.screencast.com/t/SMkhh05T0Y

**Comment by JanPetr** [comment]
Hello @alphatests,

I checked that and there is an issue directly in Magento. When clicking on the card button, the URL gets changed and as InstantSearch page relies on URL as well, it removes all filters.
Unfortunately there is nothing we can do unless Magento fixes the issue.
