### ISSUE TITLE
Add to cart ajax is not working on search page

### ISSUE THREAD

**Issue by Nehace40** [algolia/algoliasearch-magento-2#370]
On alogila search page first time product will add in cart using ajax after i change to next page or change filter text it will not work with ajax

I try to find final render function where all html replace but not get proper function 

can you tell from which  function render all html or give me solution of work ajax add to cart on other page

**Comment by JanPetr** [comment]
Hello @Nehace40,

I'm not able to reproduce it. Do you use any 3rd party extension to add products to cart with Ajax?

**Comment by Nehace40** [comment]
No, I am not using 3rd party extension

**Comment by JanPetr** [comment]
And did you do any modification in Magento to make it work with Ajax?

**Comment by jgahn-xom** [comment]
I am having this same issue. Async addtocart works on the initial search results (sometimes) but after changing the instant search query with new results the submit event is not bound for new buttons from fresh results. I don't see anywhere in the code that would bind the submit event to new instant search results and it doesn't bind for replaced category pages at all. Is Async addtocart an actual feature of the algolia-magento extension?

**Comment by jgahn-xom** [comment]
I had to add this code to the end of templates/instant/wrapper.phtml:
`<script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "{{sku}}"
            }
        }
    }
</script>`
