### ISSUE TITLE
Issue with requireJS in administration

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento-2#372]
We have upgraded to Magento 2.2.1 CE along with the AlgoliaSearch to 1.4.0.

We have recompiled code and flushed caches several times, but we still 
expirience an issue with AlgoliaSearch in admin panel:

```
require.js:1895 GET 
http://XYZ.com/pub/static/adminhtml/Magento/backend/en_US/algoliaAdminBundle.js 
net::ERR_ABORTED
req.load @ require.js:1895
require.load @ static.js:273
load @ require.js:1639
load @ require.js:820
fetch @ require.js:810
check @ require.js:840
enable @ require.js:1143
enable @ require.js:1511
(anonymous) @ require.js:1128
(anonymous) @ require.js:132
each @ require.js:57
enable @ require.js:1090
init @ require.js:774
(anonymous) @ require.js:1416
setTimeout (async)
(anonymous) @ require.js:1755
localRequire @ require.js:1405
window.require @ mixins.js:239
(anonymous) @ (index):361
require.js:166 Uncaught Error: Script error for: algoliaAdminBundle
http://requirejs.org/docs/errors.html#scripterror
at makeError (require.js:166)
at HTMLScriptElement.onScriptError (require.js:1681)
makeError @ require.js:166
onScriptError @ require.js:1681
```

The issue is similar to this one: https://github.com/algolia/algoliasearch-magento-2/commit/a9225cf1749f609538ae9a7b76dec1938e087280

**Comment by genyuk** [comment]
We have tried to recompile the code with "bundle java scripts" turned off, did not help

**Comment by JanPetr** [comment]
Hello @genyuk, I just tested it.
I tried to compile on 2.2.1 CE, in production mode, with all settings enabled and everything works on my side :/ 

Can you send me exact steps how you are able to reproduce? Ideally on a pure Magento installation. Thank you!
