### ISSUE TITLE
Wrong total records for search results filtered by category

### ISSUE THREAD

**Issue by voleye** [algolia/algoliasearch-magento-2#376]
When I search products and then try to filter them by category I have only 4 products on search results page but pagination still shows pages (that of course does not works, because there are only 4 products - nothing to paginate)

I think it is because algolia/algoliasearch-magento-2/Helper/Data.php method `getSearchResult` does not send any information about categories

Seems should be something like:
`.... "facetFilters" => "[[\"categories.level0:name of category here\"]]",....`

Is this a bug or by design? How can we fix the issue with pages?

**Comment by JanPetr** [comment]
Hello @voleye,

do you use it on instant search page power by Algolia or on a backend rendered page?
Could you share a website with me where I could investigate the issue?

**Comment by voleye** [comment]
Hi @JanPetr 

Thank you for answer. I do believe it is on a backend rendered page, I visited the method described above using xdebug and can see the count of hits = 134 in the same time when the products in this category only 4.  I am not sure about sharing the link here, I will think a little bit about how can I share detailed info. Thanks a lot

**Comment by JanPetr** [comment]
Hello @voleye,

I just tried on Magento 2.2.0 and I'm not able reproduce.

Initial search:
<img width="1074" alt="screenshot 2017-12-12 16 20 30" src="https://user-images.githubusercontent.com/1058144/33892230-8ca9928e-df58-11e7-9ca1-88784e5b29ad.png">

Refined by category - pagination done:
<img width="1284" alt="screenshot 2017-12-12 16 20 51" src="https://user-images.githubusercontent.com/1058144/33892250-9b42fb82-df58-11e7-87ff-a50d0f15f722.png">

Any chance you're running older version of Magento where is a bug?

**Comment by voleye** [comment]
@JanPetr Yes, you are right, it was fixed in in this commit
https://github.com/magento/magento2/commit/f8c75a8188274b74c00a936e6882a1c6a3168ea8#diff-9085bf7a3224a9027b610a30d8e541da

Sorry, I will close the issue!
Thank you for quick answer, you are awesome!

**Comment by JanPetr** [comment]
I'm happy you managed to find a solution :)
Happy searching! 💯
