### ISSUE TITLE
Implement Infinite Scroll Pagination Alternative

### ISSUE THREAD

**Issue by webcrew-au** [algolia/algoliasearch-magento-2#404]
Implement the infinite scroll search results lazy loading functionality as a configuration option instead of the default next / prev pagination similar to that described here: https://www.algolia.com/doc/tutorials/search-ui/instant-search/infinite-scroll/instantsearchjs/

**Comment by JanPetr** [comment]
Hello @webcrew-au,

thanks for the issue. It's on a roadmap, it's coming! :)
But I cannot promise you any ETA now.

**Comment by damcou** [comment]
Added to the features list in our roadmap.
