### ISSUE TITLE
Category Filter not showing newly added categories

### ISSUE THREAD

**Issue by carlzata** [algolia/algoliasearch-magento-2#407]
Hi guys we're trying to implement this plugin. One issue we are having at the moment is the category filter in the instant result page, We have added new sub categories under our main categories, I have cleared cache, reindexed algolia indexes but we cant seem to make it appear on the filter. We also notice some categories appearing which has "///" in the label but clicking it will not return products.
![screen shot 2018-01-24 at 1 42 34 pm](https://user-images.githubusercontent.com/2543359/35316431-79d93a30-010c-11e8-8a32-8622dff66336.png)

![screen shot 2018-01-24 at 1 43 31 pm](https://user-images.githubusercontent.com/2543359/35316451-99777ca8-010c-11e8-9994-f1cfeed1972e.png)

**Comment by JanPetr** [comment]
Hello @carlzata,

what version of the extension do you use?

**Comment by JanPetr** [comment]
Hello @carlzata,
could you upgrade the extension to it's latest version and reindex data? It should fix the issue.
