### ISSUE TITLE
price filter is not working for  US store

### ISSUE THREAD

**Issue by balwant20** [algolia/algoliasearch-magento-2#412]
i have using mutiple store on my site. and i am using your algolia search extension v1.4.0  & magento 2.1.7.
whenever i search any products in my US store and apply price filter i get no results everytime.but the same thing i do in other store like Aus, Brazil, france etc then i got appropriate results.
so i didn't get what is the problem behind this?why price filter is not working for US Store?
can anyone figure out the soln?
thanks in advance....!!!!!!!!!

**Comment by JanPetr** [comment]
Hello @balwant20,

could you share with me URL of your US and one other store? Thank you!

**Comment by JanPetr** [comment]
Hello @balwant20,

I checked your store and the price filter works as expected on US store.
Did you manage to fix it?

Re-open the issue please if you still experience troubles with. Thanks!
