### ISSUE TITLE
No setting for facet sorting?

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#416]
Hi,

I'd like to sort my facet values on alpha instead of count (https://www.algolia.com/doc/api-reference/api-parameters/sortFacetValuesBy/). But I can't find where I should do this?

**Comment by JanPetr** [comment]
Hello @peterjaap,

it's not possible with the configuration. You will have to override [filter widgets' configuration](https://community.algolia.com/instantsearch.js/v1/documentation/#refinementlist) in frontend [method `algoliaHookBeforeWidgetInitialization`](https://community.algolia.com/magento/doc/m2/frontend-events/#instant-search-page-events). There you can override the sorting of widgets.

**Comment by peterjaap** [comment]
@JanPetr great, thanks!

**Comment by peterjaap** [comment]
I got it working by taking the [Algolia Magento 2 customization example module](https://github.com/algolia/algoliasearch-custom-algolia-magento-2) and uncommenting/adding this function in `hooks.js`;

```
function algoliaHookBeforeInstantsearchInit(instantsearchOptions) {
    var storeCode = false;

    if (window.location.hostname === 'www.domainone.com') {
        storeCode = 'domainone';
    }

    if (window.location.hostname === 'www.domaintwo.com') {
        storeCode = 'domaintwo';
    }

    if (storeCode) {
        instantsearchOptions.indexName = 'magento2_' + storeCode + '_products_price_default_asc';
    }

    return instantsearchOptions;
}
```

That index of course needs to be actually present in Algolia, otherwise an error will occur and your products won't show.

**Comment by peterjaap** [comment]
Actually, the above sets a default sorting for the hits in the instant search. It does not sort the filter options on alpha. To do that, you need to set the "Products' indices extra settings" under "Advanced - Extra Algolia indices settings" to `{"sortFacetValuesBy": "alpha"}`.

**Comment by ms-navarra** [comment]
@peterjaap did you had to do anything else to have it working? does Algolia need to be reindex or anything.. coz I used taht setting but it stil doesnt sort the facet values ..

**Comment by peterjaap** [comment]
@ms-navarra you're right, that didn't work. However, I have found how it *does* work. It's just not configurable by default and you have to override a JS file from the extension.

In `vendor/algolia/algoliasearch-magento-2/view/frontend/web/instantsearch.js`, in the function `addSearchForFacetValues` (last function in the file), add `sortFacetValuesBy: 'alpha'` to the `options['searchForFacetValues']` array, so the whole function becomes this;

```
	function addSearchForFacetValues(facet, options) {
		if (facet.searchable === '1') {
			options['searchForFacetValues'] = {
				placeholder: algoliaConfig.translations.searchForFacetValuesPlaceholder,
				templates: {
					noResults: '<div class="sffv-no-results">' + algoliaConfig.translations.noResults + '</div>'
				},
                sortFacetValuesBy: 'alpha'
			};
		}
		
		return options;
	}
```

Now your facet will be sorted alphabetically.

**Comment by peterjaap** [comment]
@ms-navarra that didn't work either. But this *does* work (no, really);

```
function algoliaHookBeforeWidgetInitialization(allWidgetConfiguration) {
    jQuery.each(allWidgetConfiguration['refinementList'], function (index, item) {
       item.sortBy = ['name:asc'];
    });
}
```
