### ISSUE TITLE
Admin bundle JS file does not exist

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#417]
The Magento backend tries to load this file;

`static/adminhtml/Magento/backend/en_US/algoliaAdminBundle.js`

But that file does not exist, not even in the extension. We manually fix this now by running;

`cp ./static/adminhtml/Magento/backend/en_US/Algolia_AlgoliaSearch/algoliaAdminBundle.min.js static/adminhtml/Magento/backend/en_US/algoliaAdminBundle.js`

But we need to do this after *every* deployment. This shouldn't be the case.

**Comment by JanPetr** [comment]
Hello @peterjaap,

what version and edition of Magento do you use? Thanks! :)

**Comment by peterjaap** [comment]
`2.2.2`
