### ISSUE TITLE
Not working with custom theme.

### ISSUE THREAD

**Issue by kauansoft** [algolia/algoliasearch-magento-2#422]
Magento 2.2.2
[Bege Magento Theme](https://themeforest.net/item/bege-responsive-magento-theme/21316707)

The module is not working for me, even configuring in admin panel (api key, etc). Its like theme configuration is override algoliasearch (as autocomplete). In DOM selector i put # search_mini_form and search box has appear again, however any word i try search return this: "search results for: 'undefined', so in DOM Selector (new try) im using #search_mini_form.input_text, and results are normally (but its default results, as if it were disabled, however you can see that you are inserting an id #algolia-autocomplete-container in the html).

I tried to enable instant search results, but it did not work too.

[DEMO SITE](https://www.hortibras.com)

-------------------------------------------------------------------------------

I've check and is not consuming API (Last 24h Queries 62) the number dont change.

**Comment by damcou** [comment]
Hi @kauansoft , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
