### ISSUE TITLE
Algolia extension not working in Magento 2.2.2 EE(Commerce) - try to delete file from generated folder - read only file system

### ISSUE THREAD

**Issue by bilalusean** [algolia/algoliasearch-magento-2#424]
We are using the below versions of Algolia and Magento.

Algolia - 1.5.0
Magento 2.2.2 EE

Magento team strongly recommend generated folder should be read-only in Magento 2.2.2 but your extension trying to delete a file from the generated folder.

	[14-Feb-2018 09:28:09 UTC] PHP Fatal error:  Uncaught Magento\Framework\Exception\FileSystemException: The file "generated/code/Algolia/AlgoliaSearch/Controller/Adminhtml/Queue/Clear/Interceptor.php" cannot be deleted Warning!unlink(/app/kbrpim462wtxo_stg/generated/code/Algolia/AlgoliaSearch/Controller/Adminhtml/Queue/Clear/Interceptor.php): Read-only file system in vendor/magento/framework/Filesystem/Driver/File.php:382
	Stack trace:
	#0 vendor/magento/framework/Filesystem/Driver/File.php(405): Magento\Framework\Filesystem\Driver\File->deleteFile('/app/kbrpim462w...')
	#1 vendor/magento/framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/app/kbrpim462w...')
	#2 vendor/magento/framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/app/kbrpim462w...')
	#3 vendor/magento/framework/Filesystem/Driver/File.php(40

Please refer the Magento team reply http://nimb.ws/096qM8

**FYI:**
Magento 2.1.X **var/di** is moved to Magento 2.2.X **generated/metadata** 
Magento 2.1.X **var/generate** is moved to Magento 2.2.X **generated/code**

Please provide the fix ASAP.

Thanks.

**Comment by JanPetr** [comment]
Hello @bilalusean,

the Algolia extension doesn't delete any files in code.
Can you specify when the error is triggered? After which action?

Thank you!

**Comment by peterjaap** [comment]
Looks to me that **some** code is trying to delete the Algolia extension. Doesn't seem plausible that the extension is trying to delete itself.

**Comment by damcou** [comment]
Hi @bilalusean , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
