### ISSUE TITLE
Unable to set algoliaAnalyticsPushFunction

### ISSUE THREAD

**Issue by azurre** [algolia/algoliasearch-magento-2#425]
Steps to reproduce:
In head section add:
```
<script>
        if (typeof algoliaAnalyticsPushFunction !== "function") {
            algoliaAnalyticsPushFunction = function (formattedParameters, state, results) {
                var url = '/catalogsearch/result/?q=' + state.query + '&' + formattedParameters + '&numberOfHits=' + results.nbHits;
                window.dataLayer = window.dataLayer || [];
                window.dataLayer.push({
                    'event': 'Pageview',
                    'url': url
                });
            };
        }
</script>
```

Expected result:
algoliaAnalyticsPushFunction in instantsearch.js should be replaced by definition from head

Actual result:
algoliaAnalyticsPushFunction not replaced because of:
`var algoliaAnalyticsPushFunction = function (formattedParameters, state, results) {`

Please remove "var" before function definition to fix this issue.

**Comment by JanPetr** [comment]
Hello @azurre,

thank you for bringing it up! I'll remove it in the next version of the extension 💯

**Comment by davids123** [comment]
search not showing after installed ALgolia
