### ISSUE TITLE
Empty queue constant name confusing

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#432]
When reading the [docs about the EMPTY_QUEUE constant](https://community.algolia.com/magento/doc/m2/indexing-queue/), I found the name of the constant pretty confusing.

What I expected: the queue table is truncated before running the `algolia_queue_runner` index.

What was actually happening; the indexer processes everything in the queue. Afterwards, the queue is empty, that is why the constant is called that. Althought technically correct, I would say calling it `PROCESS_FULL_QUEUE` would be more logical.

**Comment by JanPetr** [comment]
Thanks for your feedback @peterjaap, definitely right on point! I'll add this name to the extension.
