### ISSUE TITLE
1.6.0 search.helper is undefined in instantsearch.js - out of scope?

### ISSUE THREAD

**Issue by guido7171** [algolia/algoliasearch-magento-2#439]
It seems like a bug?

- Magento 2.2.3
- Algolia 1.6.0
- Using a hit template with instant search

line 316 of view/frontend/web/instantsearch.js, search.helper returns as undefined

https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/instantsearch.js#L316

search is set in line 110 of view/frontend/web/instantsearch.js 

`var search = algoliaBundle.instantsearch(instantsearchOptions);`

when i replace 

`hit = transformHit(hit, algoliaConfig.priceKey, search.helper);`

with 

`hit = transformHit(hit, algoliaConfig.priceKey,  algoliaBundle.instantsearch(instantsearchOptions).helper);
`
it works well. 

it seems that the var search is not reachable or out of scope? 

The undefined behavior started since 1.6.0 .

Maybe some of my magento admin configs are not up to date, because of the new options? Maybe somebody has the same issue?

**Comment by JanPetr** [comment]
Hello @guido7171,

thanks for the report! I'll take a look on this issue and come back to you.

**Comment by peterjaap** [comment]
Here's another one, probably related;

```
Uncaught TypeError: Cannot read property 'helper' of undefined
    at window.focusInstantSearchBar (common.js:382)
    at startInstantSearch (instantsearch.js:522)
    at HTMLDocument.<anonymous> (instantsearch.js:537)
    at u (algoliaBundle.min.js:4)
    at Object.fireWith [as resolveWith] (algoliaBundle.min.js:4)
    at ready (algoliaBundle.min.js:4)
```

**Comment by guido7171** [comment]
we forgot to return search; in algoliaHookAfterInstantsearchStart

its working fine now
