### ISSUE TITLE
Trying to render algolia layered navigation with custom collection.

### ISSUE THREAD

**Issue by Spaggel** [algolia/algoliasearch-magento-2#441]
Hello,

We have a controller that returns a custom product collection, we're trying to make this work with the algolia layered navigation instead of the default magento layered navigation. There seems to be no official support for this. Is there any way of hooking into algolia search directly, or perhaps filtering the returned algolia collection?

Kind regards,
Daniel

**Comment by damcou** [comment]
Hi @Spaggel , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you need more information about it.
