### ISSUE TITLE
JS error when using current master-dev

### ISSUE THREAD

**Issue by Tantuss** [algolia/algoliasearch-magento-2#444]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Search doesn't work anymore.

JS error in console:
Uncaught ReferenceError: algolia is not defined

The error is in this file:
https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/autocomplete.js
on line 84

**Bug: What is the expected behavior?**
A working search :-).

**Bug: What is the proposed solution?**
Currently the solution was to go back to release version 1.6. There this issue doesn't exist.
But the current master-dev version does have this bug.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.3
Algolia master-dev

**Comment by mirkocesaro** [comment]
hi @Tantuss,
I had the same problem (with version 1.7.0 released today) because I rewrote the file common.js in my theme, in that file right now there is the definition of _algolia_ variable used on line 48. 

Try to check that file in your installation and compare it with the one in the algolia module.

**Comment by damcou** [comment]
Hello @Tantuss ,

Thanks for reaching us and sorry for the late answer.

It is a known issue when you update the module, it seems your static files are not updated correctly.
Can you re-deploy static files with command: php bin/magento setup:static-content:deploy ?

That'll solve the issue.

Hope this would help.

Best regards.

Damien

**Comment by mageprashant** [comment]
It's working  for me 

Thank you so much @Tantuss
