### ISSUE TITLE
Error while installing using Composer

### ISSUE THREAD

**Issue by VZeroCool** [algolia/algoliasearch-magento-2#446]
Trying to install using composer with Lattest Magento 2.2.3 with sample data.

Open git bash at Magento installtion run below command: 

 composer require algolia/algoliasearch-magento-2

Getting error as below:

There was an error extracting the ZIP file, it is either corrupted or using an invalid format.

 Unzip with ZipArchive class failed, falling back to unzip command
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.

Help needed.

**Comment by peterjaap** [comment]
Try clearing your composer cache by running `composer clearcache` and try again. If that doesn't help, try running `composer require algolia/algoliasearch-magento-2 --prefer-source` to fetch the source instead of the distribution (zipfile).

**Comment by VZeroCool** [comment]
I did try but still same issue.

**Comment by peterjaap** [comment]
@VZeroCool could you try a specific version? Let's say `composer require algolia/algoliasearch-magento-2:^1.6.0` ?

**Comment by VZeroCool** [comment]
@peterjaap , Same issue no luck. I am trying to install in xampp with Magento 2.2.3 sample data. I did try to install it with Magento 2.1 but there also same issue.

**Comment by VZeroCool** [comment]
Same issue no luck. I am trying to install in xampp with Magento 2.2.3 sample data. I did try to install it with Magento 2.1 but there also same issue.

Check screen. https://ibb.co/nL5MN7

**Comment by peterjaap** [comment]
Oh you're running on Windows. Sorry can't help with that, too much of a rabbit hole to go down for me.

**Comment by helloitsluke** [comment]
See issue #421. When the package is being extracted it's trying to create files which contain an asterisk in the filename.
