### ISSUE TITLE
 Products is not displayed when user select higher price range on Algolia search result page for US Store .

### ISSUE THREAD

**Issue by balwant20** [algolia/algoliasearch-magento-2#450]
the price filter is not  proper working for my US store https://www.angara.com.

i have using mutiple store on my site. and i am using your algolia search extension v1.4.0 & magento 2.1.7.
whenever i search any products in my US store and apply higher price filter i get no results everytime.but the same thing i do in other store like Aus, Brazil, france etc then i got appropriate results.
so i didn't get what is the problem behind this?why price filter is not working only for US Store?
can anyone figure out the solution of my problem?

*Steps to reproduce*
  1.  select US Store 
  2. search diamond, necklase, rings etc .
  3. apply higher price filter

it shows No products for this query ....

Thanks in advance....!!!!!

**Comment by JanPetr** [comment]
Hello @balwant20,

there might be some "currency" discrepancy and the extension is filtering on bad price.
Could you upgrade the extension to it's latest version and test it again?
