### ISSUE TITLE
Is there a way to add instant search to other types of product list pages, other than categories?

### ISSUE THREAD

**Issue by jackhogg** [algolia/algoliasearch-magento-2#452]
I'm wondering if there's a way, similar to the option in the Instant Search Results Page area of the configuration, "Replace Categories Page", to insert the instant search features into other product list page types, that aren't category page types. For example, a "Shop By Brand" extension, that generates product list pages based on manufacturer associations.

**Comment by damcou** [comment]
Hi @jackhogg ,

Thanks for reaching us and sorry for the late answer.

Unfortunately, the extension does not offer such feature out of the box.
But you can use your magento indices to implement your own search experience and replace the other product listings in Magento.

To help, I can advice you to have to look to the isSearchPage() method from the file  : https://github.com/algolia/algoliasearch-magento-2/blob/master/Block/Configuration.php#L12

Hope this would help.

Best regards.

Damien
