### ISSUE TITLE
Not able to create class overrides for ProductHelper methods

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#453]
**Do you want to request a *feature* or report a *bug*?**
feature

**Bug: What is the current behavior?**
Can't override a number of methods in ProductHelper

**Bug: What is the expected behavior?**
Being able to override them

**Bug: What is the proposed solution?**
Changing scope from private to protected

**Feature: What is your use case for such a feature?**
To modify the workings of the extension with an override

**Comment by JanPetr** [comment]
Hey @peterjaap,

I'm not really a fan of overriding those methods by extending the class.
What is the use case? Is there something you cannot handle by using [backend events](https://community.algolia.com/magento/doc/m2/backend/)?

**Comment by peterjaap** [comment]
@JanPetr well it's not about being a fan, it's about giving developers borader control over their codebase. What we do now is using a composer patch file to change the private methods to protected ones, and then using a class override.

The specific use-case for why we do this is the slowness in the queue runner, see #426

**Comment by peterjaap** [comment]
Closing this for now although I am still of the opinion one should never use private classes in an open source extension like this.
