### ISSUE TITLE
Fatal error: Uncaught Error: Class 'AlgoliaSearch\Client' not found

### ISSUE THREAD

**Issue by VZeroCool** [algolia/algoliasearch-magento-2#456]
I tried to install on Magento lattest 2.2.3 with Sample Data on localhost Xampp.

I did tried using composer but its also failed than i moved to manually.
Donwload package from Marketplace and install using CLI.

Getting below Error.

Anyone can help me with that.

`
Fatal error: Uncaught Error: Class 'AlgoliaSearch\Client' not found in C:\xampp\htdocs\m2fresh\app\code\Algolia\AlgoliaSearch\Helper\AlgoliaHelper.php:63 Stack trace: #0 C:\xampp\htdocs\m2fresh\app\code\Algolia\AlgoliaSearch\Helper\AlgoliaHelper.php(47): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->resetCredentialsFromConfig() #1 C:\xampp\htdocs\m2fresh\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(111): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->__construct(Object(Magento\Framework\App\Helper\Context), Object(Algolia\AlgoliaSearch\Helper\ConfigHelper), Object(Magento\Framework\Message\Manager), Object(Symfony\Component\Console\Output\ConsoleOutput)) #2 C:\xampp\htdocs\m2fresh\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Algolia\\Algolia...', Array) #3 C:\xampp\htdocs\m2fresh\vendor\magento\framework\ObjectManager\ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create(' in C:\xampp\htdocs\m2fresh\app\code\Algolia\AlgoliaSearch\Helper\AlgoliaHelper.php on line 63`

**Comment by JanPetr** [comment]
Hello @VZeroCool,

as you didn't install it with Composer, dependencies like Algolia PHP API client weren't installed as well. That's why you see this error.
Can I ask you what error you got while installing it with composer?

**Comment by VZeroCool** [comment]
@JanPetr , I am trying to install using composer on xampp windows OS, All things went normally package downloaded successfully but than after it will download 100 % than there's error as i mention below.

[https://github.com/algolia/algoliasearch-magento-2/issues/446](url)

**Comment by JanPetr** [comment]
@VZeroCool, can you try to install it now with commands:
`composer clearcache`
`composer require algolia/algoliasearch-magento-2:dev-master --prefer-source`

Let me know if it works!

**Comment by VZeroCool** [comment]
@JanPetr , Yeah It works, Thanks for your help. :+1:
