### ISSUE TITLE
Add to cart on instant search page - first time

### ISSUE THREAD

**Issue by hugo-ruivo-dw** [algolia/algoliasearch-magento-2#457]
Hi,
I have the latest Algolia for Magento 2 extension (1.6) installed and Magento 2.2.2.

When user logs in on the Frontend and make a search, for the first time (on the browser you need to clear all cookies and navigation data for the site, then log-in), on the instant search results page when he clicks the add to cart button nothing happens, item is not added to cart. On the second time the user makes a search the item is added to the cart. ( Add to cart is working with Ajax )

The expected behavior would be on the first time the user makes a search the item should be added to the cart.

Update:

I managed to track down the issue to form_key value after login. After login the window reloads and the cookie form_key gets updated but Algolia keeps old value until another window reload occurs.

**Comment by JanPetr** [comment]
Cool! Could you send a PR with the fix?

**Comment by hugo-ruivo-dw** [comment]
Sure.
