### ISSUE TITLE
Categories reindex not working

### ISSUE THREAD

**Issue by satishgadhave** [algolia/algoliasearch-magento-2#465]
Magento version: 2.1.7
Algolia extension: 1.6

I have four stores.
Categories indexed in store-2 has base URL of store-1 (not sure how, I have proper URLs in core_config_data table)
So, I deleted store-2 categories from Algolia indices and executed full section reindex from backend:
System >> Index management >> Algolia categories

I could see 8 entries in queue (4 for rebuildStoreCategoryIndex each store and 4 for saveConfigurationToAlgolia)

When queue runner executed, **no objects are created in store-2 categories index** in Algolia. In fact queue runner finishes in 8-10 seconds.

Any idea why its happening and what should I do to reindex categories properly?

**Comment by satishgadhave** [comment]
I found exception in logs:

Item  (...\Model\Category\Interceptor) with the same ID "84" already exists. in .../vendor/magento/framework/Data/Collection.php:407

Closing this for now.

**Comment by Cronium** [comment]
Having this exact same issue, and don't have any exceptions like @satishgadhave , queue runner completes in 3 seconds, and nothing is in the index.
