### ISSUE TITLE
Format currency in price slider

### ISSUE THREAD

**Issue by jahvi** [algolia/algoliasearch-magento-2#469]
Is it possible to format the currency when used to filter products as a slider? If not can this be added as a feature? The current way it looks is not very user friendly.

<img width="287" alt="screen shot 2018-04-11 at 12 12 36" src="https://user-images.githubusercontent.com/661330/38613366-a25a880e-3d81-11e8-9c5a-6237860be0c2.png">

It could even be worth having a way to add a "prefix" or "suffix" to the number to give more information, so attributes like "Width" could be shown as "100 cm" instead of just "100". 

**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
Make prices (or other numeric type attributes) easier to read in the frontend

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
Maybe add an additional Yes/No column to the Facets options to say "Format as currency?"

If going for the prefix/suffix option then it can be 2 additional text fields.

<img width="1169" alt="screen shot 2018-04-11 at 12 24 22" src="https://user-images.githubusercontent.com/661330/38613922-62370746-3d83-11e8-8186-76769ba68f8d.png">

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.3
Algolia 1.6

**Comment by damcou** [comment]
Hi @jahvi ,

This new feature has just been implemented on the develop branch : https://github.com/algolia/algoliasearch-magento-2/commit/4d65ef4f5a091fe2d8970ef478f0285f4b8962bb

It will be available on our next release.

Thanks for submitting your idea.

Best regards.

Damien
