### ISSUE TITLE
Images not found after flushing image cache

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#476]
**Do you want to request a *feature* or report a *bug*?**
feature

**Bug: What is the current behavior?**
After a product is indexed and the 'Flush Catalog Images Cache' button in the backend of Magento is clicked, all images are gone in the frontend. This is because Algolia indexes the cached URL (for example, `//www.webshop.com/media/catalog/product/cache/fd4c882ce4b945a790b629f572e4ef93/i/m/image.jpg`.

**Bug: What is the expected behavior?**
The expected behavior is that the images stay intact.

**Bug: What is the proposed solution?**
We should incorporate an image endpoint in the extension that will look for a cache file. The url that is indexed should contain that endpoint, followed by the image attribute value. If it exists, serve it. If it doesn't exist, create, save & serve it.

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
We've written a feature like this for a Magento 1 shop, for a similar usecase (but a different 3rd party). It exists of only one controller, which I'll paste here in full. The code obviously isn't usable one-on-one, but it will give you an idea what needs to be done.

Using this, the old URL:

`//www.webshop.com/media/catalog/product/cache/fd4c882ce4b945a790b629f572e4ef93/i/m/image.jpg`

Should become;

`//www.webshop.com/permalink/media/catalog/product/cache/fd4c882ce4b945a790b629f572e4ef93/i/m/image.jpg`

```
<?php
/**
 * Created by PhpStorm.
 * User: peterjaap
 * Date: 27-9-17
 * Time: 19:21
 */
class Elgentos_MediaPermalink_MediaController extends Mage_Core_Controller_Front_Action {
    
    public function catalogAction()
    {
        $requestUri = Mage::app()->getRequest()->getRequestUri();

        $checkExisting = substr($requestUri, strlen('/permalink'));

        $file = Mage::getBaseDir() . $checkExisting;
        if (file_exists($file)) {
            if (file_exists($file) || is_readable($file)) {
                $transfer = new Varien_File_Transfer_Adapter_Http();
                $transfer->send($file);
                exit;
            }
        }

        $requestParts = explode('/', $requestUri);

        $imagePath = implode('/', array_slice($requestParts, -3));
        $dimensions = '265x265';

        $originalFile = Mage::getBaseDir('media') . '/catalog/product/' . $imagePath;

        if (count($requestParts) == 14) {
            $dimensions = $requestParts[8];
        } elseif (count($requestParts) == 10) {
            $dimensions = $requestParts[6];
        } elseif (count($requestParts) == 9) {
            $dimensions = $requestParts[5];
        }

        $permalinkSource = Mage::getBaseDir('media') . '/catalog/product/cache/1/permalink/' . $dimensions . '/' . $imagePath;

        list ($width, $height) = explode('x', $dimensions);
        if (!$height) {
            $height = null;
        }

        if (file_exists($originalFile) && !file_exists($permalinkSource)) {
            $image = new Varien_Image($originalFile);
            $image->constrainOnly(false);
            $image->keepFrame(true);
            $image->backgroundColor(array(255, 255, 255));
            $image->keepAspectRatio(true);
            $image->resize($width, $height);
            $image->save($permalinkSource);
        }

        if (file_exists($permalinkSource) || is_readable($permalinkSource)) {
            $transfer = new Varien_File_Transfer_Adapter_Http();
            $transfer->send($permalinkSource);
            exit;
        } else {
            $this->_forward('noroute');
        }
    }
    
}
```

**Comment by DavidLambauer** [comment]
Hi, 

we can confirm this issue/feature. 

In addition to that, we do have the problem that the images of a specific product are gone as soon as we edited the product in the admin backend.

**Comment by JanPetr** [comment]
Hello, thank you for the report. We are aware of the issue and on ur roadmap is to create a custom extension which would solve that. Similar to @peterjaap's script.

I'm closing the issue now as we have it in our internal docs. Feel free to re-open if you have more to share. Thank you!

**Comment by peterjaap** [comment]
@JanPetr any progress on this?
