### ISSUE TITLE
Prevent Backend Rendering does not work correctly with cache enabled

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#480]
**Do you want to request a *feature* or report a *bug*?**
'Bug'

**Bug: What is the current behavior?**
Prequisites;
1. Prevent Backend Rendering is enabled
1. Allow backend rendering user agent list includes 'Googlebot'
1. Cache (full page and/or block) is enabled
1. First request on uncached category page is from non-Googlebot
1. Consecutive request is from Googlebot
1. Problem; result for Googlebot does not include backend rendering

**Bug: What is the expected behavior?**
In step 6, the result should include backend rendering.

**Bug: What is the proposed solution?**
I don't have a proposed solution. 'Workaround' now is to disable Prevent Backend Rendering or to disable full page and block cache.

**Comment by JanPetr** [comment]
Hello @peterjaap,

thank you for the report! Indeed, not an easy issue to fix properly. We will investigate and see what we can come up with. Maybe changing and cache key could help 🤔

**Comment by peterjaap** [comment]
Maybe you can make use of Magento's `X-Vary` header to differentiate based on user agents?

**Comment by peterjaap** [comment]
If you need more info on FPC in Magento 2, Mage2.tv will release a full series on FPC soon; https://www.mage2.tv/content/full-page-cache/

**Comment by damcou** [comment]
Hello @peterjaap ,

I added a commit related to this issue, would it be possible to test the Plugin on your side and give me some feedback about it ? 

https://github.com/algolia/algoliasearch-magento-2/pull/589/commits/5973cc2ffd3f9829babb05308bd8c3ce9257bc62

Thanks in advance ;)

**Comment by peterjaap** [comment]
Cool @damcou thanks! Will try to test next week.
