### ISSUE TITLE
Product get ___store parameter in URL

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#481]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
We have a multi-domain store; multiple websites with each their own store group and their own store view.

When saving a product in the backend, the product is reindexed and we noticed that (since recently?) the URL in Algolia gets the dreaded `___store` parameter added to it.

After running through the code with Xdebug, we found it to be in `vendor/algolia/algoliasearch-magento-2/Model/Product/Url.php:88`: `$routeParams['_scope_to_url'] = true;` This is then picked up by `Magento\Store\Url\Plugin\RouteParamsResolver`, which adds the `___store` parameter.

When we comment this out (or set it to false), the `___store` parameter disappears. Since we run our stores on seperate domains, the storecode is never necessary in the URL. I'm not sure why this `_scope_to_url` is even in there.

**Bug: What is the expected behavior?**
No `___store` parameter should be added to the url when each store runs on its own domain.

**Comment by peterjaap** [comment]
Additional weirdness that probably has thesame underlying cause; the `price.EUR.default_formated` suddenly is `€8.95 - €12.95` (with a dot as decimal delimiter) instead of `€8,95 - €12,95` (with a comma).

**Comment by JanPetr** [comment]
Hello @peterjaap,

thank you for the report. We'll investigate it and target it in next version! 🙌
