### ISSUE TITLE
Algolia Producthelper.php want to override?

### ISSUE THREAD

**Issue by KnagarajuK** [algolia/algoliasearch-magento-2#489]
Hi Team,

I would like to override vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php

since i would like to pass two attributes new_label and sale_label to algolia.

Can u guide me the following steps
thanks

**Comment by JanPetr** [comment]
Hello @KnagarajuK,

for that you don't need to override the Producthelper.
The best way would be to use [`algolia_after_create_product_object` event](https://community.algolia.com/magento/doc/m1/backend/#algoliaaftercreateproductobject) to modify the record and enrich it with your custom attributes.

You can learn how to use backend hooks here: https://community.algolia.com/magento/doc/m1/customize-backend/

**Comment by KnagarajuK** [comment]
@JanPetr 

Thanks for your reply. i am following the same.
