### ISSUE TITLE
Infinite scroll dont refresh lower pages

### ISSUE THREAD

**Issue by satishgadhave** [algolia/algoliasearch-magento-2#493]
You want to report a bug or feature: Bug

**Bug: What is the current behavior?**
1. Scroll down on instant search page and reach to 2nd or later pages.
2. Now apply "brand name" filter.
3. Only first page products are updated to filtered brand. Later pages show old result products.
URL: http://en-ae-staging.6thstreet.com/women/shoes.html

**Bug: What is the expected behavior?**
1. If new filter is applied, previous results should be cleared first and then new results should be loaded in container.
2. User should be scrolled to the top of page automatically

Magento version: 2.1.7
Algolia extension version: 1.6.0

**Comment by JanPetr** [comment]
Hello @satishgadhave,

thank you for the report! Can you upgrade to 1.7.0 version? It should be fixed there 👍 

Let me know if it works.
