### ISSUE TITLE
Autocomplete displays expired special prices

### ISSUE THREAD

**Issue by dev-ea** [algolia/algoliasearch-magento-2#496]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Autocomplete displays expired special prices.

**Bug: What is the expected behavior?**
Expired special prices should not be displayed.

**Bug: What is the proposed solution?**
[Same problem exists on Magento 1 version](https://github.com/algolia/algoliasearch-magento/issues/974), looks like the fix can also be applied here.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.4
Algolia 1.6.0

**Comment by JanPetr** [comment]
Thanks for the report @dev-ea! I just merge fix for this. Feel free to upgrade to master branch or wait for the next release :) 🚀
