### ISSUE TITLE
Algolia Search Products indexer process unknown error: Undefined rate from "AUD-GBP".

### ISSUE THREAD

**Issue by dungnv** [algolia/algoliasearch-magento-2#50]
Hello,

We using magento 2.1, Algolia search 0.8.4.
after run reindex i got this msg:
Algolia Search Products indexer process unknown error: Undefined rate from "AUD-GBP".

We setup multi website, each website using other base currency.
Please help me resolved this issue.

Thanks.

**Comment by JanPetr** [comment]
Hello @dungnv,

it happens when you did not fill currency rates in "Stores > Currency Rates". The extension fetches price for correct currency directly from Magento and Magento throws this error.
Just fill all your rates by "1" and it should work just fine 👍

**Comment by sajidunnar** [comment]
@JanPetr  Thanks man , it solved our issue
