### ISSUE TITLE
URL's getting ?___store=default

### ISSUE THREAD

**Issue by Tantuss** [algolia/algoliasearch-magento-2#511]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**

All url's get: ....?___store=default

**Bug: What is the expected behavior?**
Normal URL without this ?___store=default

**Bug: What is the proposed solution?**
The problem is in the file:
vendor/algolia/algoliasearch-magento-2/Model/Product/Url.php

There is stated that this is an exact copy of the original, but there is 1 small difference which make the system generate ?___store=default

The original file is:
vendor/magento/module-catalog/Model/Product/Url.php

This is in the Algolia version on line 87:
`if ($storeId !== $this->storeManager->getStore()->getId()) {
            $routeParams['_scope_to_url'] = true;
        }`

This is in the original file:
`if ($storeId != $this->storeManager->getStore()->getId()) {
            $routeParams['_scope_to_url'] = true;
        }`

The problem is that $storeId is an integer (in my case 1).
The $this->storeManager->getStore()->getId() returns a string "1".

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.4
Algolia search 1.7.0

**Comment by damcou** [comment]
Hi @Tantuss ,

Thanks for reaching us. I'm sorry for the late answer.
Would it be possible for you to send a PR for us to have a look and validate this ?

Thanks in advance.

Best regards.

**Comment by Tantuss** [comment]
Maybe a stupid question, but where should I send to you a PR message?

**Comment by JanPetr** [comment]
Hello @Tantuss and @damcou,

the fix has already been merged: https://github.com/algolia/algoliasearch-magento-2/pull/513/files
Feel free to upgrade the extension to `master` branch. The fix will be part of the next stable release.
