### ISSUE TITLE
Configurable product should be reindexed when child products are edited

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#515]

**Comment by damcou** [comment]
Hi @peterjaap ,

Thanks for reaching us.
I think you're right.
We will discuss this ASAP and see if it can be added to the extension.

I will keep you updated on this.

Thanks again.
Best regards.

**Comment by JanPetr** [comment]
Hello @peterjaap and @damcou,

this feature is present in the latest version of the extension: https://github.com/algolia/algoliasearch-magento-2/blob/master/Model/Indexer/Product.php#L65-L67

@peterjaap, does it work for you as expected? If no, feel free to re-open this issue :)
