### ISSUE TITLE
Autocomplete Not displayed correctly on Home page

### ISSUE THREAD

**Issue by haniffas** [algolia/algoliasearch-magento-2#517]
Hi,

Our version of Magento is 2.2.5 and Algolia version is 1.7.0

Algolia search was working perfectly on the base /Luma themes. As soon as we installed a custom theme from a third party, the auto-complete search box disappeared.

After an investigation, we have changed the DOM id on Algolia advanced property to #search and the search box came back (not sure why we had to do it because as per the algolia documentation it should be an issue as long as the custom theme uses top.search )

Now the issue is, on the Home page, search results (drop down box) not being displayed properly (the structure is collapsed) while the same search results being displayed properly on all other pages (Ex. Customer Login)

We have also checked the page source on Home Page for the search box it has additional elements but these tags are not on other pages which are working ok.

Any help would be much appreciated.

**Comment by haniffas** [comment]
![algolia-home](https://user-images.githubusercontent.com/32969173/42132257-4bfbcf98-7d0c-11e8-82d8-62a260e3f018.png)
![algolia-non home](https://user-images.githubusercontent.com/32969173/42132258-4c69f7ac-7d0c-11e8-8d7c-b0a937e49ef5.png)
![algolia-tags](https://user-images.githubusercontent.com/32969173/42132259-4c84af7a-7d0c-11e8-9160-d17d1cb64351.png)

**Comment by damcou** [comment]
Hi @haniffas ,

Thanks for reaching us.

Do you have any environment where we can reproduce this issue ?
Have you noticed any differences in the DOM between the HP and the other pages ?
Is the class "algolia-search-input" still applied on the search input ?

Thanks in advance.

Best regards.

**Comment by haniffas** [comment]
@damcou Thanks for looking into it. We have figured out it is due to a setting in the custom theme that causes the layout to collapse.But not sure why would it cause additional tags on algolia scripts/css as it is a seperate module..
 
As to the class , it is the same as other pages. 

<input id="search" type="text" name="q" value="" class="input-text form-control aa-input" maxlength="128" placeholder="test Search entire store here..." role="combobox" aria-haspopup="false" aria-autocomplete="list" autocomplete="off" spellcheck="false" aria-labelledby="search" aria-owns="algolia-autocomplete-listbox-0" dir="auto" style="position: relative; vertical-align: top;" aria-expanded="false">


For others who might be facing the similar issue:

We are using Ethan theme from Magesolution http://m2.magesolution.com/ethan
When you enable the theme builder with the Home Page builder option enabled , lay out is not coming well. If you disable the 'Home Page Builder' (to all the users who got it enabled) the algolia search seem to be coming ok.

**Comment by ausl** [comment]
This happens to me on the Porto Theme as well, however, i still couldn't identify what is the issue. My magento version is 2.2.5 as well, and the Algolia version is 1.7.2.
