### ISSUE TITLE
Results div disappearing with autocomplete menu deactivated and facet query rules used

### ISSUE THREAD

**Issue by damcou** [algolia/algoliasearch-magento-2#520]
**Do you want to request a *feature* or report a *bug*?**
A bug
Deactivate the autocomplete menu and create a facet query rule on one particular attribute 
Type an exact value of one of the possible value of this attribute
Facet selects automatically (facet query rule) and query is considered as empty

**Bug: What is the current behavior?**
The div containing the results disappear

**Bug: What is the expected behavior?**
Div should remain visible

**Bug: What is the proposed solution?**
Fix in js that handles this case (when a facet is selected, the div should always be visible)

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
v 1.7 (same issue with M1 extension)

**Comment by damcou** [comment]
Added to the features list in our roadmap.

**Comment by AlexEven** [comment]
I'm adding to the backlog as it's more a bug to fix rather than a new feature to develop. Thanks!
