### ISSUE TITLE
Not compatible with B2B extension

### ISSUE THREAD

**Issue by palakaccorin** [algolia/algoliasearch-magento-2#522]
Version Magento 2.2.2 EE
B2B functionality Enabled

I have created a shared catalog for the customer group. Some products only assigned to this shared catalog. Now after login if I search for the product then it shows results from all products. 

What is the current behavior?
On catalog search result page shows the result from all products so images and product options are not showing for those products which are not assigned to the current shared catalog.
(ex https://www.screencast.com/t/gOZBEbL5)

What is the expected behavior?
It should show results from current shared catalog products only.

**Comment by JanPetr** [comment]
Hello @palakaccorin,

thank you for the report.
It's true and we are aware of the extension not being compatible with B2B. We have it on our roadmap, but I cannot promise you any ETA for now.

But you can implement support for it by yourself by extending the extension:
- https://community.algolia.com/magento/doc/m2/customize-extension/
- https://community.algolia.com/magento/doc/m2/backend/
- https://community.algolia.com/magento/doc/m2/frontend-events/

Is that something you can do? Or if you'll decide to implement the support directly to the extension, I'll be very happy to see your PR 🚀
