### ISSUE TITLE
algolia reindex

### ISSUE THREAD

**Issue by tanvipatel1985** [algolia/algoliasearch-magento-2#523]
1. We are getting below error for algolia_queue_runner reindexing. 
2. And also, algolia_queue_runner is always showing running.
3. When I check in Algolia dashboard, it is showing: currently building index : 0 oldest queued job:0

ujbpigvgkcorm@i-2c5242a6:~$ php bin/magento indexer:reindex algolia_queue_runner
PHP Fatal error:  Uncaught Error: Call to undefined method Redbox\AlgoliaBlogIndexer\Helper\Entity\BlogHelper::getIndexName() in /app/ujbpigvgkcorm/vendor/redbox/module-algolia-blog-indexer/Helper/Data.php:87
Stack trace:
#0 [internal function]: Redbox\AlgoliaBlogIndexer\Helper\Data->rebuildStoreBlogIndex('6')
#1 /app/ujbpigvgkcorm/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(143): call_user_func_array(Array, Array)
#2 /app/ujbpigvgkcorm/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(108): Algolia\AlgoliaSearch\Model\Queue->run('5')
#3 /app/ujbpigvgkcorm/vendor/algolia/algoliasearch-magento-2/Model/Indexer/QueueRunner.php(46): Algolia\AlgoliaSearch\Model\Queue->runCron()
#4 /app/ujbpigvgkcorm/vendor/magento/module-indexer/Model/Indexer.php(412): Algolia\AlgoliaSearch\Model\Indexer\QueueRunner->executeFull()
#5 /app/ujbpigvgkcorm/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(38): Magento\Indexer\Model\Indexer->reindexAll()
#6 /app/ujbpigvgkcorm/vendor/symfony/console/Symfony/Component in /app/ujbpigvgkcorm/vendor/redbox/module-algolia-blog-indexer/Helper/Data.php on line 87

**Comment by peterjaap** [comment]
Seems like there's something wrong in the (third party?) `Redbox\AlgoliaBlogIndexer` extension. The `BlogHelper` class either doesn't extend the correct class or does not have an implementation of `getIndexName()` of its own.

**Comment by tanvipatel1985** [comment]
Can’t we exclude blog indexer from reindexing?

Thanks and Regards,

Tanvi Patel

Senior E-Commerce Developer

[http://www.boutique1.com/signatures/black/boutique1logo2014_1-.jpg]<http://www.boutique1.com/>

Boutique 1 Group LLC
Cayan Business Centre, TECOM
P.O.Box 27026, Dubai, UAE



Telephone

+971 4 448 3444

Direct

+971 4 448 3408

Facsimile

+971 4 448 3445



[http://www.boutique1.com/signatures/black/fb.jpg]<http://www.facebook.com/boutique1dubai>



[http://www.boutique1.com/signatures/black/prnt.jpg]<http://pinterest.com/boutiqueone/>



[http://www.boutique1.com/signatures/black/twit.jpg]<http://twitter.com/Boutique_1>



[http://www.boutique1.com/signatures/black/insta.jpg]<http://instagram.com/boutique_1/>



[http://www.boutique1.com/signatures/black/gplus.jpg]<https://plus.google.com/108138262263610540790/posts?partnerid=gplp0>
