### ISSUE TITLE
Default Auto-Complete Search Results not disabled

### ISSUE THREAD

**Issue by simonmaass** [algolia/algoliasearch-magento-2#534]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Currently if i search a term behind the algolia search-auto complete menu the magento 2 default auto-complete is showing

![auto-complete](https://user-images.githubusercontent.com/32599710/43401876-8e1ed4f8-9411-11e8-8786-8a4fbfce6450.png)

**Bug: What is the expected behavior?**
I would expect for the default auto-complete to be disabled.

**Bug: What is the proposed solution?**
I dont want to disable it via css like with display:none - is there another way to disable the default magento 2 function?

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Using Magento 2.2.5 and latest Algolia extension 1.7.1

**Comment by JanPetr** [comment]
Hello @simonmaass,

I'm sorry for the late reply.
There is no easy way how to disable autocomplete. If you use default Algolia's selector, it'll override the search box template and remove the autocomplete.
However, if you use a custom one (like `#search`), you'll need to disable it in code. Sorry I couldn't help more.
