### ISSUE TITLE
IE11 script error breaks checkout

### ISSUE THREAD

**Issue by brightonmike** [algolia/algoliasearch-magento-2#535]
**Bug: What is the current behavior?**

Our checkouts do not load correctly in IE11. A script error (the only JS error on the page) appears to be causing the problem. An update to the Algolia module coincides with a drop in orders and the occurrence of this problem. The error is:

```
SCRIPT438: Object doesn't support property or method 'for'
File: algoliaBundle.min.js, Line: 29, Column: 28087
```

**Bug: What is the expected behavior?**

There are no script errors in IE11 and the checkout loads normally.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
1.7.1

**Comment by Haroenv** [comment]
The fix for this has now been released in the latest version by the way
