### ISSUE TITLE
Some facets disappear when selecting children facet

### ISSUE THREAD

**Issue by jahvi** [algolia/algoliasearch-magento-2#548]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Some facets disappear when you select 3rd level facets.

![screen2](https://user-images.githubusercontent.com/661330/44398014-3f17a300-a53a-11e8-818a-46080f36cbdb.gif)

As you can see in the gif, when I select "Lay On Basins" some of the 2nd level facets disappear, like: "Commercial Toilets" and "Drinking Fountains".

This also happens on Algolia's demo page, see how the "Bottoms" facet disappears when selecting "Tees":

![screen2](https://user-images.githubusercontent.com/661330/44398577-522b7280-a53c-11e8-88d2-1a378d5370f1.gif)

This only seems to be an issue when selecting **3rd level** facets, when selecting **2nd level** facets all first level facets are shown and never disappear.

**Bug: What is the expected behavior?**
All 2nd level facets should remain visible when selecting 3rd level facets.

**Bug: What is the proposed solution?**
Not sure if this is intended, if so is there a way to prevent this?

If not then maybe tweaking the logic in the JS somehow.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento: 2.2.5
Algolia: 1.7.2

**Comment by developerlicw** [comment]
Seems to have the same problem using elasticsearch, anyone who knows why?

**Comment by JanPetr** [comment]
Hello there!

This is due to limited number of facet values retrieved.
Feel free to navigate to Algolia configuration in Algolia, instant search tab and increase a number of facet values to retrieve (default is 10). Then it'll work :)
