### ISSUE TITLE
Best practices and deprecated functions

### ISSUE THREAD

**Issue by BasBlanken** [algolia/algoliasearch-magento-2#549]
**Do you want to request a *feature* or report a *bug*?**
"bug" - deprecated functions and best practices that could break in future Magento versions.
Might add some changes via pull-request if I find the time, mostly adding this issue to find out if these things were on the radar for you guys.

**Bug: What is the current behavior?**
- multiple deprecated methods used that have functional alternatives hinted in the phpDoc
- ObjectManager being used over auto-generated factory classes

**Bug: What is the expected behavior?**
- use of factory classes instead via dependency injection
- using the non-deprecated alternatives to the deprecated methods used at the moment

**Bug: What is the proposed solution?**
Using the hinted (phpDoc) alternatives to deprecated functions;
Code inspection should inform of the deprecated methods based on the phpDoc "deprecated" tags

Use of factory classes;
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/factories.html

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento Commerce 2.2.5 and Algolia_AlgoliaSearch 1.7.2

**Comment by peterjaap** [comment]
A while back, I made a PR removing the ObjectManager from the extension in certain places but not all (PR https://github.com/algolia/algoliasearch-magento-2/pull/464, which was eventually merged with https://github.com/algolia/algoliasearch-magento-2/pull/495). Would be great if we can join efforts and get rid of it completely.

**Comment by JanPetr** [comment]
Hello @BasBlanken and @peterjaap,

thank you for the report! In the past few months we took a step forward on that and we're trying to get rid of `deprecated` functions and and ObjectManager usage as much as possible.

We don't use it in new features at all and trying to keep the best practices at place.

I know we're not in a perfect state now and we'd really appreciate any help. If you see a bad practice or any concrete code worth fixing, feel free to submit a PR or create an issue.

I'll close this issue now as it's very generic and we deliver new features and fixes with it in mind. Feel free to open new issues with concrete bugs / code smell / bad practices. We'll be happy to fix and merge it.

Thank you! ❤️
