### ISSUE TITLE
Add ability to include custom attribute

### ISSUE THREAD

**Issue by sashas777** [algolia/algoliasearch-magento-2#552]
**Feature: What is your use case for such a feature?**

We use Algolia Search with Magento 2 website and we need to include custom made attribute at the instant search results page. 

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
There is observer which allows to add new attribute to collection:
https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L238

This solves issue when we need to get product data. But in order to post it with reindexer to Algolia we need some event for the: 

https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L382

Its where custom attribute can be included. Of course it is possible to make a preference or plugin with around method and then do not execute default function - but it is conflict with any other extension which uses Algolia Search. 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento Enterprise Cloud 2.2.4 
Algolia_AlgoliaSearch version 1.7.2

**Comment by damcou** [comment]
Hi @sashas777 ,

I'm a little confused, why don't you directly use the extension configuration in the Magento back-office to add your custom attributes in the product attributes list to index and as facet in the instantsearch section ?

**Comment by sashas777** [comment]
Thanks it works

**Comment by aartipatel6495** [comment]
> Hi @sashas777 ,
> 
> I'm a little confused, why don't you directly use the extension configuration in the Magento back-office to add your custom attributes in the product attributes list to index and as facet in the instantsearch section ?

========
I have already tried it from Magento backend but it is not showing into search result
