### ISSUE TITLE
Color Attribute value displaying false?

### ISSUE THREAD

**Issue by KnK123** [algolia/algoliasearch-magento-2#553]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
we are using latest version of algolia, for **color** attribute value is displaying **false** at left side layered navigation, As well we are unable to search in the color filed, it has been disabled by default. 

![download](https://user-images.githubusercontent.com/39402605/44618121-8d57d980-a88d-11e8-954e-e840ccf12ac0.png)

**Bug: What is the expected behavior?**
**false** should not display and how to enable search filed at color attribute section
**Bug: What is the proposed solution?**
 We have cross checked at admin end for the 15 products, those products doesn't have color. 
**Feature: What is your use case for such a feature?**
if color value not available it should not display "false" at left side layered navigation with algolia
**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
Please advise
**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento version 2.2.3 CE
algolia 1.7.2

**Comment by damcou** [comment]
Hello @KnagarajuK ,

You're right, adding the possibility not to index empty/false values for attributes is a feature which has not been implemented yet four our Magento2 extension but it is on our roadmap.

Thanks for your feedback ! 

Best regards.

Damien

**Comment by KnagarajuK** [comment]
sounds good, Thank you so much @damcou please update when you have implemented this feature.
