### ISSUE TITLE
Theme settings for product_thumbnail_image ignored

### ISSUE THREAD

**Issue by paulvandermeijs** [algolia/algoliasearch-magento-2#554]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
Changed the size for `product_thumbnail_image` in the theme's `etc/view.xml` file. After reindexing the `thumbnail_url` in the index still references the same image as before.

**Bug: What is the expected behavior?**
The index should reference an image as defined in the `etc/view.xml` file for the theme used for the specific store view.

**Bug: What is the proposed solution?**
Use the settings from `etc/view.xml` defined in the theme used by the specific store view when creating image URLs. 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
 * Magento v2.2.0
 * Algolia extension v1.7.1

**Comment by JanPetr** [comment]
Hello @paulvandermeijs,

you can specify the sizes in advanced configuration of Algolia extension in Magento :)
