### ISSUE TITLE
catalogsearch result page is blank

### ISSUE THREAD

**Issue by mageprashant** [algolia/algoliasearch-magento-2#563]
Hi algolia team

I am using your extension version 1.7.2
I have tried to search and Enter valid product name & click on the search button after redirect to search page but search result page is shown blank.
I have getting console error like https://www.screencast.com/t/10oisW057X

Please check given the video for more information.
https://screencast-o-matic.com/watch/cFQFluqLPk

Please help on this asap.

Thanks,

**Comment by damcou** [comment]
Hi @mageprashant ,

This is a known issue.
Could you please empty your Magento & browser caches and perform a static content deploy to see if you still get the problem ?

`php bin/magento setup:static-content:deploy`

Thx in advance.

Best regards.

**Comment by mageprashant** [comment]
Hi @damcou 

I have tried below all commands 

```
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento cache:flush
```

but i still getting the issue.
https://www.screencast.com/t/iUiflifr2

Please help on this asap.

Thanks
Prashant Patel

**Comment by mageprashant** [comment]
check this
https://github.com/algolia/algoliasearch-magento-2/issues/444
