### ISSUE TITLE
Algolia 1.8.0

### ISSUE THREAD

**Issue by BrentRobert** [algolia/algoliasearch-magento-2#565]
Algolia 1.8.0 added an archivetable, though in setup updating from 1.7.2 it does not get created. Resulting in the queue runner not working.

Second issue I'm having when trying to reindex or running the queue runner:

```
Exception:
Notice: Undefined property: Algolia\AlgoliaSearch\Helper\Entity\Product\PriceManager::$priceManagerEvent in vendor/algolia/algoliasearch-magento-2/Helper/Entity/Product/PriceManager.php on line 69
```

**Comment by JanPetr** [comment]
Thank you for the report, @BrentRobert! ❤️ 

I've just merged fix (#566), could you update to `master` to test it out? Thanks!

**Comment by BrentRobert** [comment]
Hi, thanks for the very fast response. I'll check it out as soon as possible!

**Comment by damcou** [comment]
Hi @BrentRobert ,

Were you able to test the fix ?
Let us know.

Best regards.

Damien

**Comment by damcou** [comment]
Hi @BrentRobert, 

Thanks for you feedback.
Glad that everything works on your side now ;) .

Happy searching !
