### ISSUE TITLE
Unable to reindex properly with 1.8.0

### ISSUE THREAD

**Issue by KnagarajuK** [algolia/algoliasearch-magento-2#568]
**Do you want to request a *feature* or report a *bug*?**

  Bug

**Bug: What is the current behavior?**

Unable to re-index products in magento 2.2.3 CE  getting an error 

Algolia Search Products indexer process unknown error:

Warning: Illegal offset type in /srv/public_html/vendor/magento/module-catalog/Model/ProductRepository.php on line 235 

seems that the indexer for algolia_products is failing because of the following line:

    public function get($sku, $editMode = false, $storeId = null, $forceReload = false)

    {

        $cacheKey = $this->getCacheKey([$editMode, $storeId]);

        if (!isset($this->instances[$sku][$cacheKey]) || $forceReload) {

            $product = $this->productFactory->create();

            $productId = $this->resourceModel->getIdBySku($sku);

**Bug: What is the expected behavior?**

 able to re-index properly.

**Bug: What is the proposed solution?**

Kindly check and fix it.

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento:- 2.2.3 CE
name: algolia/algoliasearch-client-php
version: 1.27.0
name: algolia/algoliasearch-magento-2
version: 1.8.0
 
https://prnt.sc/kwifvr
https://prnt.sc/kwixa7

Could you please suggest. thanks

**Comment by damcou** [comment]
Hi @KnagarajuK ,

Thanks for reaching us.
I tried to reproduce this issue with Magento 2.2.3 but everything seems good to me on my side.

Can you please tell me more about it ?
Did you get this error before updating to version 1.8.0 ?
Is there any additional logs or reports that you can provide ?

Let me know.

Best regards.

**Comment by KnagarajuK** [comment]
I have upgraded to 1.8.0 on yesterday then i got this issue

**Comment by damcou** [comment]
Could you please var_dump the $sku variable before the line 235 and reindex the algolia_products indexer to see why and when you get the illegal offset type ?

**Comment by KnagarajuK** [comment]
@damcou 

Thanks for your suggestion, but we have downgraded algolia to 1.7.2 then we can able to reindex.

**Comment by damcou** [comment]
Could you please try to reproduce the issue on a staging/dev environment to investigate more ?

**Comment by damcou** [comment]
Hi, I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
