### ISSUE TITLE
Undefined index Exception in ConfigHelper if HTTP_USER_AGENT is not set

### ISSUE THREAD

**Issue by michaelscheel** [algolia/algoliasearch-magento-2#570]
`{"0":"Notice: Undefined index: HTTP_USER_AGENT in \/var\/www\/html\/vendor\/algolia\/algoliasearch-magento-2\/Helper\/ConfigHelper.php on line 668","1":"#0 \/var\/www\/html\/vendor\/algolia\/algoliasearch-magento-2\/Helper\/ConfigHelper.php(668): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined index...', '\/var\/www\/html\/v...', 668, Array)\n#1`

**Bug: What is the current behavior?**
Module is throwing an exception if no HTTP_USER_AGENT is given, which some more or less trustworthy bots do when they crawl our site. (https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/ConfigHelper.php#L717)

**Bug: What is the expected behavior?**
Don't crash when HTTP_USER_AGENT is not set. HTTP_USER_AGENT is not a required property.

**Bug: What is the proposed solution?**
Check if HTTP_USER_AGENT is set. If not, enable backend rendering.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
latest version, Magento 2.2.5

**Comment by damcou** [comment]
Hi @michaelscheel ,

Thanks for your feedback.
Actually, backend rendering feature will be one of the main topics that we are going to work on during the next weeks/monthes.

So be sure that this issue will be taken into account. We will keep you updated about it.

Thanks again.
Best regards.
Damien

**Comment by JanPetr** [comment]
Hello @michaelscheel,

thank you for the report. The fix has been submitted^ and will be merged soon 🚀
