### ISSUE TITLE
Show error when access "Indexing Queue" grid feature in backend

### ISSUE THREAD

**Issue by BanyuUrip** [algolia/algoliasearch-magento-2#574]
**Do you want to request a *feature* or report a *bug*?**
_Bug._
Steps to reproduce:

- Install Magento EE v2.1.10 and Algolia Search v.1.8.1 (latest)
- Go to magento backend
- Click Menu Stores -> Algolia Search -> Indexing Queue

**Bug: What is the current behavior?**
_Show error on screen._

> 1 exception(s):
> Exception #0 (Magento\Framework\Exception\LocalizedException): Element 'settings': This element is not expected. Expected is one of ( form, fieldset, paging, filters, massaction, action, columns, container, field, dataSource ).
> Line: 37
> 
> Element 'settings': This element is not expected. Expected is one of ( column, actionsColumn, selectionsColumn ).
> Line: 59
> 
> Exception #0 (Magento\Framework\Exception\LocalizedException): Element 'settings': This element is not expected. Expected is one of ( form, fieldset, paging, filters, massaction, action, columns, container, field, dataSource ).
> Line: 37
> 
> Element 'settings': This element is not expected. Expected is one of ( column, actionsColumn, selectionsColumn ).
> Line: 59

**Bug: What is the expected behavior?**
_Show data grid._

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
_Algolia Search v1.8.1
Magento EE v2.1.10_

https://github.com/algolia/algoliasearch-magento-2/blob/4bcc50f7b3334de06fa4031ea66423065ef4a678/view/adminhtml/ui_component/algolia_algoliasearch_indexing_queue_listing.xml

I believe the file above caused an error (some of xml syntax is not supported by Magento 2.1.x).

**Comment by damcou** [comment]
Hello @BanyuUrip ,
Thanks a lot for reporting that, I'm on it now.

I'll keep you updated.

Thanks again.
Best regards.

Damien

**Comment by damcou** [comment]
Hi again @BanyuUrip ,

we made a change on the xml file : https://github.com/algolia/algoliasearch-magento-2/commit/9a13b2ac6ab47a1559025b74c54dc5145f81388a

we just merged to master branch. Can you upgrade dev-master version with your composer and give it a try to see if you still have the issue?

Thanks in advance.

Best regards.

Damien

**Comment by BanyuUrip** [comment]
Hi @damcou,

I have tested it and confirm that the error has been fixed. Now the grid has appeared properly in Magento 2.1.x.
I hope this update will be included in next release soon.

Thankyou for your quick response and help.

Best Regards
