### ISSUE TITLE
Making URLs relative

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#576]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Bug: What is the current behavior?**
The indexed URLs for the products in the ALgolia index are absolute urls (i.e. `https://webshop.com/en/my-product-name`)

Maybe also do this for the image URLs.

**Bug: What is the expected behavior?**
Having relative URLs; `/en/my-product-name`

**Bug: What is the proposed solution?**
When pushing the URL to the index, don't include the domain

**Feature: What is your use case for such a feature?**
We have a lot of test environments set up for our clients (and local dev environments) and when we use the regular index, the URLs point to the production site instead of the local environment. This is pretty annoying since now we have to create indices per environment and push all records there which takes a lot of time.

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
A configuration option would be nice to make this backward compatible (having the default set to including the domain).

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
M2.2.6 + Algolia 1.7.1

**Comment by peterjaap** [comment]
Temporary workaround; I modify the extension a bit to strip off the domain part before the hit object gets sent to the template.

Modify `common.js` and add this function after line 49;

```
makeUrlRelative = function (url) {
            var hostname;
            //find & remove protocol (http, ftp, etc.) and get hostname

            if (url.indexOf("//") > -1) {
                hostname = url.split('/')[2];
            }
            else {
                hostname = url.split('/')[0];
            }

            //find & remove port number
            hostname = hostname.split(':')[0];
            //find & remove "?"
            hostname = hostname.split('?')[0];

            var positionHostname = url.indexOf(hostname);

            return url.replace(hostname, '').substr(positionHostname);
        };
```

Then modify `window.transformHit` function and make these three lines the first lines in the function;

```
hit['url'] = this.makeUrlRelative(hit['url']);
hit['image_url'] = this.makeUrlRelative(hit['image_url']);
hit['thumbnail_url'] = this.makeUrlRelative(hit['thumbnail_url']);
```

**Comment by peterjaap** [comment]
Updated patch for Algolia extension 1.9.1;

```
diff --git a/view/frontend/web/internals/common.js b/view/frontend/web/internals/common.js
index 9e3c446..b0c4ce4 100644
--- a/view/frontend/web/internals/common.js
+++ b/view/frontend/web/internals/common.js
@@ -67,7 +67,31 @@ requirejs(['algoliaBundle'], function(algoliaBundle) {
 			return "";
 		};
 
+		makeUrlRelative = function (url) {
+			var hostname;
+			//find & remove protocol (http, ftp, etc.) and get hostname
+
+			if (url.indexOf("//") > -1) {
+				hostname = url.split('/')[2];
+			} else {
+				hostname = url.split('/')[0];
+			}
+
+			//find & remove port number
+			hostname = hostname.split(':')[0];
+			//find & remove "?"
+			hostname = hostname.split('?')[0];
+
+			var positionHostname = url.indexOf(hostname);
+
+			return url.replace(hostname, '').substr(positionHostname);
+		};
+
 		window.transformHit = function (hit, price_key, helper) {
+			hit['url'] = this.makeUrlRelative(hit['url']);
+			hit['image_url'] = this.makeUrlRelative(hit['image_url']);
+			hit['thumbnail_url'] = this.makeUrlRelative(hit['thumbnail_url']);
+
 			if (Array.isArray(hit.categories))
 				hit.categories = hit.categories.join(', ');
 
-- 
2.17.1

```

**Comment by JanPetr** [comment]
Hello @peterjaap,

thank you for the report and the idea. And I'm sorry for not reacting earlier.
We took this idea internally and we have it on our roadmap. But to be honest, currently it doesn't have a big priority. We'll see if we get into implementing it :)

Thank you for your contributions 💯 🙌

**Comment by tomkingfisher** [comment]
Our product links are fine however, we have an issue with the Categories linking to the default store rather than the store that it should go to.

**Comment by amit4106udale** [comment]
Is this implemented in latest algolia @JanPetr

**Comment by peterjaap** [comment]
@amit4106udale no not yet.
