### ISSUE TITLE
Error in indexing magento product to algolia

### ISSUE THREAD

**Issue by shashiLBB** [algolia/algoliasearch-magento-2#579]
Hello,

While indexing I am getting an error in Helper/configHelper.php file.

Warning: array_filter() expects parameter 1 to be array, boolean given in /opt/bitnami/apps/magento/htdocs/vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php on line 635

Warning: array_filter() expects parameter 1 to be array, boolean given in /opt/bitnami/apps/magento/htdocs/vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php on line 596

**Comment by damcou** [comment]
Hi @shashiLBB ,

Thanks for reaching us.

Could you tell us what is your Magento version ? Your Algolia extension version ? 
Could you also please run this SQL query and send us the result ?

`select * from core_config_data where path like "%algoliasearch_categories%";`

Thanks in advance.

Best regards.
Damien

**Comment by jfahrni** [comment]
Hello

i have the same or similar Problem:

Warning: min(): Array must contain at least one element in /home/www-data/magento2/vendor/algolia/algoliasearch-magento-2/Helper/Entity/Product/PriceManager/Configurable.php on line 22 in /home/www-data/magento2/vendor/magento/framework/App/ErrorHandler.php:61

Magento 2.2.6
Algolia 1.8.2

and this is my Export from your last question: (select * from core_config_data where path like "%algoliasearch_categories%";)

"config_id","scope","scope_id","path","value"
1210,"default",0,"algoliasearch_categories/categories/show_cats_not_included_in_navigation",1
1211,"default",0,"algoliasearch_categories/categories/index_empty_categories",1
1240,"default",0,"algoliasearch_categories/categories/category_additional_attributes","[{\"attribute\":\"name\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"},{\"attribute\":\"path\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"},{\"attribute\":\"description\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"},{\"attribute\":\"meta_title\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"},{\"attribute\":\"meta_keywords\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"},{\"attribute\":\"meta_description\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"},{\"attribute\":\"product_count\",\"searchable\":\"1\",\"retrievable\":\"1\",\"order\":\"unordered\"}]"
1241,"default",0,"algoliasearch_categories/categories/custom_ranking_category_attributes","[{\"attribute\":\"product_count\",\"order\":\"desc\"}]"

Best, Jonas

**Comment by JanPetr** [comment]
Hello, this issue has been resolved and is fixed in the latest version of the extension 🙌
