### ISSUE TITLE
Possible Feature - Search Segmentation

### ISSUE THREAD

**Issue by ezequielalba** [algolia/algoliasearch-magento-2#581]
Hi!

I have been working with Algolia module for Magento 2 quite a while, but now I am facing a new challenge. The client wants to make the search to be filtered too by user segmentation, based on custom attributes, past orders, user location (probably), etc.

Do you think this is possible to implement it with the current extension? or Do I have to create all my instant search page custom? 

I now that with a Hook.js I can accomplish certain customizations, but to overwrite stuff from the module is not the best way. So I want to be sure this is possible with the current extension as it is. 

Thanks for your time!

**Comment by peterjaap** [comment]
We made a site-wide filter just with a custom widget that we add to the frontend by using hooks. You can see it in action at for example https://www.all4honda.com/en/honda-interior (the car make/model selector above the products is the custom widget).

**Comment by ezequielalba** [comment]
It is @peterjaap 
https://www.algolia.com/doc/guides/ranking/personalization/#optional-filters

That works.

**Comment by peterjaap** [comment]
@ezequielalba great stuff. Didn't understand your case there but now I see :)
