### ISSUE TITLE
Search results autocomplete does not close on mobile devices

### ISSUE THREAD

**Issue by StevenGuapaBV** [algolia/algoliasearch-magento-2#583]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
On mobile devices the autocomplete menu does not close when the user wants to click anything outside of the search. 

**Bug: What is the expected behavior?**
When a user clicks outside of the search, the autocomplete should not be visible anymore. Same behavior as the desktop rendering.

**Bug: What is the proposed solution?**
Fix the javascript that handles the display. 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento EE 2.2.6 & Algolia 1.8.1

**Comment by simonmaass** [comment]
we have the same issue - would love to have help

**Comment by Nicelabsrl** [comment]
You should try to change this statement in view/frontend/web/autocomplete.js 

`options.debug = true;`
to
`options.debug = false;`
