### ISSUE TITLE
"_EMPTY_" string sent when search has no results

### ISSUE THREAD

**Issue by StevenGuapaBV** [algolia/algoliasearch-magento-2#584]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When the search query has no results, the "See all products" link becomes active. This link now has the "magentoinstance.com/catalogsearch/result/?q=__empty__" href. This results in the magento search result page with the title: search results for:  __empty__
 
**Bug: What is the expected behavior?**
This should be a customer friendly search title, not __empty__

**Bug: What is the proposed solution?**
This could be refactored to show another query like "all products". 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento EE 2.2.6 & Algolia 1.8.1

**Comment by simonmaass** [comment]
had the same problem... we fixed it like this:

use Magento\Search\Helper\Data as SearchDataHelper;

class SearchDataHelperPlugin
{
    public function afterGetEscapedQueryText(SearchDataHelper $subject, string $result)
    {
        /** when aloglia is used, you can hit the search result page with __empty__
         *  By replacing the __empty__ with an empty string at this place, we prevent the __empty__ to be rendered
         *  in the search-box and in the Page Title and on the page as well.
         */
        return $result === '__empty__' ? '' : $result;
    }
}
