### ISSUE TITLE
Layered navigation filters don't work in search result page

### ISSUE THREAD

**Issue by JonnyStecchino** [algolia/algoliasearch-magento-2#590]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When doing a search, for example https://dev.jonathan.it/en/catalogsearch/result/?q=futaba 
Layered Navigation filters do not work, for example trying to filter in the first attribute below the categories: TELEMETRIA, always show all results, any filter attributes. 

**Bug: What is the expected behavior?**
Layered navigation should filter products correctly

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
I'm using algoliasearch-magento-2 1.8.2 and Magento CE 2.2.6

**Comment by Nicelabsrl** [comment]
Hello, I have the same problem with my one of my clients too.
Unfortunately I will not be able to use your module until you find a solution.

Thanks

**Comment by JonnyStecchino** [comment]
I'm back on this problem, can not you test in our server DEV? We give you the SSH and Admin credentials (in private) for access and you can test directly in our installation.

**Comment by damcou** [comment]
Hello @JonnyStecchino ,

Sorry for the late reply, I had a look at this issue today.
We are currently working on a new feature about SEO including a revamp of the Backend Adapter. I added a fix that should handle the filtering where Instantsearch is disabled on the catalogsearch page.

This will be available in the next version of the extension (probable ETA : mid december).

Thanks again for your feedback !

Damien

**Comment by JonnyStecchino** [comment]
Hi Damien,
Is not there a chance to try this Fix in my installation?
So I make a final decision because with this problem it Algolia is not usable for me.
If necessary, please send me the file you have corrected or, if you want to try directly on my development server, I will send you the login credentials.

Thank You
Franco

**Comment by damcou** [comment]
The problem is that the fix is part of a bigger feature that is currently being reviewed on our side, so it probably won't work on the current version. 

Here is the PR : https://github.com/algolia/algoliasearch-magento-2/pull/616/files

**Comment by JonnyStecchino** [comment]
I understood, thanks

**Comment by JonnyStecchino** [comment]
Unfortunately, even with the 1.9 update you have not solved the problem with the filters, do you have some news for me?

**Comment by JonnyStecchino** [comment]
Hello @JanPetr 
I'm sorry but I have already explained everything, I had also made available my server dev for the tests, but usually no answer.
As soon as possible I will uninstall Algolia from my website.
Thank You
