### ISSUE TITLE
Blank Admin Configuration Pages

### ISSUE THREAD

**Issue by nickpiro** [algolia/algoliasearch-magento-2#595]
Using latest version (was hoping that would fix this issue). Was using 1.7.1, now using latest version 1.8.2 on Magento 2.2.5.

I receive this error in my logs when I load one of these pages.
- main.CRITICAL: Unable to unserialize value.

Unable to view admin configuration pages
- Autocomplete Menu
- Instant Search Results Page
- Products
- Categories

**Comment by hobadams** [comment]
We've also seen this issue. Any solutions would be appreciated.

**Comment by nickpiro** [comment]
Still no answers on this? Little strange how we're the only two people experiencing this...

**Comment by JanPetr** [comment]
Hello @nickpiro and @hobadams, we have a fix ready in master branch, should be tagged as stable today. Feel free to upgrade and let me know how it works for you.

**Comment by hobadams** [comment]
@nickpiro - we have solved this. You may need to empty any serialised data in Algolia config settings from the `store_config` table. 

If you remove the module from `setup_module` and re run setup upgrade it will install the defaults correctly for you.

**Comment by nickpiro** [comment]
@JanPetr I'd like to say the update worked for us, but it did not. 

@hobadams, you recommend uninstalling via composer and reinstalling?
