### ISSUE TITLE
Error No method named searchRules

### ISSUE THREAD

**Issue by wafdar** [algolia/algoliasearch-magento-2#596]
Hi, 
Every save the configuration in admin, I receive this error "Something went wrong while saving this configuration: No method named searchRules was found."

I receive this error too in my log main.CRITICAL: Exception message: No method named searchRules was found.

Algolia Version 1.8.2
Magento Version 2.1.8

Thanks

**Comment by JanPetr** [comment]
Hello @wafdar,

can you update Algolia's PHP client to its latest 1.* version? 
Just run `composer update algolia/algoliasearch-client-php:1.*` on your Magento instance and it'll update it.
