### ISSUE TITLE
Queue runner only processes 1 job

### ISSUE THREAD

**Issue by QuentinFarizonAfrimarket** [algolia/algoliasearch-magento-2#597]
** Bug report : Queue runner only processes 1 job **

1 Activate queue runner, set number of jobs to 50

![image](https://user-images.githubusercontent.com/33634848/47357249-720b1e00-d6c6-11e8-9487-c9124a310f8c.png)

2 Add products to reindex

![image](https://user-images.githubusercontent.com/33634848/47357261-7cc5b300-d6c6-11e8-988c-d6a028180b36.png)

3 Run queue runner

```
server ~ $ /usr/bin/php /space/www/magento/current/src/bin/magento indexer:reindex algolia_queue_runner
1 jobs processed in 9 seconds.
Algolia Search Queue Runner index has been rebuilt successfully in 00:00:09
```

**Bug: What is the current behavior?**
Only one job has been processed (confirmed by command output and back-office display)

**Bug: What is the expected behavior?**
50 jobs should be processed

Magento 2.1.13
Algolia 1.8.2 (latest)
It was working well on Algolia 1.6.0

**Comment by akosglue** [comment]
I also noticed this on 2.2.6
any comment on this?

**Comment by damcou** [comment]
Hello @QuentinFarizonAfrimarket ,

I just checked and I don't reproduce the issue on my side.
Could you tell me if you get any error in your Magento logs during the process ?
Is there any records in the algoliasearch_queue_ archive table in DB ?

Could you also please try to var_dump the size of the $jobs array here : https://github.com/algolia/algoliasearch-magento-2/blob/master/Model/Queue.php#L157

Thanks in advance.
Best.
Damien

**Comment by Lipdk** [comment]
Hello @QuentinFarizonAfrimarket ,

I believe the issue is in the file `vendor/algolia/algoliasearch-magento-2/Model/Queue.php` 

Around the line  248:
```$limit = $maxJobs = ($maxJobs === -1) ? $this->configHelper->getNumberOfJobToRun() : $maxJobs;```

The value coming from the `configHelper` is a string, and around the line 286 a strong type comparison is done:

```
if (count($rawJobs) === $maxJobs) {
    $jobs = $rawJobs;
    break;
}
```

A quick fix would be change the condition to `if (count($rawJobs) == $maxJobs)` or change the line 248 to ```$limit = $maxJobs = ($maxJobs === -1) ? (int) $this->configHelper->getNumberOfJobToRun() : $maxJobs;```

This worked for me, hopefully it will help you as well.
Rgds,
Luis

**Comment by JanPetr** [comment]
Hello @QuentinFarizonAfrimarket and @Lipdk,

the fixing PR has been submitted^. Feel free to give it a try.

[Thank you](http://bit.ly/2KHTYV3) for the report ❤️
