### ISSUE TITLE
Multilanguage Category URL for multilanguage storeview not indexed

### ISSUE THREAD

**Issue by pimruiter** [algolia/algoliasearch-magento-2#598]
** Bug report : Multilanguage Category URL for multilanguage storeview not indexed **

**Bug: What is the current behavior?**
When having multilangual URL's for each storeview only the global url (storeId 0) is indexed in Algolia.

<domain>/<language>/<EN category url> indexed right
<domain>/<language>/<NL category url> not indexed, the URL above is indexed.

**Bug: What is the expected behavior?**
The multilanguagel category URL is indexed. 

**Bug: What is the proposed solution?**
When indexing the category URL pass the current store_id when fetching URL from rewrite table.

For now, I have created a workaround with the events dispatched after the category object is created. 

**What is the version of Magento and of Algolia extension you are using?**
Current latest version 1.8.2. Magento 2.2.6.

**Comment by akosglue** [comment]
any updates on this?

**Comment by JanPetr** [comment]
Hello there!

Thank you for the report, the extension is [fixed now](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/CategoryHelper.php#L236). Feel free to upgrade to the latest version and give it a try :)
