### ISSUE TITLE
Magento 2.2.6 - Search refinement does not refine results

### ISSUE THREAD

**Issue by JackWormUK** [algolia/algoliasearch-magento-2#601]
Do you want to request a feature or report a bug?
Bug

Bug: What is the current behavior?
If a search is performed on the standard products within magento such as
/catalogsearch/result/?q=bac
36 products are returned.  If this in then refined;
catalogsearch/result/index/?cat=11&q=bac
36 products are returned
Flushing everything and re-indexing does not fix the issue. All indexes are ready, except for
Algolia Search - Delete inactive products

Bug: What is the expected behavior?
When this search string is used
catalogsearch/result/index/?cat=11&q=bac
8 products should be returned
If Algolia is disabled in the admin section Enable Search -> 'No' then this is the behavior that we see.

Notes:
We have a few modules from Amasty and Aheadworks installed along with the Weltpixel theme

What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.
Magento CE 2.2.6 & Algolia 1.8.2

**Comment by JackWormUK** [comment]
Thank you but we have integrated a different solution a long time ago.

**Comment by JonnyStecchino** [comment]
Hello, I also have doubts about Algolia and if they do not solve this problem I will change solution, what solution are you using? Can you send me the link of your site?
Thanks

**Comment by JackWormUK** [comment]
I used the Amasty.com elastic search module and setup elastic search software on its own server.

Amasty have a demo on their website and I can confirm it works perfectly.

**Comment by JackWormUK** [comment]
Our site is still in development. I will let you know when it is online.

I have indexed the descriptions for the standard content/demo content and it searches in a few seconds

**Comment by JanPetr** [comment]
Hello there,

we update the backend rendering and filtering capabilities in the latest version of the extension.
Feel free to give it a try and let us know what you think 🚀

**Comment by JonnyStecchino** [comment]
Hello Petr,
if the latest version is 1.8.4, I confirm that it does not work the same, already tried.
Franco

**Comment by JanPetr** [comment]
@JonnyStecchino, 1.8.4 doesn't have it implemented. Can you upgrade to 1.9.1?

**Comment by JonnyStecchino** [comment]
Done, it does not work the same.
