### ISSUE TITLE
Using passive listeners with algoliaBundle.min.js

### ISSUE THREAD

**Issue by ozzman6154** [algolia/algoliasearch-magento-2#605]
Hello,

While doing a performance audit for one of my client's website that uses Algolia Search extension, it was found that the Algolia bundled JS did not use the "Passive" flag for every event listener.  By adding this flag, it will help to improve page load performance.

More implementation details can be found here: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

Version tested on:
Algolia extension: 1.7.2
Magento:  Magento Commerce Cloud version 2.1.10

Regards,
ozzman

**Comment by damcou** [comment]
Hello @ozzman6154 ,

Thanks a lot for you feedback, this is indeed very interesting.

But, we can't use this for now for 2 main reasons: 
- Instantsearch.js is embedded in the bundle and it requires preact to work. Unfortunately preact doesn't support the passive event listeners for now : https://github.com/developit/preact/issues/428
- Passive event listeners are not natively supported by IE : https://caniuse.com/#feat=passive-event-listener

Feel free to reopen this issue if you have more questions.

Thanks again.
Best regards.
Damien
