### ISSUE TITLE
Page index emulation not stopped after error

### ISSUE THREAD

**Issue by bartbollen93** [algolia/algoliasearch-magento-2#613]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
On an environment with multiple stores, the information within the page indexing can be wrong when an error occurs because the error isn't stopping the emulation. This occurs in \Algolia\AlgoliaSearch\Helper\Data::rebuildStorePageIndex. The emulation is started at the begin of the function and is ended at the ending of the function. But when an error (like record size too big) would occur between the start and stop, the emulation is never stopped. So when the indexer tries to index another store, it is using the store that was emulated before the error because it's still active. As a result of this, wrong data is send to Algolia (like the wrong store in the URL).

**Bug: What is the expected behavior?**
When an error occurs, the emulation must be stopped.

**Bug: What is the proposed solution?**
Write a try-catch for everything between `$this->startEmulation($storeId)` and `$this->stopEmulation()` so that in case of an error, the emulation is stopped in the catch statement.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento EE 2.2.6 & Algolia 1.8.2

**Comment by JanPetr** [comment]
Hello @bartbollen93 ,

thank you for the report and I'm sorry for the late answer.
We took the reported issue back internally and we'll investigate soon and send an update here.

If you have more information or details, feel free to share it with us here, it'll help us to fix it. Thank you!

**Comment by JanPetr** [comment]
Fixed, it'll be part of the next release 🎉
