### ISSUE TITLE
Fatal error: Uncaught Error: Class 'AlgoliaSearch\Version' not found

### ISSUE THREAD

**Issue by agghanim** [algolia/algoliasearch-magento-2#614]
Hello there,

First off, let me say that I installed it manualy by uploading it to FTP. I can't use composer as my phplimit is 768M, and nope, it can't be set higher (shared hosting).

I'm getting the following error when I try to access my admin panel after installing AlgoliaSearch:

`Fatal error: Uncaught Error: Class 'AlgoliaSearch\Version' not found in /******/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php:56 Stack trace: #0 /******/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Algolia\AlgoliaSearch\Helper\AlgoliaHelper->__construct(Object(Magento\Framework\App\Helper\Context), Object(Algolia\AlgoliaSearch\Helper\ConfigHelper), Object(Magento\Framework\Message\Manager), Object(Symfony\Component\Console\Output\ConsoleOutput)) #1 /******/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Algolia\\Algolia...', Array) #2 /******/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Algolia\\Algolia...') #3 /******/vendor/magento/f in /******/app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php on line 56`

I could bypass the error by simply removing the following from AlgoliaHelper.php:

'Version::addPrefixUserAgentSegment('Magento2 integration', $this->config->getExtensionVersion());
        Version::addSuffixUserAgentSegment('PHP', phpversion());
        Version::addSuffixUserAgentSegment('Magento', $this->config->getMagentoVersion());
        Version::addSuffixUserAgentSegment('Edition', $this->config->getMagentoEdition());'

EDIT: the extension doesn't want to be enabled:

'Fatal error: Uncaught Error: Class 'AlgoliaSearch\Client' not found in /******//app/code/Algolia/AlgoliaSearch/Helper/AlgoliaHelper.php:70
etc ...'

This command wouldn't go through because of the shared hosting limitations:
'composer require algolia/algoliasearch-magento-2'

But this did work:
'composer require algolia/algoliasearch-magento-2:dev-master --prefer-source'

Some more errors came up, but were easy fixes by removing the app/code/Algolia/AlgoliaSearch directory

Not sure if I've fixed it, no search bar is showing up for now

**Comment by JanPetr** [comment]
Hello @agghanim,

this happens when you don't install the extension with Composer and it's missing dependency on PHP API client.
Can you install the extension with Composer by running `composer require algolia/algoliasearch-magento-2`?
