### ISSUE TITLE
Autocomplete does not display special price when today is equal product's `special_to_date` attribute

### ISSUE THREAD

**Issue by dev-ea** [algolia/algoliasearch-magento-2#618]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**Bug: What is the current behavior?**

When the product's `special_to_date` attribute is equal today's date, the special price is not displayed on autocomplete.

**Bug: What is the expected behavior?**

The special price should be displayed, because it's not expired yet. 

**Bug: What is the proposed solution?**

Based on https://github.com/algolia/algoliasearch-magento-2/blob/1.8.3/view/frontend/web/internals/common.js#L158-L161, you use **now**'s timestamp. It should be **today's midnight** timestamp. 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.2.6
Algolia_AlgoliaSearch 1.8.3

**Comment by JanPetr** [comment]
Solved and released 🎉

**Comment by JanPetr** [comment]
[Thank you](http://bit.ly/2KHTYV3) for the report, @dev-ea 👍
