### ISSUE TITLE
Installing Algoliasearch-magento-2

### ISSUE THREAD

**Issue by amarlot** [algolia/algoliasearch-magento-2#621]
Hello team,
I wanted to test your module and so set up a VM from GCP marketplace with Magento 2.2.6.
When I tried to install, i got this error with composer
It seems there is a dependancy missing.
Any idea ?
Alex

sing version ^1.8 for algolia/algoliasearch-magento-2
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - algolia/algoliasearch-magento-2 1.8.3 requires magento/framework ~100.0|~101.0 -> no matching package found.
    - algolia/algoliasearch-magento-2 1.8.2 requires magento/framework ~100.0|~101.0 -> no matching package found.
    - algolia/algoliasearch-magento-2 1.8.1 requires magento/framework ~100.0|~101.0 -> no matching package found.
    - algolia/algoliasearch-magento-2 1.8.0 requires magento/framework ~100.0|~101.0 -> no matching package found.
    - Installation request for algolia/algoliasearch-magento-2 ^1.8 -> satisfiable by algolia/algoliasearch-magento-2[1.8.0, 1.8.1, 1.8.2, 1.8.3].
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Installation failed, deleting ./composer.json.

**Comment by amarlot** [comment]
Hello,
I found the issue. I was on the default directory of magento. (In my case : /var/www/html).
It's not in the documentation in step1 : https://community.algolia.com/magento/doc/m2/getting-started/
If it's correct, maybe it could be interesting to add it.
Thanks,
ALex

**Comment by JanPetr** [comment]
Great you managed to resolve it, @amarlot. We'll update the docs :)
