### ISSUE TITLE
algoliaBundle.js 404 

### ISSUE THREAD

**Issue by ZayLong** [algolia/algoliasearch-magento-2#623]
I have no clue how to actually replicate this, but maybe the devs can point me in the right direction because this has been driving me nuts.

Basically what happens periodically to my magento 2 sites, is that I'll get a 404 error complaining that algoliaBundle.js cant be found.

It tries to locate it in the base directory for a themes pub static. i.e. 
/pub/static/frontend/vendor/themename/en_US/algoliaBundle.js

in actuality, algoliaBundle.min.js is included but in its own directory
/pub/static/frontend/vendor/themename/en_US/Algolia_AlgoliaSearch/internals/algoliaBundle.min.js

Any clue why this happens? Why is magento expecting to find algolia in the wrong directory?  Any help is appreciated.

**Comment by JanPetr** [comment]
Hello @ZayLong,

can you run `php bin/magento setup:static-content:deploy` when it happens?

**Comment by ZayLong** [comment]
yes, an that "fixes" it but it still periodically happens.

And still happens on the latest version of the magento 2 extension, tested
with 2.1.16
