### ISSUE TITLE
Is Algolia available for Magento 2 EE?

### ISSUE THREAD

**Issue by MagePsycho** [algolia/algoliasearch-magento-2#63]
Just wondering if Algolia is available for Magento 2 EE?

**Comment by JanPetr** [comment]
Hello @MagePsycho, yes, you can definitelly install the extension for EE. But there might occur some unexpected issues. If you run into some, feel free to open an issue with it.

**Comment by MagePsycho** [comment]
Reason I am asking this is Magento 2.1 EE introduced the concept of staging data. And now they are using `row_id` as main key in `catalog_product_entity` which needs special attention.

**Comment by JanPetr** [comment]
In that case we do not support `row_id` yet. But it's definitelly coming.

**Comment by MagePsycho** [comment]
Hi @JanPetr 
Any updates on AlgoliaSearch Extension compatibility for Magento 2 EE (2.1.x)?
We are ready to go live with Magento 2 EE and the extension compatibility issue is blocking us.

FYI, In Magento 2.1.0 EE, we are getting following error

> Column not found: 1054 Unknown column 'backend.entity_id' in 'field list'

while re-indexing, browsing category pages etc.
And the reason seems obvious as from Magento EE 2.1 on wards, entity_id -> row_id in order to support content staging feature.

Can you please share the ETA for Magento 2.1.x EE compatibility? 
I bet this is blocking many Magento 2EE shop owners from using awesome Algolia search.

**Comment by JanPetr** [comment]
Hello @MagePsycho,
the compatibility should be fixed in the latest release - [1.0.3](https://github.com/algolia/algoliasearch-magento-2/releases/tag/1.0.3). Can you update and confirm that the issue is fixed?
