### ISSUE TITLE
Mistake in example documentation

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#632]
On https://community.algolia.com/magento/doc/m2/frontend-events/ it says;

```
algolia.registerHook('beforeAutocompleteSources', function(sources, algoliaClient) {
	// modify default sources

	return sources;
});
```

This should also return the client;

```
algolia.registerHook('beforeAutocompleteSources', function(sources, algoliaClient) {
	// modify default sources

	return [sources, algoliaClient];
});
```

**Comment by peterjaap** [comment]
Also see #633

**Comment by JanPetr** [comment]
Actually it shouldn't @peterjaap. The code is ready to accept only sources, not an array of sources and client: https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/autocomplete.js#L84

**Comment by JanPetr** [comment]
But it looks like `sources` are not passed as they should be. I'll investigate a bit.

**Comment by peterjaap** [comment]
Ah you're right. #633 turned out to be the reason why I thought it wasn't working.
