### ISSUE TITLE
RequireJs Compatibility

### ISSUE THREAD

**Issue by DavidLambauer** [algolia/algoliasearch-magento-2#642]
Hi, I'm using the algoliasearch module with Magento 2.2.7. When hitting the route `catalogsearch/result/?q=QUERYSTRING` we receive the following JS Errors: 

```
Uncaught ReferenceError: requirejs is not defined at common.min.js:4
Uncaught ReferenceError: requirejs is not defined at instantsearch.min.js:1
Uncaught ReferenceError: requirejs is not defined at autocomplete.min.js:1
```

I had a look at the code and it seems, that the JS files are not imported correctly. Currently, all the algolia js files are imported via: 

```
...
        <script src="Algolia_AlgoliaSearch::internals/common.js"/>

        <script src="Algolia_AlgoliaSearch::instantsearch.js"/>
        <script src="Algolia_AlgoliaSearch::autocomplete.js"/>
...
```

Therefore, there is no dependency management through requirejs and it can happen that the requirejs object is not initiated at the time, the algolia modules is loaded.

Would it be possible to follow the Magento Guidelines https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_init.html ?

**Comment by simonmaass** [comment]
any news here? this is pretty important, as the complete search page isnt working!

**Comment by JanPetr** [comment]
Hello @simonmaass,

thank you for the report! Indeed we included the files as you mentioned and we use requireJs which is injected by Magento. 
Do you have a way how to reproduce the issue? Do you use any custom theme which doesn't include requireJS? I'm not able to reproduce locally.

Thank you!

**Comment by DavidLambauer** [comment]
Unfortunately, it is pretty hard to reproduce. IMHO it's a general issue that can occur depending on the use of other modules. This module assumes, that requireJs is loaded during the module execution. Depending on the use of additional modules, it is possible that requireJs is not loaded at the time of execution. 

Would it be possible to include the algoliasearch scripts via requireJs as well? I guess this would solve the issue and prevents future dependency issues.

**Comment by peterjaap** [comment]
^ yes please.

**Comment by jellesiderius** [comment]
Any progress on this? Would be a really good improvement.

**Comment by bsuravech** [comment]
Hi everyone, 

We hear you on this subject. It's been something we've been investigating on how to better approach javascript within the extension. We did some changes the v2 release but we were not able to move to RequireJS at that time. This is something we want to focus on in the future. 

We've passed this feedback to our productboard. If you have any further feedback or suggestions, please feel free to send them over to [support@algolia.com](mailto:support@algolia.com) and let us know this is feedback for the Magento team. Thank you everyone!
