### ISSUE TITLE
Always indexing base image

### ISSUE THREAD

**Issue by SergioViteri** [algolia/algoliasearch-magento-2#643]
Hi,

when changing the "Type" in Algolia Search > Images > Type to "small image" or "thumbnail" it always indexes the base image instead of the selected one.

I am using magento 2.2.6  and algoliasearch-magento-2 1.9.0

Thank you.

**Comment by JanPetr** [comment]
Thank you for the report, @SergioViteri. We will investigate and come back to you.

**Comment by JanPetr** [comment]
Fixed, it'll be part of the next release 🎉

**Comment by SergioViteri** [comment]
¡good! :tada:
