### ISSUE TITLE
Replace categories page issue on 2.2.7

### ISSUE THREAD

**Issue by kerlama** [algolia/algoliasearch-magento-2#647]
Hi,

we are using module version 1.8.4 on Magento 2.2.7 and when we enable this feature:
![screenshot_14](https://user-images.githubusercontent.com/4161312/50476242-c208a880-09c7-11e9-9c6e-e0bd5b253aa6.jpg)

Our category pages goes blank, only toolbar is visible and that's it.

Do we have to adjust something or its bug ?

**Comment by kerlama** [comment]
So, as no one helped out I come with the solution myself.
The problem was that algolia did not indexed categories for products, entries were empty in algolia.

I checked the code and in getCoreCategories() function in CategoryHelper.php there is:

`$this->categoryCollection
            ->addIsActiveFilter()
            ->addAttributeToSelect('name')
            **->addAttributeToFilter('include_in_menu', '1')**
            ->addAttributeToFilter('level', ['gt' => 1]);`

include_in_menu is excess, at least in our case, because client setup doesn't include categories in the menu. 

I did not go any deeper in checking why this is relevant and need at all, but commenting this line out sorted our problem with replacing categories page set to **YES**

**Comment by JanPetr** [comment]
Hello @kerlama,

sorry for not coming back to you on this.
It's great to hear you figured it out. Indeed, the extension doesn't index categories, which are not supposed to be in menu by default. We'll consider creating a config directive for it.

I'm closing the issue now. Feel free to re-open if you have something to add. Thank you!
