### ISSUE TITLE
Module Not working filter price

### ISSUE THREAD

**Issue by wcladesh** [algolia/algoliasearch-magento-2#648]
Hello Team,

Thanks for developing this useful module.
I have installed this algoliasearch-magento-2 module version 1.9.0  with the composer in Magento ver. 2.2.4 ,it is successfully installed and working fine. But when we search products and apply price filter in left navigation section. It produces the following error

`Fatal error: Uncaught Error: Call to undefined method Algolia\AlgoliaSearch\Helper\Adapter\FiltersHelper::isSearch()`

We have fixed that issue by overriding your FiltersHelper class and define isSearch() in same class instead of calling this function from AdapterHelper class. Now it is working fine for me.

Please check this issue and fix it in next release so we can update it.

**Comment by damcou** [comment]
Hello @wcladesh , 

Thanks a lot for spotted this . 
You're right, it seems that we let a small bug during the refactoring of the feature.
I'll have a look ASAP.

Can you please confirm that the error is triggered [here](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Adapter/FiltersHelper.php#L107) ?

Thanks again.
Best regards.
Damien

**Comment by wcladesh** [comment]
Hello @damcou ,

Yes, same place issue is triggered.
below is the line where we were getting the issue.

`if (!$this->config->isInstantEnabled($storeId) && $this->isSearch()) {`

**Comment by damcou** [comment]
@wcladesh ,

I made a change (see the related PR).
Seems that we forgot to remove the call during the refactoring.
It is going be reviewed and if it's good, that will be part of the 1.9.1 release ASAP. 

Thanks again.
Best.
Damien

**Comment by wcladesh** [comment]
@damcou ,

Thanks a lot to update the code. I will keep an eye for release and update it.
