### ISSUE TITLE
Array must contain at least one element in /Configurable.php on line 22

### ISSUE THREAD

**Issue by trilokgupta** [algolia/algoliasearch-magento-2#650]
Hello

i have a problem when i do reindex:

Warning: min(): Array must contain at least one element in /magento2/vendor/algolia/algoliasearch-magento-2/Helper/Entity/Product/PriceManager/Configurable.php on line 22 in /home/www-data/magento2/vendor/magento/framework/App/ErrorHandler.php:61

Magento 2.2.6
Algolia 1.9.0

**Comment by JanPetr** [comment]
Thank you for raising the issue, @trilokgupta. It's been resolved in related PR^ and will be released soon 🚀
