### ISSUE TITLE
CMS Page Content exceeds limit

### ISSUE THREAD

**Issue by BrentRobert** [algolia/algoliasearch-magento-2#658]
**Bug: What is the current behavior?**
When the content of a CMS page exceeds 10KB the indexer throws an error resulting in all indexations of pages for the current store view failing.

**Bug: What is the expected behavior?**
Only the page with the content that's too big should stop indexing.

**Bug: What is the proposed solution?**
Truncate the content field or don't index the page. Or another solution?

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
M2.2.6, Module Version 1.8.3

**Comment by JanPetr** [comment]
Hello @BrentRobert,

thank you for the report.
This behavior is already implemented in the extension, but the hardcoded limit is 20kb in the extension. Currently, different Algolia plans has different limits and we cannot have it dynamic in the extension :/

We are aware of the downside and when we have a way how to set the correct limit for different plans, we will implement it. Thank you for understanding!
