### ISSUE TITLE
Algolia Instant Search doesn`t work on IE11

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#659]
**Bug: What is the current behavior?**

Algolia Instant search not rendered and error shows in console

SCRIPT1003: Expected ':'  common.js(556, 13)

**Bug: What is the expected behavior?**
Algolia Instant search should be work in IE 11, because this version in offical included to Magento 2 supported browser list: https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements_browsers.html 

**Bug: What is the proposed solution?**
Issue is related with routing  for Instant search pages (URLs are SEO-friendly) and it's implemented with ES6 specification and it's not supported in IE11. In this case -  shorter syntax for method definitions on objects initializers. So, need to restore IE11 support in JS files.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

- Magento 2.2.3-2.2.6
- AlgoliaSearch 1.9.0

**Comment by mnjongerius** [comment]
Hi @vmalyk , we found the same issue on IE11. I'm willing to look into fixing this myself, can you point me in the right direction?

**Comment by JanPetr** [comment]
Fixed in PR^ 🚀 
[Thank you](http://bit.ly/2KHTYV3) for the report, @vmalyk and @mnjongerius 💯

**Comment by robbertstevens** [comment]
@JanPetr when wil a new version release, so I can update the module?
