### ISSUE TITLE
All child SKUs shown since recent update

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#667]
**Do you want to request a *feature* or report a *bug*?**
I see it as a bug, some might see it as a feature

**Bug: What is the current behavior?**
Since a recent update (not sure which one, we just upgraded from 1.7.1 to 1.9.1) the autocomplete and instant search widgets show ALL child SKUs for a configurable product (instead of the SKU of the configurable product). While in some cases this may come in handy, we have products that may have dozens (or hundreds) of simple products. It will show ALL of these SKUs, borking the layout. Here's an example;

![image](https://user-images.githubusercontent.com/431360/51918786-7724eb00-23e2-11e9-8440-2d34b828d38f.png)

**Bug: What is the expected behavior?**
Expected behavior is that it shows the first SKU (which is the configurable products' SKU).

**Bug: What is the proposed solution?**
Or revert this, or add a configuration option so we can choose what Algolia will show.

We have temporarily circumvented it by adding this to `\Algolia\AlgoliaSearch\Helper\AlgoliaHelper::prepareRecords` right before casting the record:

```

            // We should only show the first SKU in the list for a configurable product
            // So if SKU is an array and contains more than 1 items, slice it!
            if (is_array($object['sku']) && count($object['sku']) > 1) {
                $object['skus'] = $object['sku'];
                $object['sku'] = array_slice($object['sku'], 0,1);
            }
```

Then we made 'skus' a searchable field in the index, so all configurables are still found by searching child SKU's.

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
Configuration entry under Products: "Show all child SKUs for configurable products in frontend: Yes/No". Yes will show all SKUs, No will show only configurable SKU.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
M 2.2.7 + Algolia 1.9.1

**Comment by JanPetr** [comment]
Hello @peterjaap,

thank you for the report!
Indeed, we changed behavior for SKUs in order to make a configurable product searchable by its children's SKUs. It has a weird side effect, that it display's the children SKUs as well.

I'll add it to our roadmap and we'll add a configuration directive in future versions.
Thank you for coming up with a workaround in a meantime :)

If you don't mind I'll close this issue. Feel free to re-open if you want to add something or just keep it open :) Thanks!

**Comment by peterjaap** [comment]
That'd be great :) :+1:

**Comment by damcou** [comment]
Hello @peterjaap ,

I'm currently having a look at our backlog and I found this issue.
Do you have any new insight about it ?

I made some tests on my side, the only way I can reproduce it is to use this syntax :

`{{{ sku }}}`

I'm not a Hogan expert but I managed to get a display which seems to correspond to what you want : 

```
{{#sku.0}}
  {{{ sku.0}}}
{{/sku.0}}
{{^sku.0}}
  {{{ sku }}}
{{/sku.0}}
```
I check if there's sku.0 , I know if the variable is an array this way. If it's an array, I display the first element, if it's not, I display the whole variable.

I would have added this to the extension, the fact is that we don't display natively the SKU in our listings (both autocomplete and instantsearch ones) . 

We can still add the configuration you suggested at indexing level... Meaning if the user don't want to index the children SKUs inside the parent, we can give him the opportunity to do so. 
But I'm not sure this would be really useful so I have to talk about this with the team.
What do you thing about it on your side ?

Thanks for spotting that in any case.

Best.
Damien

**Comment by damcou** [comment]
Hi @peterjaap ,
Just a quick follow-up on that issue.
I know that it has been a long time you opened it and it may not be an issue anymore on your side so I'll re-close the ticket but feel free to give it a try and reply/re-open it if needed.

Thanks again.
Damien
