### ISSUE TITLE
Customer group prices are always "0" for grouped products

### ISSUE THREAD

**Issue by eugene-shramko** [algolia/algoliasearch-magento-2#668]
Magento 2.3 EE
Algolia 1.9.1

1. Configure Algolia indexes to be updated on save ("System" -> "Index Management").
2. Configure Algolia to index customer group prices (set "Stores" -> "Configuration" -> "Algolia Search" -> "Advanced" -> "Enable Customer Groups" to "Yes").
3. Create one simple product with regular price set to "100".
4. Create another simple product with regular price set to "150".
5. Create a grouped product, select created simple products as the child products.
6. Check created grouped product data within Algolia indices. Check autocomplete results for grouped product.

**Expected result:**
All customer group prices for grouped product within Algolia indices correspond to Magento.
The price for grouped product in autocomplete correspond to Magento.

**Actual result:**
All customer group prices for grouped product within Algolia indices are "0".
The price for grouped product in autocomplete is "0".

**P.S.** Default prices for grouped product are calculated correctly.

**Comment by JanPetr** [comment]
Hello @eugene-shramko,

thank you for the report and I'm sorry for the late answer.
We took the reported issue back internally and we'll investigate soon and send an update here.

If you have more information or details, feel free to share it with us here, it'll help us to fix it. Thank you!

**Comment by JanPetr** [comment]
Fixed, it'll be part of the next release 🎉
