### ISSUE TITLE
Reindex "algolia_categories" Error

### ISSUE THREAD

**Issue by simonmaass** [algolia/algoliasearch-magento-2#673]
**Do you want to request a *feature* or report a *bug*?**
BUG

**Bug: What is the current behavior?**
If I reindex: `php bin/magento indexer:reindex algolia_categories`

i get `Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/magento2/vendor/algolia/algoliasearch-magento-2/Model/Indexer/Category.php on line 91`

![image](https://user-images.githubusercontent.com/32599710/52439656-67ad4c80-2b1c-11e9-8493-4122e14576f1.png)

**Bug: What is the expected behavior?**
indexer finishes successful

**Bug: What is the proposed solution?**
no idea... :(

Magento 2.3
php7.2
"name": "algolia/algoliasearch-magento-2",
"version": "1.9.1"

**Comment by mwr** [comment]
I just created a pull-request addressing this issue.
https://github.com/algolia/algoliasearch-magento-2/pull/681

**Comment by simonmaass** [comment]
the merged fix works
