### ISSUE TITLE
Autocomplete does not always display special prices

### ISSUE THREAD

**Issue by SilvanLaroo** [algolia/algoliasearch-magento-2#684]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**Bug: What is the current behavior?**
If we set a special price for a product, the special price is not shown. We set up Algolia Queue runner. If we disable this feature and do a full reindex, the prices are shown correctly. Also if a special price is set to a specific date, the special price is still shown after this date. We have to do a full reindex again to fix this issue.

**Bug: What is the expected behavior?**
If a product has a special price, show that special price within the given period.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.1.14, Algolia 1.8.4

**Comment by damcou** [comment]
Hello @SilvanLaroo ,

Thanks for reaching out.
If you activated the indexing queue, it can happen that the process takes some time or maybe the queue is not set up correctly. Here is some documentation about it : https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing-queue/

About the display of the special prices, we recently added a small fix in the version 1.9.1 : https://github.com/algolia/algoliasearch-magento-2/commit/f7e8431b21b9c0a2b8c7f6841f1115106f85b77f
Would it be possible for you to update the extension and see if the problem persists ?

You also have to make sure that the special_from_date and special_to_date (coming from the product configuration in Magento) are indexed in the price objects in your Algolia indices.

Thanks in advance.
Best.
Damien

**Comment by JanPetr** [comment]
Hello @SilvanLaroo, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue, feel free to respond and re-open the issue. Thank you!
