### ISSUE TITLE
Instant search result settings are indexed, even when inactive

### ISSUE THREAD

**Issue by lykciv** [algolia/algoliasearch-magento-2#685]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
The sorting strategies for the instant search results page are always indexed. Even when the instant search results page is disabled. 

**Bug: What is the expected behavior?**
As noted on the documentation: "Each sorting strategy will create a new index, which will increase the amount of records."
If the instant search results page is disabled, I expect that the underlying (default) configuration is ignored. Right now, this is creating a huge amount of records which are never used.

**Bug: What is the proposed solution?**
Check if the instant search results page is enabled, before indexing the sorting strategies.

**Relevant documentation**
https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing/?language=php#sorting-strategies 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento: 2.2.7
Algolia: 1.8.4

**Comment by damcou** [comment]
Hello @lykciv ,

Thanks for reaching out.
You're right, the replicas relative to the sortings are created even if Instant Search is activated.
We will have a look at it ASAP.
In the meanwhile, if you don't want them to be created, you can temporary reactivate instantsearch, remove the 3 sortings, save the configuration, then turn off instantsearch again and resave the configuration.

The replicas won't be created anymore (but you will still have to delete them in your Algolia dashboard). 

We will keep you updated on this.
Thanks again.
Best.
Damien

**Comment by JanPetr** [comment]
Fixed in https://github.com/algolia/algoliasearch-magento-2/pull/694, will be part of the next release 🙌 Thank you for the report, @lykciv 💯
