### ISSUE TITLE
Topsearch not working perfectly

### ISSUE THREAD

**Issue by jagdishdots** [algolia/algoliasearch-magento-2#699]
I have set up a multi-website website in Magento 2.2.6 and Also installed the Algolia search. In search input when I  used a test like "Mug"  or any keyword and press the enter key from the keyboard it redirects to 404 page for one store only. search enter is working fine for other websites.

Redirect URL : p/catalogsearch/result/?q=mug

I have debugged but didn't find why it is adding p keyword in URL and remove the store name from URL.

**Comment by bsuravech** [comment]
Hi @jagdishdots,

Can you confirm for us what your baseURL is for this store? Is there a live example that we can take a look at to debug the issue? 

Thanks!

**Comment by jagdishdots** [comment]
Hi Please see the URL.
https://paladone.tcmarketing.co.uk/ukb2b/

try to search with top search

**Comment by jagdishdots** [comment]
any solution?

**Comment by bsuravech** [comment]
Hi @jagdishdots,

I can confirm that your autocomplete form has the correct result URL:

https://paladone.tcmarketing.co.uk/ukb2b/catalogsearch/result/

This should be submitting to the store specific catalogsearch result page. Our extension does not handle redirects. 

Has there been any customisations in regards to Magento's default catalogsearch or to redirects on your site? When I go to this link:
https://paladone.tcmarketing.co.uk/ukb2b/catalogsearch/result/?q=red

I see that the URL after load gets updated to: 
https://paladone.tcmarketing.co.uk/ukb2b/catalogsearch/result/index/?p=2&q=red

Which is not default for our extension. Perhaps this what is modifying your URL?

**Comment by JanPetr** [comment]
Hello @jagdishdots, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue, feel free to respond and re-open the issue. Thank you!
