### ISSUE TITLE
"Add to cart" translation not working in Algolia Instant Search Page

### ISSUE THREAD

**Issue by aboutzahurul** [algolia/algoliasearch-magento-2#701]
We are unable to translate "Add to cart" text in Algolia Instant Search Page

### Preconditions
1. Magento CE 2.1.9 with sample product, Multi language en_US and ar_SA
2. algolia/algoliasearch-magento-2 1.10.0 installed by composer (you will need algolia account to config the module)
3. On i18n en_US.csv translated to ar_SA.csv

### Expected result
"Add to cart" text should translated as in AR csv on Algolia Instant Search Page

### Actual result
"Add to cart" text didn't translated

### Solution
on file 'vendor/algolia/algoliasearch-magento-2/view/frontend/templates/instant/hit.phtml' line 71 "Add to cart" text didn't added to translation.

replace line 71 code by below code.
```
<span><?php echo __('Add to Cart') ?></span>
```
Note: Its not recommenced to replace original module file cos change may lost in future update. for this you may follow the link "https://www.algolia.com/doc/integration/magento-2/guides/create-a-custom-extension/" to know how to override algolia magento 2 module 

@algolia:  Please fix it on next version.

**Comment by bsuravech** [comment]
Hi @aboutzahurul,

Good catch! We have created a PR #702 to address this issue. You can take a look at it and patch accordingly. Once approved, it will be included for our next release. Thanks!

**Comment by aboutzahurul** [comment]
Hi @bsuravech,

We were also finding difficulties to translate the text "Show more products" when turning on the infinite scroll for Algolia Instant Search Page. After long search we got the text on "https://github.com/algolia/algoliasearch-magento-2/blob/master/Block/Configuration.php" under line number 229. This text also not added on en_US.csv. I just manually added the text on csv and working file. Please regenerate the translation text and solve the issue also on next release. Thanks!

**Comment by aboutzahurul** [comment]
> Hi @aboutzahurul,
> 
> Good catch! We have created a PR #702 to address this issue. You can take a look at it and patch accordingly. Once approved, it will be included for our next release. Thanks!



> We are unable to translate "Add to cart" text in Algolia Instant Search Page
> 
> ### Preconditions
> 1. Magento CE 2.1.9 with sample product, Multi language en_US and ar_SA
> 2. algolia/algoliasearch-magento-2 1.10.0 installed by composer (you will need algolia account to config the module)
> 3. On i18n en_US.csv translated to ar_SA.csv
> 
> ### Expected result
> "Add to cart" text should translated as in AR csv on Algolia Instant Search Page
> 
> ### Actual result
> "Add to cart" text didn't translated
> 
> ### Solution
> on file 'vendor/algolia/algoliasearch-magento-2/view/frontend/templates/instant/hit.phtml' line 71 "Add to cart" text didn't added to translation.
> 
> replace line 71 code by below code.
> 
> ```
> <span><?php echo __('Add to Cart') ?></span>
> ```
> Note: Its not recommenced to replace original module file cos change may lost in future update. for this you may follow the link "https://www.algolia.com/doc/integration/magento-2/guides/create-a-custom-extension/" to know how to override algolia magento 2 module
> 
> @algolia: Please fix it on next version.

You also need to translate the title text of button on line 70 from file "https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/templates/instant/hit.phtml"

replace line 70 code by below code.
```
<button type="submit" title="<?php echo __('Add to Cart') ?>" class="action tocart primary" data-objectid="{{objectID}}" data-position="{{__position}}">
```
Thanks!

**Comment by bsuravech** [comment]
Hi @aboutzahurul 

Title text was already added. As for the en_US.csv file, thanks for letting us know about the "Shore more products" string! That has been updated! 

Thanks!

**Comment by aboutzahurul** [comment]
Hi,

How can we translate some text on javascript file? For example: on file "https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/internals/algoliaBundle.min.js" how can we translate the text "Clear the search query" in different language?

Thanks!

**Comment by bsuravech** [comment]
Whoops, I have hot fingers. 

@aboutzahurul I don't have a quick solution for you yet on translating text from the algoliaBundle.min.js file, however, if you have a suggestion or see another translation issue as you are working towards translating the Algolia extension, please feel free to submit a PR here for us! You're really good at tracking these down and we highly encourage contributions from our community! 

I'll follow up here once I know more about what we can do in our bundle. Thanks!

**Comment by JanPetr** [comment]
Hello @aboutzahurul,

the translation of reset title "Clear the search query" is a bit tricky, but can be done. You need to implement [`beforeWidgetInitialization` JS custom hook](https://www.algolia.com/doc/integration/magento-2/customize/custom-front-end-events/?language=php#instant-search-page-events) and change the template of ["reset" cross](https://community.algolia.com/instantsearch.js/v2/widgets/searchBox.html#struct-SearchBoxResetOption).

The code could look like this:
```js
algolia.registerHook('beforeWidgetInitialization', function(allWidgetConfiguration) {
	allWidgetConfiguration['searchBox']['reset'] = {
		template: `
			<button type="reset" title="**TRANSLATED_TITLE**" class="ais-search-box--reset">
			  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="100%" height="100%">
			    <path d="M8.114 10L.944 2.83 0 1.885 1.886 0l.943.943L10 8.113l7.17-7.17.944-.943L20 1.886l-.943.943-7.17 7.17 7.17 7.17.943.944L18.114 20l-.943-.943-7.17-7.17-7.17 7.17-.944.943L0 18.114l.943-.943L8.113 10z" fill-rule="evenodd">
			    </path>
			  </svg>
			</button>`
	};
	
	return allWidgetConfiguration;
});
```

Let me know how it works for you 🚀
