### ISSUE TITLE
"Reindex products" not adding products to queue runner

### ISSUE THREAD

**Issue by QuentinFarizonAfrimarket** [algolia/algoliasearch-magento-2#715]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**Bug: What is the current behavior?**
Prerequisites :
- Queue runneris activated
- Queue is empty
- Database table `algoliasearch_queue` is empty

Run :
web@qs5o4mezk2kmpt73g5bxeggzye:~$ bin/magento indexer:reindex algolia_products
Algolia Search Products index has been rebuilt successfully in 00:00:01

But nothing is added to the database table `algoliasearch_queue` and the back-office lists 0 queued indexing jobs.

**Bug: What is the expected behavior?**
Products should be added to the indexing jobs, queue should be full

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento version : 2.2.7 EE
Algolia version : 1.10.0

**Comment by damcou** [comment]
Hello there,

The behaviour you describe seems to be the behaviour of the extension when the indexing queue is not activated.

Could you please run the following SQL request to be sure that the indexing queue is activated on each store / website ? : 

`select * from core_config_data where path = "algoliasearch_queue/queue/active";`

Thanks in advance.
Best.
Damien

**Comment by QuentinFarizonAfrimarket** [comment]
It is though :
```
MariaDB [main]> select * from core_config_data where path = "algoliasearch_queue/queue/active";
+-----------+---------+----------+----------------------------------+-------+
| config_id | scope   | scope_id | path                             | value |
+-----------+---------+----------+----------------------------------+-------+
|      1593 | default |        0 | algoliasearch_queue/queue/active | 1     |
+-----------+---------+----------+----------------------------------+-------+
1 row in set (0.01 sec)
```

**Comment by QuentinFarizonAfrimarket** [comment]
@julienbourdeau What do you think about that issue ? 

Thanks !
Quentin

**Comment by bsuravech** [comment]
@QuentinFarizonAfrimarket Thanks for following up. Are there any errors being reported to the logs when you run the reindex for products?

**Comment by QuentinFarizonAfrimarket** [comment]
Hello @bsuravech,
In which logs should I search ? Here I'm running the indexation from the command line.

**Comment by bsuravech** [comment]
@QuentinFarizonAfrimarket I'd tail var/log/system.log while you are running it in case there were errors. Thanks!

**Comment by QuentinFarizonAfrimarket** [comment]
@bsuravech Nothing in var/log/system.log, var/log/debug.log, var/log/exception.log, var/log/support_report.log ...

I can give you ssh access to this test environment if you want.

**Comment by QuentinFarizonAfrimarket** [comment]
Up please.
We are in the process to upgrade to from magento 2.1 to 2.2, so we're forced to migrate Algolia from 1.6.0 to an upper version, and none of the tested version above the one we now is working.

**Comment by QuentinFarizonAfrimarket** [comment]
I've found the issue, algoliasearch_credentials/credentials/enable_backend was set to 0 and this configuration is checked for indexation.
What is this setting ? 

I see in the upgrade script that it is supposed to be set at 1 by default if not set, but maybe I first installed a previous version that set it to 0.

**Comment by JanPetr** [comment]
Hello @QuentinFarizonAfrimarket,

yes, it should be set to 1. Otherwise it disables indexing completely. Does it fix your issue?

(I'm closing the issue now, feel free to re-open if you still experience the issue)

**Comment by QuentinFarizonAfrimarket** [comment]
@JanPetr yes, it fixed our issue.
But I think you should investigate if migrations are correctly applying this value ; if not, other people will stumble onto this.
