### ISSUE TITLE
Indexer: Rules quota exceeded

### ISSUE THREAD

**Issue by danemacmillan** [algolia/algoliasearch-magento-2#716]
When running the Magento2 Algolia indexers from the command line, the `algolia_products` and `algolia_categories` indexers fail to run, and state that a "Rules quota exceeded."

```
Algolia Search Products indexer process unknown error:
Rules quota exceeded. Please contact us if you need an extended quota.
Algolia Search Categories indexer process unknown error:
Rules quota exceeded. Please contact us if you need an extended quota.
Algolia Search Pages index has been rebuilt successfully in 00:00:00
```

![](https://i.imgur.com/zXpXcLV.png)

According to my paid account, this should not be an issue.

**Comment by 0livier** [comment]
Hi!
If you running 1.9.0+, the way to contact the support team is through the _Support page_ within the Algolia section of your Magento admin pages or by sending a mail to support+magento@algolia.com with your APP_ID.
Best regards,

**Comment by bsuravech** [comment]
This has been submitted to the support inbox and will be followed up there. Thanks!
