### ISSUE TITLE
Enterprise category indexing has an incorrect path

### ISSUE THREAD

**Issue by supachris28** [algolia/algoliasearch-magento-2#719]
**Bug: What is the current behavior?**
When indexing categories, the path is constructed with an incorrect name of Web Development / 2D Game Development:
![image](https://user-images.githubusercontent.com/20416049/54741690-2007ef00-4bb7-11e9-9a3a-e54f48711a88.png)

**Bug: What is the expected behavior?**
The Path should be Web Development / Front End Web Development

The categories are configured correctly:
![image](https://user-images.githubusercontent.com/20416049/54741702-28f8c080-4bb7-11e9-8309-a2cf15b48023.png)

**Bug: What is the proposed solution?**
Looking in the database we can see the entity and row IDs for this category path:
![image](https://user-images.githubusercontent.com/20416049/54741710-2eeea180-4bb7-11e9-86c3-2b76dbd03097.png)

And then the entities and their names:
![image](https://user-images.githubusercontent.com/20416049/54741723-36ae4600-4bb7-11e9-88ae-d3ae539d157a.png)

We can see that the entity_id 6672 in the catalog_category_entity table has been incorrectly matched with row_id 6672 in the catalog_category_entity_varchar table.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.6 EE (Cloud)
Algolia 1.10.0

**Comment by bsuravech** [comment]
Hi @supachris28, 

Thank you for reporting and the screenshots! We will investigate and will get back to you once we know more. Thanks!

**Comment by damcou** [comment]
Hello there,

This issue should now be resolved with the latest fixes.
Feel free to reopen it if you have more questions.

Best.
