### ISSUE TITLE
AlgoliaHelper constructor very slow due to getMagentoVersion()

### ISSUE THREAD

**Issue by QuentinFarizonAfrimarket** [algolia/algoliasearch-magento-2#723]
**Do you want to request a *feature* or report a *bug*?**
Performance issue

**What is the current behavior?**
The AlgoliaHelper is instatiated at many places.
There is a performance issue in his constructor due to call to ConfigHelper::getMagentoVersion(), due to the fact that Magento's ProductMetadataInterface::getVersion() itself has very poor performances.

This is due to it loading the composer.json file from disk, parsing it, and linting it (see screenshots below)
On my test environment, it took up to a 1 second. Granted, it may take less on production, but it will still be too much.

**Bug: What is the proposed solution?**
I didn't find an alternative way to get the Magento version/edition ...
Do you really need to get this information on every call to your service ?

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento : tested on 2.1.13 and 2.2.7

![Screenshot from 2019-03-22 15-04-46](https://user-images.githubusercontent.com/33634848/54828299-25972f00-4cb4-11e9-9f3e-cd72566c48c3.png)

**Comment by bsuravech** [comment]
Hi @QuentinFarizonAfrimarket,

Thanks for reporting the performance concern here. The reason why we're retrieving the Magento version is to support Magento Commerce (EE) specific features while being compatible with the Open Source (Community) edition. 

We will take a look further at how to optimise this and will get back to you once we learn more.

**Comment by QuentinFarizonAfrimarket** [comment]
Hello Betty,
Thanks for you quick return !
If you want ideas on how to check if customer is in Edition mode, here is an idea : you could check the version (in database setup_module table) of a module only installed in Enterprise edition, like `Magento_CatalogStaging`

**Comment by bsuravech** [comment]
Hey @QuentinFarizonAfrimarket,

Currently, we cannot make any further improvements as we need the version value for support purposes. However, Magento has already done a good job with caching the version value in memory. It should only process the file once. 

If you yourself have any ideas on how to further optimise this, please feel free to submit a PR. Perhaps make a suggestion to the Magento 2 community as well! 

Best, 

Betty

**Comment by QuentinFarizonAfrimarket** [comment]
Hello @bsuravech 
In which version did Magento start caching the version ?

**Comment by QuentinFarizonAfrimarket** [comment]
It isn't cached in current latest branch 2.3-develop : https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/App/ProductMetadata.php#L62

**Comment by everettgreen** [comment]
We're having the same issue. @bsuravech - could you clarify where this is cached? Thank you!
