### ISSUE TITLE
Expose algoliaBundle libraries in instantsearch.js

### ISSUE THREAD

**Issue by danemacmillan** [algolia/algoliasearch-magento-2#724]
The `algoliaBundle` in [`instantsearch.js`](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/instantsearch.js#L2) provides a tonne of powerful functionality that is completely inaccessible to anyone wanting to make significant modifications to the InstantSearch experience.

For example, when I wanted to modify both the [`pagination`](https://community.algolia.com/instantsearch.js/v2/widgets/pagination.html) and [`sortBySelector`](https://community.algolia.com/instantsearch.js/v2/widgets/sortBySelector.html) widgets, which don't offer template customizations, I had to code workarounds that effectively kept the original widgets in play on the page, but hidden away from the end user, and created new widgets that were a hybrid between them and the new ones. Thankfully the [`algoliasearch-helper-js`](https://github.com/algolia/algoliasearch-helper-js) library is available to custom widgets, but it's really not enough.

Had the `algoliaBundle` been exposed via a `algolia.triggerHooks`, similar to how [`autocomplete.js`](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/autocomplete.js#L84) exposes it, then I would have access to Algolia's InstantSearch [Connectors](https://community.algolia.com/instantsearch.js/v2/connectors.html) via `algoliaBundle.instantsearch.connectors`, which are immensely powerful, and the core logic building blocks to widgets. That would have allowed me to get all the relevant data for the type of customizations I wanted to develop, by creating new widgets based on custom `connectPagination` and `connectSortBySelector` connectors.

**Comment by bsuravech** [comment]
Hey @danemacmillan,

This is really great feedback! We created a PR linked to this issue. Feel free to take a look at it. If you have any further suggestions for improvements let us know and feel free to submit a PR as well!

**Comment by JanPetr** [comment]
Thank you for the awesome feedback, @danemacmillan 👍 It was added and it'll be part of the next release 🎉

**Comment by danemacmillan** [comment]
This is great to read. I probably won't be revisiting my Algolia integration for several more months, but when I do, this will likely be the first thing I refactor to use.
