### ISSUE TITLE
common.js error in iOS 9, 8 & 7 (untested below) causes termination of JS and causes Algolia search does not run

### ISSUE THREAD

**Issue by lornacodes** [algolia/algoliasearch-magento-2#735]
**Bug: What is the current behavior?**
In Safari/Chrome on iOS 9, 8 & 7 

Javascript errors with "SyntaxError: Expected an identifier but found 'location' instead" at line  560 in algoliasearch-magento-2/view/frontend/web/internals/common.js

If you have any javascript on page, because (I believe) iOS terminates JS on error, no other JS will run. Algolia search will not load either.

**Bug: What is the expected behavior?**

There should not be a syntax error in the JS.

Perhaps the earlier versions of iOS are no longer supported but for such a simple fix, it would be bizarre not to include this.

**Bug: What is the proposed solution?**
algoliasearch-magento-2/view/frontend/web/internals/common.js

Change 'let' keywords to 'var' for now as support is still (relatively) new and it is _only_ this file that uses this. 

Having changed this in my own core code, I can confirm it works.

See [https://www.w3schools.com/js/js_let.asp](https://www.w3schools.com/js/js_let.asp) for 'let' browser support.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.2.7, Algolia 1.10

**Comment by JanPetr** [comment]
Thank you for the report, @lornacodes 💯 I created a PR and it will be fixed in the next version 🙌
