### ISSUE TITLE
How would one use the `menuSelect` widget?

### ISSUE THREAD

**Issue by danemacmillan** [algolia/algoliasearch-magento-2#737]
In looking at the [example in the M2 docs](https://www.algolia.com/doc/integration/magento-2/customize/custom-front-end-events/), it should be as straightforward as replacing `"toggle"` with `"menuSelect"`, and then using the relevant [object options for the `menuSelect` widget](https://community.algolia.com/instantsearch.js/v2/widgets/menuSelect.html). I've done this, and the widget renders on the page, but there are no options besides a generic "See all" text. I've set the `attributeName` to the one desired, and I know it has data, but the options in the select are not populated. What am I missing? This is what the code looks like:

```js
algolia.registerHook('beforeWidgetInitialization', function(widgetInitializationData) {
    var wrapper = document.getElementById('instant-search-facets-container');

    var widgetConfig = {
        container: wrapper.appendChild(createISWidgetContainer('principal_category')),
        attributeName: 'principal_category',
        limit: 20,
        templates: {
            header: '<div class="name">Departments</div>',
            item: '<option>{{label}}:{{value}}</option>'
        },
        autoHideContainer: false
    };

    if (typeof widgetInitializationData['menuSelect'] === 'undefined') {
        widgetInitializationData['menuSelect'] = [widgetConfig];
    } else {
        widgetInitializationData['menuSelect'].push(widgetConfig);
    }

    return widgetInitializationData;
});
```

The same option-less widget renders regardless of `templates.item` being set.

**Comment by JanPetr** [comment]
Hello @danemacmillan,

do you have `principal_category` attribute set as attribute for faceting? If not, set it like that and it should work :)
