### ISSUE TITLE
Range slider for price does not always show currency symbol

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#742]
The range slider shows the price ranges twice for some reason. Here's a screenshot;

![image](https://user-images.githubusercontent.com/431360/55320022-79ed9c00-5476-11e9-8f6f-fcc0be17fcd3.png)

The top prices do have a currency symbol, but the bottom prices don't.

For now we hide them by using this css;

```
.is-widget-container-price_EUR_default .ais-range-slider--marker-large, .is-widget-container-price_EUR_default .ais-range-slider--value {
    display:none;
}
```

![image](https://user-images.githubusercontent.com/431360/55320105-abfefe00-5476-11e9-8e2e-ad03d858ef3f.png)

**Comment by damcou** [comment]
Hello @peterjaap ,

Thanks for reaching out.
I had a look at the rangeSlider component from our js library : https://www.algolia.com/doc/api-reference/widgets/range-slider/js/?language=js#connector

Looks like what we call "pips" are meant to be displayed this way as you can see here : https://instantsearchjs.netlify.com/stories/?path=/story/rangeslider--default

Unfortunately, I don't think it's possible to add the currency on the pips (I guess they are only used as "points of reference") but you can remove them setting "pips:false". 

Hope that helps.
Best.
Damien

**Comment by peterjaap** [comment]
@damcou thanks, where would I place that `pips:false` exactly?

**Comment by damcou** [comment]
Should be there in the extension : https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/instantsearch.js#L458

I guess it should be also doable using the beforeWidgetInitialization hook.
