### ISSUE TITLE
How would one observe autocomplete events?

### ISSUE THREAD

**Issue by danemacmillan** [algolia/algoliasearch-magento-2#745]
According to the [autocomplete.js documention](https://github.com/algolia/autocomplete.js#events), it's as simple as binding to the element that is targeted for autocomplete, because "[a]ll custom events are triggered on the element initialized as the autocomplete. In the case of the Magento2 integration, that occurs at https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/autocomplete.js#L100, and `$(this)` refers to the selector defined in the admin and exposed via the `algoliaConfig.autocomplete.selector` config; in my case, this refers to the DOM node, `#search`.

Observing any of the events simply does not work.

I've tried every node possible. I've observed the parent of the specified node, as is indicated in the source referenced, and I've tried on the various node IDs and classes that appear on the page. According to the documentation it really should be as simple as binding to the DOM node that is enhanced with this autocomplete functionality.

Given that this does not work, I'm going to say that the autocomplete.js documentation itself is wrong.

Regardless, I can see clearly why this does not work, so this ultimately is my suggestion: register an algolia hook after the autocomplete instance has been instantiated, and provide that instance, because it's the only thing that accepts the `.on()` method.

Change the code [from this](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/autocomplete.js#L100), to below:

```js
var algoliaAutocompleteInstance = $(this).autocomplete(options, sources);
algoliaAutocompleteInstance = algolia.triggerHooks('afterAutocompleteStart', algoliaAutocompleteInstance);

algoliaAutocompleteInstance
    .parent()
    .attr('id', 'algolia-autocomplete-tt')
    .on('autocomplete:updated', function (e) {
        fixAutocompleteCssSticky(menu);
    })
    .on('autocomplete:updated', function (e) {
        fixAutocompleteCssHeight(menu);
    }).on('autocomplete:selected', function (e, suggestion, dataset) {
        location.assign(suggestion.url);
    });
```

Then whitelist the new `afterAutocompleteStart` hook in [common.js](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/internals/common.js#L2).

This means that end users who want to actually observe the [events listed](https://github.com/algolia/autocomplete.js#events) can do so like:

```js
algolia.registerHook('afterAutocompleteStart', function(afterAutocompleteStart) {

    afterAutocompleteStart.on('autocomplete:updated', function(e) {
        console.log('updated!');
    });

    return afterAutocompleteStart;
});
```

This ticket is really low-hanging fruit for anyone who wants an easy PR.

**Comment by damcou** [comment]
Hello @danemacmillan ,

Thanks a lot for your feedback and your investigations.
We tested your enhancement on our own and it seems fine.
A PR has been created and will be reviewed ASAP.

Thanks again.
Best.
Damien
