### ISSUE TITLE
Getting an 503 while Reindex SKU is running

### ISSUE THREAD

**Issue by thanura-bi** [algolia/algoliasearch-magento-2#748]
Hi,
When I run Algolia search re-index SKUs, it's throwing a 503 error on below call,
.../algolia_algoliasearch/reindex/save
I can see the actual error in Magento reports,

```
`{"0":"Warning: Illegal offset type in vendor\magento\framework\DataObject.php on line 76","1":
"#0 vendor\magento\framework\DataObject.php(76): Magento\\Framework\\App\\ErrorHandler->handler(2, 'Illegal offset ...', '\app\...', 76, Array)\n
 #1 [internal function]: Magento\\Framework\\DataObject->setData(Object(Magento\\Framework\\Phrase),Object(Magento\\Framework\\Message\\Collection))\n
 #2 vendor\magento\framework\Session\SessionManager.php(157): call_user_func_array(Array, Array)\n
 #3 generated\code\Magento\Framework\Message\Session\Proxy.php(103): Magento\\Framework\\Session\\SessionManager->__call('setData', Array)\n
 #4 vendor\magento\framework\Message\Manager.php(121): Magento\\Framework\\Message\\Session\\Proxy->__call('setData', Array)\n
 #5 vendor\magento\framework\Message\Manager.php(143): Magento\\Framework\\Message\\Manager->getMessages(false, Object(Magento\\Framework\\Phrase))\n
 #6 vendor\magento\framework\Message\Manager.php(315): Magento\\Framework\\Message\\Manager->addMessage(Object(Magento\\Framework\\Message\\Error), Object(Magento\\Framework\\Phrase))\n
 #7 vendor\algolia\algoliasearch-magento-2\Controller\Adminhtml\Reindex\Save.php(169): Magento\\Framework\\Message\\Manager->addErrorMessage(Object(Algolia\\AlgoliaSearch\\Exception\\ProductDisabledException), Object(Magento\\Framework\\Phrase))\n
 #8 vendor\algolia\algoliasearch-magento-2\Controller\Adminhtml\Reindex\Save.php(98): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save->checkAndReindex(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n
 #9 vendor\magento\framework\App\Action\Action.php(107): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save->execute()\n
 ...........
```

The issue is at,
vendor/algolia/algoliasearch-magento-2/Controller/Adminhtml/Reindex/Save.php
Line 160
`$this->messageManager->addErrorMessage(
                        $e,
                    __(
                        'The product "%1" (%2) is disabled in store "%3 / %4 / %5".',
                        [
                            $e->getProduct()->getName(),
                            $e->getProduct()->getSku(),
                            $websites[$stores[$e->getStoreId()]->getWebsiteId()]->getName(),
                            $storeGroup[$stores[$e->getStoreId()]->getStoreGroupId()]->getName(),
                            $stores[$e->getStoreId()]->getName(),
                        ]
                    )
                );`

Here addErrorMessage is expecting an String rather than an object. $e shouldn't be passed.

Regards,
Thanura

**Comment by bsuravech** [comment]
Hi @thanura-bi,

Thanks for reporting this! We have created a PR for this issue #749. You can review the changes and patch if you'd like. This will be included in the upcoming release. 

Thank you!

**Comment by thanura-bi** [comment]
Thanks! I have already created a patch for it for our M2 build. But I'll use yours in future if needed.
Regards
Thanura

**Comment by thanura-bi** [comment]
Hi,
Looks like still there's an issue thats not getting covered by the patch. This is when you try to re-index a SKU that doesn't exists,
`{"0":"Requested product doesn't exist","1":"
#0 \app\...\generated\code\Magento\Catalog\Model\ProductRepository\Interceptor.php(24): Magento\\Catalog\\Model\\ProductRepository->get('65566', false, NULL, false)\n
#1 \app\...\vendor\algolia\algoliasearch-magento-2\Controller\Adminhtml\Reindex\Save.php(93): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->get('65566')\n
#2 \app\...\vendor\magento\framework\App\Action\Action.php(107): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save->execute()\n
#3 \app\...\vendor\magento\module-backend\App\AbstractAction.php(235): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#4 \app\...\vendor\magento\framework\Interception\Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#5 \app\...\vendor\magento\framework\Interception\Interceptor.php(138): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor->___callParent('dispatch', Array)\n
#6 \app\...\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
#7 \app\...\vendor\magento\framework\Interception\Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n
#8 \app\...\app\code\Bss\ForceLogin\Plugin\OtherPage.php(95): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
#9 \app\...\vendor\magento\framework\Interception\Interceptor.php(135): Bss\\ForceLogin\\Plugin\\OtherPage->aroundDispatch(Object(Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n
#10 \app\...\vendor\magento\framework\Interception\Interceptor.php(153): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
#11 \app\...\generated\code\Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor.php(26): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor->___callPlugins('dispatch', Array, NULL)\n
#12 \app\...\vendor\magento\framework\App\FrontController.php(55): Algolia\\AlgoliaSearch\\Controller\\Adminhtml\\Reindex\\Save\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#13 \app\...\vendor\magento\framework\Interception\Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#14 \app\...\vendor\magento\framework\Interception\Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n
.....`

**Comment by thanura-bi** [comment]
I have a patch for this if anyone interested,
```
This patch fix algolia product SKU reindex issue
@package algolia/algoliasearch-magento-2
========================================================
--- Controller/Adminhtml/Reindex/Save.php	2019-04-10 16:48:20.000000000 +1000
+++ Save.php	2019-04-10 16:40:26.000000000 +1000
@@ -13,6 +13,7 @@
 use Magento\Catalog\Api\ProductRepositoryInterface;
 use Magento\Framework\Controller\ResultFactory;
 use Magento\Store\Model\StoreManagerInterface;
+use Magento\Framework\Exception\NoSuchEntityException;

 class Save extends \Magento\Backend\App\Action
 {
@@ -92,11 +93,11 @@
                 /** @var \Magento\Catalog\Model\Product $product */
                 $product = $this->productRepository->get($sku);
                 if (! $product->getId()) {
-                    throw new UnknownSkuException(__('Product with SKU "%1" was not found.', $sku));
+                    throw new NoSuchEntityException(__('Product with SKU "%1" was not found.', $sku));
                 }

                 $this->checkAndReindex($product, $stores);
-            } catch (UnknownSkuException $e) {
+            } catch (NoSuchEntityException $e) {
                 $this->messageManager->addExceptionMessage($e, $e->getMessage());
             } catch (ProductDeletedException $e) {
                 $this->messageManager->addExceptionMessage(
@@ -158,7 +158,6 @@
             } catch (ProductDisabledException $e) {
                 // Product status is a Website specific attribute
                 $this->messageManager->addErrorMessage(
-                    $e,
                     __(
                         'The product "%1" (%2) is disabled in store "%3 / %4 / %5".',
                         [
@@ -198,7 +197,6 @@
                     }
                 } else {
                     $this->messageManager->addErrorMessage(
-                        $e,
                         __(
                             'The product "%1" (%2) is not visible in store "%3 / %4 / %5".',
                             [
```

**Comment by bsuravech** [comment]
Hi @thanura-bi,

Thanks for the follow up and the catch! We updated the PR to add an addition exception catch for NoSuchEntityException that is thrown before our own UnknownSkuException. Thanks again for the assist and the patch!

**Comment by thanura-bi** [comment]
Welcome!! Cool
