### ISSUE TITLE
Instant Search results don't render on IE11

### ISSUE THREAD

**Issue by jeeshin** [algolia/algoliasearch-magento-2#751]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**Bug: What is the current behavior?**
1. Navigate to https://www.munchkin.com using Internet Explorer 11
2. Click on search icon at top-right of page (magnifying glass)
3. Search bar should appear. Type "duck" as search term and press Enter key (Note that auto-complete results show successfully)
4. Search results page should show results, however the Algolia block does not render and console errors appear:
```
SEC7118: XMLHttpRequest for https://rh1i0d3wu9-dsn.algolia.net/1/indexes/stg6_en_us_products/query?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.24.9%3BMagento2%20integration%20(1.7.0)&x-algolia-application-id=RH1I0D3WU9&x-algolia-api-key=YmRjM2RhYjlmODliMjlkYmYzYTRmMWNlNTZhODdiOTdlZjk1MGM1MDYyZmZmZDhjZTQ1NTI2MTg3YzlmMDI0MnRhZ0ZpbHRlcnM9 required Cross Origin Resource Sharing (CORS). 
File: result 
SEC7131: Security of a sandboxed iframe is potentially compromised by allowing script and same origin access. 
```
![algolia-instantsearch-ie11](https://user-images.githubusercontent.com/39323851/55825841-a1b6b280-5abb-11e9-8c27-370943001de8.png)

We can replicate this issue in both our production and development environments.

**Bug: What is the expected behavior?**
Instant search results should appear as they do on Chrome, Safari and Firefox.

**Bug: What is the proposed solution?**
None proposed.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento Commerce 2.3.1 and Algolia 1.10.0

**Comment by JanPetr** [comment]
Hello @jeeshin,

it seems it's caused by `X-Frame-Options: SAMEORIGIN` header your store is sending. It prevents IE11 to make a call to different domain API: https://stackoverflow.com/questions/14486461/iframe-sandbox-attribute-is-blocking-ajax-calls

Could you try to remove it and try again?
