### ISSUE TITLE
Magento 2.2.5 CE failed algolia_products reindex

### ISSUE THREAD

**Issue by dzls** [algolia/algoliasearch-magento-2#752]
**Do you want to request a feature or report a bug?**
Bug.

**Bug: What is the current behavior?**

When running bin/magento indexer:reindex algolia_products on Magento CE 2.2.5, reindex fails with SQL error message...

    Algolia Search Products indexer process unknown error:
    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_value.value' in 'field list', query was: SELECT `entity`.`sku`, `product_entity`.`entity_id` AS `product_id`, `attribute`.`attribute_code`, `entity_value`.`value` AS `value_index`, `attribute_label`.`value` AS `super_attribute_label`, IFNULL(option_value.value, default_option_value.value) AS `option_title`, `default_option_value`.`value` AS `default_title` FROM `catalog_product_super_attribute` AS `super_attribute`
    INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.entity_id = super_attribute.product_id
    INNER JOIN `catalog_product_super_link` AS `product_link` ON product_link.parent_id = super_attribute.product_id
    INNER JOIN `eav_attribute` AS `attribute` ON attribute.attribute_id = super_attribute.attribute_id
    INNER JOIN `catalog_product_entity` AS `entity` ON entity.entity_id = product_link.product_id
    INNER JOIN `catalog_product_entity` AS `entity_value` ON entity_value.attribute_id = super_attribute.attribute_id AND entity_value.store_id = 0 AND entity_value.entity_id = entity.entity_id
    LEFT JOIN `catalog_product_super_attribute_label` AS `attribute_label` ON super_attribute.product_super_attribute_id = attribute_label.product_super_attribute_id AND attribute_label.store_id = 0
    INNER JOIN `eav_attribute_option` AS `attribute_option` ON attribute_option.option_id = entity_value.value
    LEFT JOIN `eav_attribute_option_value` AS `option_value` ON option_value.option_id = entity_value.value AND option_value.store_id = 1
    LEFT JOIN `eav_attribute_option_value` AS `default_option_value` ON default_option_value.option_id = entity_value.value AND default_option_value.store_id = 0 WHERE (super_attribute.product_id = 237) AND (attribute.attribute_id = '') ORDER BY `attribute_option`.`sort_order` ASC

**Bug: What is the expected behavior?**
Algolia reindexes should run successfully.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento Community 2.2.5
Algolia Search Magento 2 version 1.10.0

**Comment by JanPetr** [comment]
Hello @dzls,

thank you for the report. I'll investigate and come back to you.
In a meantime, would you be able to share with us your Algolia configuration?

**Comment by JanPetr** [comment]
I was not able to reproduce the issue, @dzls. Your configuration would really help me on that. Thanks!

**Comment by dzls** [comment]
Hi @JanPetr.

Thanks for investigating the issue!

Here's the config set on core_config_data:

    INSERT INTO `core_config_data` (`config_id`, `scope`, `scope_id`, `path`, `value`) VALUES (NULL, 'default', '0', 'algoliasearch_credentials/credentials/enable_backend', '1'),
    (NULL, 'default', '0', 'algoliasearch_credentials/credentials/enable_frontend', '0'),
    (NULL, 'default', '0', 'algoliasearch_credentials/credentials/application_id', 'application_id'),
    (NULL, 'default', '0', 'algoliasearch_credentials/credentials/search_only_api_key', 'search_only_api_key'),
    (NULL, 'default', '0', 'algoliasearch_credentials/credentials/api_key', 'api_key'),
    (NULL, 'default', '0', 'algoliasearch_credentials/credentials/debug', '0'),
    (NULL, 'default', '0', 'algoliasearch_credentials/credentials/index_prefix', 'staging_magento2_'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/is_popup_enabled', '1'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/nb_of_products_suggestions', '6'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/nb_of_categories_suggestions', '2'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/nb_of_queries_suggestions', '0'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/min_popularity', '1000'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/min_number_of_results', '2'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/render_template_directives', '1'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/debug', '0'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/is_instant_enabled', '1'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/instant_selector', '.columns'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/number_product_results', '9'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/max_values_per_facet', '10'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/replace_categories', '1'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/show_suggestions_on_no_result_page', '1'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/add_to_cart_enable', '1'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/infinite_scroll_enable', '0'),
    (NULL, 'default', '0', 'algoliasearch_products/products/use_adaptive_image', '0'),
    (NULL, 'default', '0', 'algoliasearch_categories/categories/show_cats_not_included_in_navigation', '0'),
    (NULL, 'default', '0', 'algoliasearch_categories/categories/index_empty_categories', '0'),
    (NULL, 'default', '0', 'algoliasearch_images/image/width', '265'),
    (NULL, 'default', '0', 'algoliasearch_images/image/height', '265'),
    (NULL, 'default', '0', 'algoliasearch_images/image/type', 'image'),
    (NULL, 'default', '0', 'algoliasearch_queue/queue/active', '0'),
    (NULL, 'default', '0', 'algoliasearch_queue/queue/number_of_job_to_run', '5'),
    (NULL, 'default', '0', 'algoliasearch_queue/queue/number_of_retries', '3'),
    (NULL, 'default', '0', 'algoliasearch_cc_analytics/cc_analytics_group/enable', '0'),
    (NULL, 'default', '0', 'algoliasearch_cc_analytics/cc_analytics_group/is_selector', '.ais-hits--item a.result, .ais-infinite-hits--item a.result'),
    (NULL, 'default', '0', 'algoliasearch_cc_analytics/cc_analytics_group/enable_conversion_analytics', 'disabled'),
    (NULL, 'default', '0', 'algoliasearch_cc_analytics/cc_analytics_group/add_to_cart_selector', '.action.primary.tocart'),
    (NULL, 'default', '0', 'algoliasearch_analytics/analytics_group/enable', '0'),
    (NULL, 'default', '0', 'algoliasearch_analytics/analytics_group/delay', '3000'),
    (NULL, 'default', '0', 'algoliasearch_analytics/analytics_group/trigger_on_ui_interaction', '1'),
    (NULL, 'default', '0', 'algoliasearch_analytics/analytics_group/push_initial_search', '0'),
    (NULL, 'default', '0', 'algoliasearch_synonyms/synonyms_group/enable_synonyms', '0'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/number_of_element_by_page', '300'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/remove_words_if_no_result', 'allOptional'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/partial_update', '0'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/customer_groups_enable', '0'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/make_seo_request', '1'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/remove_branding', '0'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/autocomplete_selector', '.algolia-search-input'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/index_product_on_category_products_update', '1'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/prevent_backend_rendering', '0'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/prevent_backend_rendering_display_mode', 'all'),
    (NULL, 'default', '0', 'algoliasearch_advanced/advanced/backend_rendering_allowed_user_agents', 'Googlebot\nBingbot'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/sections', '[{\"name\":\"pages\",\"label\":\"Pages\",\"hitsPerPage\":\"2\"}]'),
    (NULL, 'default', '0', 'algoliasearch_autocomplete/autocomplete/excluded_pages', '[{\"attribute\":\"no-route\"}]'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/facets', '[{\"attribute\":\"price\",\"type\":\"slider\",\"label\":\"Price\",\"searchable\":\"2\",\"create_rule\":\"2\"},{\"attribute\":\"categories\",\"type\":\"conjunctive\",\"label\":\"Categories\",\"searchable\":\"2\",\"create_rule\":\"2\"},{\"attribute\":\"brand\",\"type\":\"disjunctive\",\"label\":\"Colors\",\"searchable\":\"1\",\"create_rule\":\"2\"}]'),
    (NULL, 'default', '0', 'algoliasearch_instant/instant/sorts', '[{\"attribute\":\"price\",\"sort\":\"asc\",\"sortLabel\":\"Lowest price\"},{\"attribute\":\"price\",\"sort\":\"desc\",\"sortLabel\":\"Highest price\"},{\"attribute\":\"created_at\",\"sort\":\"desc\",\"sortLabel\":\"Newest first\"}]'),
    (NULL, 'default', '0', 'algoliasearch_products/products/product_additional_attributes', '[{\"attribute\":\"name\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"sku\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"manufacturer\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"categories\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"color\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"price\",\"searchable\":\"2\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"rating_summary\",\"searchable\":\"2\",\"order\":\"unordered\",\"retrievable\":\"1\"}]'),
    (NULL, 'default', '0', 'algoliasearch_products/products/custom_ranking_product_attributes', '[{\"attribute\":\"in_stock\",\"order\":\"desc\"},{\"attribute\":\"ordered_qty\",\"order\":\"desc\"},{\"attribute\":\"created_at\",\"order\":\"desc\"}]'),
    (NULL, 'default', '0', 'algoliasearch_categories/categories/category_additional_attributes', '[{\"attribute\":\"name\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"path\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"meta_title\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"meta_keywords\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"meta_description\",\"searchable\":\"1\",\"order\":\"unordered\",\"retrievable\":\"1\"},{\"attribute\":\"product_count\",\"searchable\":\"2\",\"order\":\"unordered\",\"retrievable\":\"1\"}]'),
    (NULL, 'default', '0', 'algoliasearch_categories/categories/custom_ranking_category_attributes', '[{\"attribute\":\"product_count\",\"order\":\"desc\"}]');``

**Comment by damcou** [comment]
hello @dzls ,

Thanks for providing the configuration.
The error message on the first message seems to be relative to product with ID = 237, it is the same product each time ?

Could you try to index it with the [SKU reindexing form](https://www.algolia.com/doc/integration/magento-2/how-it-works/sku-reindexing-form/) (from the Algolia extension) to see if you have the same issue ? 

If you do, could you please try to figure out when does the error is triggered exactly ?

It will help us a lot to figure out what the issue can be.

Thanks in advance.
Best.

**Comment by dzls** [comment]
Hi @damcou 

Thank you for your reply.

The SKU reindexing form helped me realise that the issue is not related to the Algolia module, but the product itself. Also, I've found this solution https://magento.stackexchange.com/a/242170, and now the reindexes are running fine.

Thank you all for the help.

I'm now closing the ticket.
DZ
