### ISSUE TITLE
Translate attribute with custom source

### ISSUE THREAD

**Issue by VincentMarmiesse** [algolia/algoliasearch-magento-2#753]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure if this is a bug or a misconfiguration on my side.

**What is the current behavior?**
I have an attribute with a custom source which looks like this:

```
<?php
namespace Vendor\Catalog\Model\Product\Attribute\Source;

class EngineType extends \Magento\Eav\Model\Entity\Attribute\Source\AbstractSource
{
    const VALUE_ELECTRIC    = 'EL';
    const VALUE_GASOLINE    = 'ES';
    [...]

    const LABEL_ELECTRIC    = 'Electric';
    const LABEL_GASOLINE    = 'Gasoline';
    [...]

    /**
     * Retrieve All options
     *
     * @return array
     */
    public function getAllOptions()
    {
        if (!$this->_options) {
            $this->_options = [
                [
                    'value' => self::VALUE_ELECTRIC,
                    'label' => __(self::LABEL_ELECTRIC)
                ],
                [
                    'value' => self::VALUE_GASOLINE,
                    'label' => __(self::LABEL_GASOLINE)
                ],
                [...]
            ];
        }
        return $this->_options;
    }
}
```
Labels are not translated in Algolia while it's well translated in admin.

**What is the expected behavior?**
Labels should be translated in Algolia

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.3.1
Algolia 1.10.0

Should I configure something to have the labels translated in Algolia?

Thanks!

**Comment by JanPetr** [comment]
Hello @VincentMarmiesse,

thank you for your report!
The extension [fetches the value from the resource based on the Store ID](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L890-L891). And it looks like the resource is giving it in non-translated state.

Would you be able to update your resource to return translated version?
Or you can use [`algolia_after_create_product_object` event](https://www.algolia.com/doc/integration/magento-2/customize/custom-back-end-events/#products), write a listener and translate the attribute there.

Would any of those solutions work for you?
