### ISSUE TITLE
Category name change and data inconsistencies

### ISSUE THREAD

**Issue by username12212112** [algolia/algoliasearch-magento-2#758]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
1. Have categories, products and data synced to Algolia. Use Algolia to render Magento category pages
2. Go to Magento admin category and select a category with a number of products
3. Change the category name and save
4. Open category page on front-end of site
5. Page loads with no products or missing for a period of time (until affected products are reindexed)

**Bug: What is the expected behavior?**
On step 4 users should be able to load the category and see all products

**Bug: What is the proposed solution?**
This is caused due to the way Algolia fetches the products/ data for the category.
The POST that fetches the category data uses the category names in the Form Data request
`facetFilters: [["categories.level1:Kids /// PJ Sets test"]]` and because the name has changed in Magento and thus the POST value for facetFilters changes at the same time, whilst the category names need to be re-index to Algolia, we see inconsistencies.

A potential solution for this would be to filter by Magento category ID, as this is constant and will remove the inconsistency of missing products.
 
![Screen Shot 2019-04-18 at 2 10 39 pm](https://user-images.githubusercontent.com/44450887/56336489-fce75400-61e3-11e9-91df-acff28008ef5.png)

**Feature: What is your use case for such a feature?**

1. Anyone that uses Magento + Algolia and changes the name of any category.
2. Magento Admin needs to change the category name for a new sale
 

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
NA

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magneto Cloud 2.2.6
Algolia latest

**Comment by JanPetr** [comment]
Hello @username12212112,

thank you for the report! I create a PR this morning: #759 
Can you give it a try? Don't forget to have enabled "Update product on category products update" config option. It's in Algolia Search configuration, tab Advanced.

**Comment by bsuravech** [comment]
Hi @username12212112,

Following up here! We have introduce a few improvements to the category product indexing in our latest version. We also have a new PR #819 to be included in the next release that improves in further the conditions for updating products on category save. Please feel free to review and see if this helps with your issue. Thanks!

**Comment by bsuravech** [comment]
Hi @username12212112! We have incorporated these changes in our latest version. Please feel free to upgrade your extension to benefit from the updates! Thanks!
