### ISSUE TITLE
StockItemObserver don't reindex product when stock was decreased after shipping creation

### ISSUE THREAD

**Issue by Dzhus111** [algolia/algoliasearch-magento-2#773]
When magento decrease product stock after shipping creation, algolia has not add  this product for reindexing. In this case  StockItemObserver plugin is not worked. So if magento decrease product stock  to 0, the product still available on search results. 

Used magento 2.3.0 commerce with MSI functionality (used default  source) for products inventory.
Algolia latest

**Comment by damcou** [comment]
Hello @Dzhus111 ,

Thanks for your feedback.
You're right, the extension is not fully compatible with the 2.3 MSI functionality yet, we are aware of it and it's on our roadmap for the coming weeks.
Thanks for this insight, I'll add it to our notes on this topic.

Best regards.

**Comment by barzucristi** [comment]
Hello,

We are using Magento 2.3 with MSI and because of it most of the products are not indexed in Algolia. Can you please let us know if this issue has been resolved?

Looking forward to your reply,

**Comment by damcou** [comment]
Hello @barzucristi ,

We are currently finalizing the fix for this issue.
It should be available in the coming days.

Thanks for your patience.

**Comment by barzucristi** [comment]
Hello,

Thank you for your prompt reply!

Will wait on news from you.

Thank you for your help,

Cristi Birzu

**Comment by damcou** [comment]
Hello,

The additional module to download is available here : https://github.com/algolia/algoliasearch-inventory-magento-2/
Feel free to try it :) .
Keep in mind that you have to get the v1.12.1 of the extension to make it work.

Thanks again for your feedback.
Best.
Damien
