### ISSUE TITLE
How to Add Redirects on Search

### ISSUE THREAD

**Issue by sandeep570** [algolia/algoliasearch-magento-2#777]
Hey, guys, I need How to Add Redirects on Search. So using this link: https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/tutorials/how-to-add-redirects-on-search/#introduction I am unable to redirect so do you guys have any working snippet. Actually, in my code, it is not hitting the indices. 
My code written here is : `		const clientoptions = {
			appId: algoliaConfig.applicationId,
			apiKey: algoliaConfig.apiKey,
			indexName: algoliaConfig.indexName + '_searchterms'
			}
		var searchkey = algoliaBundle.instantsearch(clientoptions);		
		const index = searchkey.client.initIndex('EB_local_default_searchterms');
		const input = document.getElementById('search');
		input.addEventListener('keydown', ({ key }) => {
		  if (input.value === 'star wars') {
			console.log("val = "+input.value);
		    index.search(
		      '',
		      {	hitsPerPage: 1,
			facetFilters: [`query_terms:${input.value}`]
		      },
		      (err, { hits } = {}) => {
			if (hits.length > 0) {
			  window.location.href = hits[0].url;
			}
		      }
		    );
		  }
		});`

Could anyone please help me out what I am missing anything. **Algolia version: 1.7.2**

**Comment by bsuravech** [comment]
Hi @sandeep570,

Thanks for reaching out. Magento's default Search Terms redirect behaviour is respected in the Algolia Magento extension. You should be redirected if there is a search term that has a redirect URL once the search is submitted to catalogsearch/results. Let us know if that solution helps out or if we can further assist you with your custom redirection. Thanks!

**Comment by sandeep570** [comment]
Hi @bsuravech Thanks for the reply and sorry for the late reply from my side. I have completed this task using algolia provided sample code. So, I am closing this ticket.
