### ISSUE TITLE
Merchandising on category page ignores filtering by attributes

### ISSUE THREAD

**Issue by Dzhus111** [algolia/algoliasearch-magento-2#778]
I 'm not sure is this algolia magento module issue or some problems with configuration.
When some products was promoted by Algolia Merchandising on category page, these products will showed always in category page even filtering by some attribute (e.g color or brand) should  hide these products from the results. In my case, I have only one product with some filter value, but I see extra products that promoted by Algolia Merchandising on category page and they has no this filter value.

I expected that Algolia Merchandising should changes only products position for sorting by relevance and not ignores filtering.

Used Magento 2.3.1 commerce, category page replaced with algolia instant search result page, sorting by relevance
Algolia latest

**Comment by bsuravech** [comment]
Hi @Dzhus111, 

Thank you for your feedback regarding the promoted products and filtering. This is the current default behaviour of the merchandising feature to promote the product above the filtering. This was not intended for default sort ordering but I can see why there is confusion here. We have passed your feedback along for consideration for future improvements to the merchandising feature. Thanks!

**Comment by Dzhus111** [comment]
> Hi @Dzhus111,
> 
> Thank you for your feedback regarding the promoted products and filtering. This is the current default behaviour of the merchandising feature to promote the product above the filtering. This was not intended for default sort ordering but I can see why there is confusion here. We have passed your feedback along for consideration for future improvements to the merchandising feature. Thanks!

Hi bsuravech, I understand your comment, however, we have discussed this with our client Slater Menswear and we are due to launch in Autumn and we cannot use the Algolia merchandiser as it currently works. Whilst most categories we use are ordered by relevance and the Algolia ranking, we do heavily merchandise manually some top level categories based on every changing business requirements and if we use the functionality you made available to merchandise we will be impairing the use of filters for customers - e.g. I move a blue product top and when the user filters by Black will still see the Blue product - which will have a negative impact on sales.
As far we we see, we have 3 options here:
1. You make this functionality optional, so that we can turn it on and off in the CMS (ideal solution)
2. You tell us how we could amend the module code to ignore such query rules used for the VM when filters are applied by the user (not ideal but OK)
3. We disable the algolia merchandiser, re-enable the default Magento merchandiser and use it to  generate a custom index (this is what we did on Magento 1, but it’s a lot of work)
Can you please advise?

**Comment by damcou** [comment]
Hello there,

We are currently investigating this request and we'll working on it during the next year (I'm sorry I can't give you any precise ETA for it). We'll try to make the functionality optional and configurable inside the Magento back-office.

In the meantime, here's a workaround that you could use : 

You can try to use one of our js frontend events : beforeInstantsearchInit (https://www.algolia.com/doc/integration/magento-2/customize/custom-front-end-events/?language=php#instant-search-page-events)
The goal would be to try to clear the ruleContext which we set currently in Magento when you select a facet.
You can easily do this by adding a `searchFunction` and watching for refined facet values. You can review this gist as inspiration for what you have to do for this : https://gist.github.com/bsuravech/5fb154b94e88410cd1a5e96380d282c0
Then, as soon as you select a filter, the query rule is not applied anymore

Hope that help.
Feel free to reopen the issue if you have questions.
Best.
