### ISSUE TITLE
Magento 2.1.1, Instance search is not working.

### ISSUE THREAD

**Issue by shakeshah** [algolia/algoliasearch-magento-2#78]
HI, 
Please help me how i am gonna show, instance search, what the steps involve on it.
Thanks

**Comment by JanPetr** [comment]
Hello @shakeshah,
you need to enable instant search in configuration:
![screenshot 2016-09-29 10 01 52](https://cloud.githubusercontent.com/assets/1058144/18945643/c7ebf4ea-862b-11e6-8d8f-30ca6b4d1afd.png)
If you want to use only instant search feature without autocomplete (like on https://jadopado.com/), just disable autocomplete feature :)

**Comment by shakeshah** [comment]
I did,exactly the same, no luck with it :(

**Comment by JanPetr** [comment]
Can you see any error in your browser's console? Can you give me URL of your website?

**Comment by shakeshah** [comment]
I am working on my localhost, 
all cache are disabled, check the screens below please.
![2016-09-29_1219](https://cloud.githubusercontent.com/assets/5294498/18946257/20ecb9d6-863f-11e6-8e22-ddc9c7364a1f.png)
![2016-09-29_1222](https://cloud.githubusercontent.com/assets/5294498/18946309/5a29caa4-863f-11e6-8d13-81500e5bcc88.png)

**Comment by JanPetr** [comment]
You need to Enable search as well.

**Comment by shakeshah** [comment]
enable search, override my topsearch, and then no search box is showing
![2016-09-29_1231](https://cloud.githubusercontent.com/assets/5294498/18946597/a8c92ae6-8640-11e6-9f88-71e269e9016a.png)
,

**Comment by JanPetr** [comment]
And can you see any error now?

What you can do is to change default search box selector to match your original search box. In that case it should work just fine :) https://github.com/algolia/algoliasearch-magento-2/issues/77#issuecomment-250398548

**Comment by shakeshah** [comment]
i am getting now error Invalid instant-search selector: .algolia-search-input

**Comment by JanPetr** [comment]
It seems like it cannot render top search block with the new search box.
Can you try to change selector to you default search box?

**Comment by shakeshah** [comment]
i know, the algolia top search is not rendering, i try with my default search, nothing happens. :(

**Comment by JanPetr** [comment]
Hello @shakeshah,
I'm sorry for not being responsive here :( Did you manage to make it work? Or are you still struggling? Can I still help you in any way?
