### ISSUE TITLE
Indexing error: call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by razvan-f** [algolia/algoliasearch-magento-2#781]
Hello,

I am having problems when reindexing algolia_queue_runner; it always fails, here is the summary of the error (text file with full error: [full error algolia.txt](https://github.com/algolia/algoliasearch-magento-2/files/3216406/full.error.algolia.txt)):

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Algolia\AlgoliaSearch\Helper\Data' does not have a method 'rebuildCategoryIndex' in /home/myhost/public_html/Mywebsite/vendor/algolia/algoliasearch-magento-2/Model/Job.php on line 82 in /home/myhost/public_html/Mywebsite/vendor/magento/framework/App/ErrorHandler.php:61`

PHP 7.1.29, Magento 2.3.1, tried both Algolia 1.9 and 1.11, same error.

**Comment by razvan-f** [comment]
Hey guys @JanPetr @0livier @bsuravech,

any opinion on this ?

**Comment by bsuravech** [comment]
Hi @razvan-f,

Apologies for the delay in response. I took a look at your error txt file, and thank you for providing that for us to view. It's a very interesting error. Can you confirm that your  \Algolia\AlgoliaSearch\Helper\Data class contains the method rebuildCategoryIndex() ?

https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Data.php#L340-L344

**Comment by razvan-f** [comment]
Hi @bsuravech ,

Thank you for jumping in !

I removed the Algolia extension and all files in /vendor/algolia and reinstalled. The Data.php files are 100% identical at this point. 

However, now I am getting errors about different methods (moveIndex, saveConfigurationToAlgolia), see attached file.
[algolia error.log](https://github.com/algolia/algoliasearch-magento-2/files/3396823/algolia.error.log)

**Comment by bsuravech** [comment]
Hi @razvan-f, 

Can you share with us the indexing queue table rows for the jobs that contain moveIndex and saveConfigurationToAlgolia methods? We'd like to see what their class and if its listed correctly in the jobs.

**Comment by razvan-f** [comment]
Oh thank you @bsuravech, you are a life saver. 

I never thought to check the queued jobs and to clear them, as I assumed there is a system that clears those. There were jobs in there since Magento 2.1.7 & AlgoliaSearch 1.7.2 and I guess that's why they were failing. Once I deleted those, everything was working fine.

Cheers !
Razvan.

**Comment by bsuravech** [comment]
Awesome, @razvan-f! I'm glad you figured it out! Cheers!
