### ISSUE TITLE
Magento 2.1 saving category fatal error

### ISSUE THREAD

**Issue by JEifert** [algolia/algoliasearch-magento-2#787]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**Bug: What is the current behaviour?**
After updating Algolia to 1.11, php encounters a fatal error when saving a category, either programatically or in the admin backend:
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Algolia\AlgoliaSearch\Model\Indexer\CategoryObserver::afterSave() must be an instance of Magento\Catalog\Model\Category, none given, called in /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php on line 74 and defined in /var/www/html/vendor/algolia/algoliasearch-magento-2/Model/Indexer/CategoryObserver.php:19
Stack trace:
#0 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(74): Algolia\AlgoliaSearch\Model\Indexer\CategoryObserver->afterSave(Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor))
#1 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Array, 'catalogsearchFu...')
#2 /var/www/html/vendor/magento/module-catalog-search/Mode in /var/www/html/vendor/algolia/algoliasearch-magento-2/Model/Indexer/CategoryObserver.php on line 19

**Bug: What is the expected behaviour?**
Save the category successfully.

**Bug: What is the proposed solution?**
Accessing method parameters in the "after" interceptor method is not supported in Magento 2.1, only in Magento versions >= 2.2
https://devdocs.magento.com/guides/v2.3/ext-best-practices/extension-coding/common-programming-bp.html#using-around-plugins

To maintain backwards compatibility with Magento 2.1, the afterSave function in Algolia\AlgoliaSearch\Model\Indexer\CategoryObserver should be converted to aroundSave.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Using Magento 2.1 and Algolia 1.11.1

**Comment by bsuravech** [comment]
Hi @JEifert,

Thank you for providing a thorough report. We have an active PR that will be included in the next release that addresses this issue. Can you try to patch the CategoryObserver.php file with the changes in this PR and let us know if this works for you? 

https://github.com/algolia/algoliasearch-magento-2/pull/783

We hope to release these changes soon. Thanks!

**Comment by xantek-imc** [comment]
I was having the same problem with Magento 2.3.1 and Algolia 1.11.1.  PR #783 patch did apply cleaning and resolved the PHP fatal error while saving categories.

**Comment by JEifert** [comment]
Thanks,

Saving the category seems to work correctly after applying the patch.
