### ISSUE TITLE
Magento2.2.7 layred navigation attribute filter not working

### ISSUE THREAD

**Issue by zaheerbadi** [algolia/algoliasearch-magento-2#792]
**Bug: What is the current behavior?**
it doesn't return filtered product collection when we filter with any attribute.

**Bug: What is the expected behavior?**
it should be filter with attribute.

**Algolia version
1.11.1

**Comment by razvan-f** [comment]
This is one of the historical problems of Algolia on Magento 2, it was there since the first release. Still not fixed on Algolia 1.11.1 & Magento 2.3.1.

**Comment by zaheerbadi** [comment]
Hello @JanPetr @0livier @bsuravech 

Can anyone please respond on the above issue.

**Comment by zaheerbadi** [comment]
**Its strange but it worksssssss**
http://prntscr.com/o3d6y9
When Enable Instant Search Results Page to Yes just for saving my custom attribute and again it saved with No then refresh my layered navigation result it works.

Don't know why this happened but it works for now.

**Comment by zaheerbadi** [comment]
**Strange but it works**

You have to add your custom attribute in http://prntscr.com/o3q1zt
and set **Enable Instant Search Results Page** to No after saved your custom attribute otherwise it won't work.

Chearssssssssssssssssssssssss

**Comment by bsuravech** [comment]
Hi everyone! 

@zaheerbadi, I'm glad you were able to figure out the solution to your issue! 

We are going to take this feedback into consideration when reviewing our backend implementation as well as for our general documentation and updates to our configuration. Thank you!
