### ISSUE TITLE
Magento 2 B2B Index Error

### ISSUE THREAD

**Issue by glo-arandazzo** [algolia/algoliasearch-magento-2#793]
**Bug: What is the current behavior?**
On a Magento 2.2.8 Enterprise B2B site using shared catalogs and permissions, the following error occurs:

```#bin/magento index:reindex algolia_products
Algolia Search Products indexer process unknown error:
Notice: Undefined offset: 1 in /site/vendor/algolia/algoliasearch-magento-2/Model/Observer/CatalogPermissions/ProductCollectionAddPermissions.php on line 66```

**Bug: What is the expected behavior?**
The index should complete without issue. 

Any help would be greatly appreciated.

**Comment by bsuravech** [comment]
Hi @glo-arandazzo,

The PR to correct this issue has been merged into the latest version. Please feel free to upgrade and let us know if that works out for you. Thanks!
