### ISSUE TITLE
Home Search Not working

### ISSUE THREAD

**Issue by ebofi** [algolia/algoliasearch-magento-2#796]
Hi,

We had installed the Algolia and we are using Porto Theme, after installed the algolia plugin we see that our search button on top is not working on clickable., so we then specify the dom selector via admin. After that search works but we dont see algolia results apperiaring on the search, but we see only default magneto Instant search results showing when typing.

**Comment by bsuravech** [comment]
Hi @ebofi ,

Thanks for reaching out. Can you confirm that the Autocomplete feature is enabled in your configuration? If yes, on the frontend, when you type in a query to the search input, can you see in the developer tools inspector if the autocomplete dropdown is populating? It might be that the theme has it hidden or underneath another layer. Let us know!

**Comment by ebofi** [comment]
This is what im seeing in console and when i type on the Search, nothing happens. 


![Untitled-1 copy](https://user-images.githubusercontent.com/25876216/59519530-ae092280-8ee5-11e9-9c4f-95d42645b199.jpg)

**Comment by ebofi** [comment]
20 days passed. Please algolia help on this

**Comment by bsuravech** [comment]
@ebofi Can you please reach out to support@algolia.com with your issue including your APP ID? It might be plan related and someone from our team can assist you. Please feel free to refer to this issue in your email. Thanks!
