### ISSUE TITLE
Add to cart option not disabling

### ISSUE THREAD

**Issue by sammarcus** [algolia/algoliasearch-magento-2#80]
I may be missing something but even when I toggle this to off, the default hit template still shows the Add to Cart in the hit on the results page?

![image](https://cloud.githubusercontent.com/assets/8689264/19063485/3d6ca252-89b8-11e6-8e63-df8dda26792b.png)

I've emptied the relevant caches and reindexed but the individual hits still shows the template Add To Cart button. Of course I can simply remove it from the hit template, but I thought it was unexpected behavior for it not to respect `isAddToCartEnabled`

**Comment by sammarcus** [comment]
I performed a few more searches and noticed that some queries the button existed but as I made the query longer the button disappeared as the results updated! Very strange.

![ezgif-1506705850](https://cloud.githubusercontent.com/assets/8689264/19176304/496ce214-8bf3-11e6-94fd-96b33ce9885e.gif)

**Comment by JanPetr** [comment]
Hello @sammarcus,
sorry for the late response.

Is the issue still persists and you still can see the button on "short" queries? Do you have any error in your browser's console?

**Comment by JanPetr** [comment]
Hello @sammarcus,
did you manage to solve the issue? Do you have a live website, where I could take a look?

**Comment by sammarcus** [comment]
@JanPetr Sorry I didn't see this before! I just ended up removing the entire form at the end of the hits template since I will never be needing add to cart functionality directly in my hit. I didn't peek at the console while this was occurring, but next time I have a chance and m working with an earlier version of my data I can try to provide some logging to see why this was happening. Feel free to close if you'd like!

**Comment by JanPetr** [comment]
Thanks for the clarification @sammarcus. If you'll get chance to reproduce, I'll be happy to get more info about it. Cheers!
