### ISSUE TITLE
How to index the image of categories and other attributes?

### ISSUE THREAD

**Issue by leonardovilarinho** [algolia/algoliasearch-magento-2#804]
I'm at a time trying to index the category images and other product attributes, such as: custom options and configurable product configurations.

I have no idea how to do this, can anyone tell me if this is possible?

**Comment by bsuravech** [comment]
Hi @leonardovilarinho, 

Thanks for reaching out to us. To index category images, you can use a category backend event to create an observer and add the category image attribute there. 

Product attributes can be configured in the **Stores > Configuration > Algolia Search > Products** settings but if you need to add a custom attribute you can utilize a product backend event for another observer to pass in additional or dynamic attribute values. You can read more about backend events here:

https://www.algolia.com/doc/integration/magento-2/customize/custom-back-end-events/
