### ISSUE TITLE
Translating "show more" and "show less" for facets

### ISSUE THREAD

**Issue by jellesiderius** [algolia/algoliasearch-magento-2#821]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
The facets with a limit of items, show "Show more" and "Show less". This should be translatable in the i18n within your Magento theme.

**Bug: What is the proposed solution?**
Make this translatable.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.3.1
Algolia 1.11.1

**Comment by bsuravech** [comment]
Hi @jellesiderius,

Thank you for reporting! I'm going to create an internal ticket for this issue. We'll follow up once this has been updated. Cheers!
