### ISSUE TITLE
Option to index categories regardless of 'Include in Menu' status not working

### ISSUE THREAD

**Issue by batmike** [algolia/algoliasearch-magento-2#824]
I currently have enabled the option to index all categories whether the Include in Menu option per category is Yes or No. However, when I have categories where Include in Menu is disabled, Algolia is not indexing those categories even if there are active products in them.

To get the category indexed, I've found that I have to have the entire tree for a particular category set to Include in Menu and then, if I really don't want it in the menu, I've been overriding it in the Topmenu.php function specifically.

**Comment by damcou** [comment]
Hello there,

This issue should be fixed in our next release coming in January.
Here is the PR : https://github.com/algolia/algoliasearch-magento-2/pull/864

Best.
