### ISSUE TITLE
Show custom product attribute on category pages

### ISSUE THREAD

**Issue by baljinderimpinge** [algolia/algoliasearch-magento-2#827]
Hello Support,

I am using Algolia search on my magento 2 store and I have enabled algolia seach on my category pages. It is working fine but I have to add some custom attributes data on the listing page. Can you please let me know how to show that?
https://magento2.wernersheadshop.ch/wasserpfeifen/shisha.html?p=2

Thanks

**Comment by baljinderimpinge** [comment]
hello @sgmac @0livier @yannickcr @redox
Can you please let me know about above query?
Thanks

**Comment by damcou** [comment]
Hello, 

Your question / issue seems to be related to your specific use-case.
For this type of request, please reach out our support team at support@algolia.com.
Thanks for understanding.
