### ISSUE TITLE
Category broken image showing in autosuggestion

### ISSUE THREAD

**Issue by Nehace40** [algolia/algoliasearch-magento-2#828]
I enable configuration Remove pub from image url.

Now in autosuggestion category image come with pub in URL so image is not showing proper. Product image is showing correct without pub in url.

**Comment by damcou** [comment]
Hello, 

Your question / issue seems to be related to your specific use-case.
For this type of request, please reach out our support team at support@algolia.com.
Thanks for understanding.

**Comment by adarshkhatri** [comment]
`Remove pub/ from image URLs` setting completely has no effect in magneto 2.3.3. It doesn't do anything. Shame

**Comment by adarshkhatri** [comment]
Right, so you must do reindex after making that change. 

`bin/magento indexer:reindex algolia_products`

Then all images will be updated without `pub` in the url.
