### ISSUE TITLE
Update operations extremely high

### ISSUE THREAD

**Issue by jasuten** [algolia/algoliasearch-magento-2#831]
**Bug: What is the current behavior?**

We have around 15k products, around 50 custom attributes, several price groups and catalog price rules. We are getting update record operations over 500k-1m on days that are busy with product and inventory updates.

The search indexes are all set to schedule, we can see that the algolia_products_cl table can have 40 duplicates of a single product every time a product is saved, which is 40 update operations on the same product.

**Bug: What is the expected behavior?**

Update record operations should be a lot lower.

**Bug: What is the proposed solution?**

The Magento mview tables (i.e. algolia_products_cl, catalog_product_flat_cl) do not have a unique key set on the entity_id column. We've made a little extension internally that adds a unique key to the column to stop duplicates. This is more of an issue with Magento but as Algolia uses the default indexing logic it is affected by it.

We also do not show prices on our search results (B2B site) & show out of stock products, but there is no easy way to remove subscriptions in the mview.xml from watching the catalog_product_index_price & cataloginventory_stock_item tables unnecessarily. It would be great to be able to have options to control if this isn't requires to cut down on update operations as well. At the moment we had to make a local copy of the extension and modify it instead of installing through composer.

These two changes for us reduced update operations from 500k to 600 per day.

**Feature: What is your use case for such a feature?**

Reduce monthly expenses and improve site performance.

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

New options to control which tables are utilised for mview subscriptions. Possibly also adding a unique key for just the algolia_products_cl table until Magento fixes their cl tables.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Using Magento 2.3.1, latest Algolia. Tested the same issue occurs on 2.3.2.

**Comment by damcou** [comment]
Hello @jasuten ,

Thanks for reaching out.
Your use case seems to be interesting and we would be very interested to know what are the ecxact changes you made on your local copy of the extension and which files are affected.

It will help us a lot to see if we can do something "global" to add to the extension. 

Let us know.
Best.

**Comment by jasuten** [comment]
Hi @damcou ,

Here is our attempt at fixing the issue for our scenario https://github.com/rival-ecommerce/magento-mviewfix

One drawback is that if a product is updated, then indexed, then updated again soon after the product isn't added to the changelog tables until they get cleared (every hour by Magento). Which isn't an issue for us but could be for others.

**Comment by damcou** [comment]
Thanks a lot for your feedback.
We'll work on the indexing queue refactoring on early 2020 and we'll take your issue in account, for sure ;) .

If you have additional questions, feel free to reopen the issue.
Best.
