### ISSUE TITLE
Use ?page=2 for infinite scroll search

### ISSUE THREAD

**Issue by projdevel** [algolia/algoliasearch-magento-2#832]
Installed the latest version (1.11.3).

Does that possible to include pagination to url when Infinity scroll is turned on?

Also when I click "Show more", url doesn't apply parameter to something like http://sile.lo?page=2

And when I go to http://sile.lo?page=2 still show first algolia search page.

**Comment by damcou** [comment]
Hello @projdevel ,

I'm sorry but according to the Instant Search document, it doesn't seem to be possible.
More information on the request you sent on our forum [here](https://discourse.algolia.com/t/infinite-scroll-click-event/8284). 

Sorry again.
