### ISSUE TITLE
Magento 2.1.2 Backend does not work

### ISSUE THREAD

**Issue by skynixukraine** [algolia/algoliasearch-magento-2#84]
Hi there,

After migrating from Magento 2.0.7 to Magento 2.1.2 all pages of magento backend stopped working.
I've tried:
- clean cache manually from var directory
- clean asstes from put/static
- installed Magento 2.1.2 from scratch
The issue is everywhere.
![cache management tools system magento admin 2016-10-15 14-32-35](https://cloud.githubusercontent.com/assets/12690168/19409790/b8dc5ca4-92e4-11e6-9f98-e8bbbdbf43a9.png)

**Comment by JanPetr** [comment]
Hello @skynixukraine,
thanks for report. Can you turn off merging of JS files? Does the problem persist?

**Comment by skynixukraine** [comment]
Well, yes, when merging is turned off it is ok. 
Let's keep this ticked opened until it is fixed.

**Comment by JanPetr** [comment]
Fixed in #86

**Comment by JanPetr** [comment]
Released
