### ISSUE TITLE
Update to Algolia PHP client 2.3

### ISSUE THREAD

**Issue by simonmaass** [algolia/algoliasearch-magento-2#846]
Are there any efforts on migrating to the 2.x Algolia Search API Client for PHP?

**Comment by bsuravech** [comment]
Hi @simonmaass! We're currently evaluating the update to the latest Algolia Search PHP API Client. You can follow along in this PR: 

https://github.com/algolia/algoliasearch-magento-2/pull/848

**Comment by simonmaass** [comment]
@bsuravech great - thank you!
