### ISSUE TITLE
Removing Algolia as magento module causes errors

### ISSUE THREAD

**Issue by avoelkl** [algolia/algoliasearch-magento-2#855]
**Bug: What is the current behavior?**
The Algolia module was removed via composer and in app/etc/config.php. An error occurs while saving in the backend, saying algolia_products_cl table is not available.

**Bug: What is the expected behavior?**
Algolia is removed and not problems in the webshop occur.

**Bug: What is the proposed solution?**
Remove the triggers when the module is unistalled.
The triggeres were created in the **catalog_product_entity_media_gallery_value** table as they cause errors if the algolia_products_cl table is not present any more.

Update: Same applies to the **catalog_product_index_price_replica** table, there are triggers which are old/outdated as well (found during reindex):
```SQLSTATE[42S02]: Base table or view not found: 1146 Table 'algolia_products_cl' doesn't exist, query was: INSERT INTO `catalog_product_index_price_replica` (`entity_id`, `customer_group_id`, `website_id`, `tax_class_id`, `price`, `final_price`, `min_price`, `max_price`, `tier_price`) SELECT `catalog_product_index_price_temp`.`entity_id`, `catalog_product_index_price_temp`.`customer_group_id`, `catalog_product_index_price_temp`.`website_id`, `catalog_product_index_price_temp`.`tax_class_id`, `catalog_product_index_price_temp`.`price`, `catalog_product_index_price_temp`.`final_price`, `catalog_product_index_price_temp`.`min_price`, `catalog_product_index_price_temp`.`max_price`, `catalog_product_index_price_temp`.`tier_price` FROM `catalog_product_index_price_temp` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `customer_group_id` = VALUES(`customer_group_id`), `website_id` = VALUES(`website_id`), `tax_class_id` = VALUES(`tax_class_id`), `price` = VALUES(`price`), `final_price` = VALUES(`final_price`), `min_price` = VALUES(`min_price`), `max_price` = VALUES(`max_price`), `tier_price` = VALUES(`tier_price`)```

Update 2: This is a nightmare, i keep finding more and more errors:
```[SQLSTATE[42S02]: Base table or view not found: 1146 Table 'algolia_products_cl' doesn't exist, query was: INSERT INTO `catalog_product_entity_media_gallery` (`attribute_id`,`value`) VALUES (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?) ON DUPLICATE KEY UPDATE `attribute_id` = VALUES(`attribute_id`), `value` = VALUES(`value`)]```

```[2019-09-18 17:46:16] main.ERROR: Cron Job indexer_update_all_views has an error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'algolia_products_cl' doesn't exist, query was: INSERT INTO `catalog_product_index_price` (`entity_id`, `customer_group_id`, `website_id`, `tax_class_id`, `price`, `final_price`, `min_price`, `max_price`, `tier_price`) SELECT `catalog_product_index_price_temp`.`entity_id`, `catalog_product_index_price_temp`.`customer_group_id`, `catalog_product_index_price_temp`.`website_id`, `catalog_product_index_price_temp`.`tax_class_id`, `catalog_product_index_price_temp`.`price`, `catalog_product_index_price_temp`.`final_price`, `catalog_product_index_price_temp`.`min_price`, `catalog_product_index_price_temp`.`max_price`, `catalog_product_index_price_temp`.`tier_price` FROM `catalog_product_index_price_temp` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `customer_group_id` = VALUES(`customer_group_id`), `website_id` = VALUES(`website_id`), `tax_class_id` = VALUES(`tax_class_id`), `price` = VALUES(`price`), `final_price` = VALUES(`final_price`), `min_price` = VALUES(`min_price`), `max_price` = VALUES(`max_price`), `tier_price` = VALUES(`tier_price`). Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":161742848,"emalloc_start":150170632} [] []```

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.3.2.

according to composer.json:
"algolia/algoliasearch-magento-2": "^1.11"

**Comment by bsuravech** [comment]
Hi @avoelkl - thank you for reporting this. We apologize for the delay in response. We currently don't have an uninstall script to remove CL tables but this is something we will add to our product board for future improvements to the extension. 

Magento currently doesn't make dropping triggers for Update on Schedule easy and apparent for cases like this. You will need to have the extension installed and by going to Index Management, simply change the indexing mode for all Algolia indexes from "Update on Schedule" to "Update on Save". This tells Magento to manually drop all triggers associated to the Algolia subscriptions. Let me know if you have any questions regarding the above.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue, feel free to respond and re-open the issue. Thank you!
