### ISSUE TITLE
Multiple inventories indexing algolia?

### ISSUE THREAD

**Issue by robbertstevens** [algolia/algoliasearch-magento-2#856]
**Do you want to request a *feature* or report a *bug*?**
FEATURE

**Feature: What is your use case for such a feature?**
Indexate the stock warehouses.

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
Should be based on if you use multiple inventories or not.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento2.3.2
Algolia 1.11.1

**Comment by bsuravech** [comment]
Hi @robbertstevens! Thanks for inquiring. We are currently working on compatibility with MSI and hoping to release that in the coming months. Please feel free to follow our releases for the latest updates:

https://github.com/algolia/algoliasearch-magento-2/releases
