### ISSUE TITLE
Accessing a not configured CATEGORY_CUSTOM_RANKING value is problematic

### ISSUE THREAD

**Issue by ThomasNegeli** [algolia/algoliasearch-magento-2#858]
**Bug: What is the current behavior?**
Cronjob indexer_update_all_views stores the following message in the cron_schedule table 
```Warning: array_filter() expects parameter 1 to be array, boolean given in /var/www/src/releases/72/src/vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php on line 603```

**Bug: What is the expected behavior?**
If no ```CATEGORY_CUSTOM_RANKING```is configured, this should not raise a warning.

**Bug: What is the proposed solution?**
Check values before using them

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.9 Commerce B2B
Algolia 1.11.3

**Comment by bsuravech** [comment]
Hi @ThomasNegeli - Thanks for reporting! We have added it to a pull request to cast the empty value for customRanking configuration to return an empty array to prevent this warning message.

**Comment by damcou** [comment]
Hi there, the fix has been merged, feel free to apply to your Magento instance if needed.
The next version will be released in January 2020.

Thanks for your feedback.
Best.
