### ISSUE TITLE
Category Indexing has an incorrect path with /admin/ tag

### ISSUE THREAD

**Issue by adamvarga** [algolia/algoliasearch-magento-2#862]
**Bug: What is the current behavior?**

We have detected a problem with one magento shop (2.3.2 - OS) regarding the Algolia search extension (v. 1.11.3). The autocomplete menu displays the category URLs incorrectly. No matter which storview one chooses, the category URLs is always supplemented with **/admin/** and thus generated incorrectly.

Then we invalidated the algolia category index via the CLI: `php bin/magento indexer:reset algolia_categories` and the indices were automatically rebuilt by Magento. I checked the index table in the algolia backend again. The resetting unfortunately did not help. The regenerated urls are still wrong.

**Bug: What is the expected behavior?**

Where the tag /admin/ is in the URLs integrated / indexed at any time, the storeview code (**de, en, it**) should be displayed accordingly. 

I also checked the indexes in algolia backend (for every storeview) and the URLs are displayed wrong in all categories as well. I attached some screenshots below.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.2 (OS)
Algolia 1.11.3

![algolia_search_wrong_category_urls_1](https://user-images.githubusercontent.com/17138890/65880110-8f923e80-e391-11e9-99a3-aa3a5bff2459.png)

![algolia_search_wrong_category_urls_2](https://user-images.githubusercontent.com/17138890/65880343-eef04e80-e391-11e9-8ba1-28b7ea3aa7dd.png)

![algolia_search_wrong_category_urls_3](https://user-images.githubusercontent.com/17138890/65880126-96b94c80-e391-11e9-88b4-e1c656e7fe7c.png)

**Comment by damcou** [comment]
Hello there,

Your issue should be fixed with the current version of your module (1.12.1).
Could you please update it?
Feel free to reopen the issue if you still have questions.

Best.
