### ISSUE TITLE
Magento Commerce displaying wrong products in categories or empty categories

### ISSUE THREAD

**Issue by Thundar** [algolia/algoliasearch-magento-2#871]
**Bug: What is the current behavior?**

In Magento Commerce the extension is querying Algolia for a different category path for categories not included in menu, so for such categories this could happen:
- you get the right products
- you get the products of a different (sibling) category
- you get an empty category

**Bug: What is the expected behavior?**
You should get the products indexed for the category you are browsing

**Bug: What is the proposed solution?**
In CategoryHelper the getCoreCategories function does:
`->addAttributeToFilter('include_in_menu', '1')`
When happening, the result from `getCategoryKeyId` returns null for certain category ids, and `getCategoryById` will not be able to retrieve the row id for that category (Magento Commerce feature).
 So `getCategoryName` will return the name of a category with row_id equal to the entity_id of the category we should have, resulting in a wrong XHR query to Algolia.

I see no mean in using `->addAttributeToFilter('include_in_menu', '1')`, or at least it could be used depending by the `ConfigHelper::showCatsNotIncludedInNavigation()` result (beware it could change by store).

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento Commerce 2.2.4
Algoliasearch Magento 2 1.11.3

**Comment by Thundar** [comment]
There is a similar issue with `->addIsActiveFilter()` in the same collection and indexing. If the category is disabled in global configuration and/or default store view, the product will be indexed without that category in the store index, when entity_id does not match with row_id.

**Comment by 0livier** [comment]
Hi @Thundar. We acknowledge the issue, and commit to fix it for the next minor release 1.12.1 (we're releasing 1.12.0 this week or the next one). We'll prioritize the fix before features as it's a troublesome bug. We'll keep you informed when we start to work on it and give you a branch name so you'll be able to use the patch before it's formally released in a new version.

**Comment by Thundar** [comment]
Thank you so much @0livier . Please note the difficult side: each category could be activated/included in menu or not depending by single store too. The most intuitive behavior is to have only and all the categories matching the store in the store indexes.

**Comment by 0livier** [comment]
Hey @Thundar. Small update, the team will look at this issue during next sprint.

**Comment by damcou** [comment]
Hello @Thundar ,

Just a quick update to let you know that we are currently having a look at this issue. 
From my understanding, indexing all the (enabled) categories without taking into account the include_in_menu attribute would resolve a lot of issue.
Then, we already filter the categories section of the autocomplete menu and we would just have to find a solution to filter them in the categories filter of the product listing as well.

Let me know if you have additional questions.

**Comment by Thundar** [comment]
Hello @damcou 
thank you for the follow up. Yes, I think that removing include_in_menu you should just adjust filtering results later.
Anyway, please note that both "is_enabled" and "include_in_menu" could be flagged per website/store view. The actual category collection, running on cron, does not distinguish store views as for the other product attributes.

**Comment by damcou** [comment]
Hello @Thundar ,

Again, apologies for the delay, we are still on this issue.
We are still looking for a solution regarding the category filter.
Here is where we are right now on the related branch : https://github.com/algolia/algoliasearch-magento-2/commit/639fb9f71b568885df8565eb38789d70557eaf4f
Maybe you could give it a try on your side to tell us if it solves your issues (it's still in progress so there's some commented code) ?

Regarding store view config, I made some tests on my side and the process seem to handle this type of setting (tried to disable and/or non include a category at store level, and it only disappear from the index for the related store). Did you experienced any inconsistency ou you side related to this ?

**Comment by Thundar** [comment]
Hello @damcou 
di compilation is failing in Magento 2.2.4 as \Magento\Framework\Search\EngineResolverInterface was added in 2.3.0. I would need https://github.com/algolia/algoliasearch-magento-2/pull/900 in fix/category-include-in-menu branch...

**Comment by damcou** [comment]
Hello @Thundar ,

Apologies for this, it should be good now.

**Comment by 0livier** [comment]
Hi @Thundar ,

Just checking if you saw that @damcou updated the pull request #864 in order to have the PR work with Magento 2.2.4's DI.

**Comment by Thundar** [comment]
@0livier yes, thanks, the build in 2.2 is ok now. We can check the indexes as @damcou asked.

**Comment by Thundar** [comment]
@damcou I see no more an empty category path node as before, anyway there is still an issue I'm facing on "non default" stores that could bring to wrongly empty categories. Please have a look at this examples.
![Screenshot 2019-10-28 at 10 29 57](https://user-images.githubusercontent.com/2631899/67667803-f2fe9480-f96e-11e9-9477-b09435d97f2d.png)
![Screenshot 2019-10-28 at 10 29 28](https://user-images.githubusercontent.com/2631899/67667807-f5f98500-f96e-11e9-9b68-dfb2074ef0c6.png)

Additionally, some products in a secondary website/store view index have indexed enabled categories from default store view/website (disabled both in that store view and in store view 0), anyway I think this is a minor issue.

**Comment by damcou** [comment]
Hello @Thundar ,

Thanks for the test.
I'm trying to reproduce such behaviour on my side.
Could you please tell me if the category "Tua Terra" is indexed in the category index for the store c_902 ?

Is this particular product directly associated to the category "Tua Terra" ? If not, could you please associate it and try to reindex the product ?

Thanks in advance.
Best.

**Comment by Thundar** [comment]
@damcou 
When I get the screenshots before I just reindexed algolia_products. After your question, I reindexed algolia_categories and then the single sku. It is correct now!

**Comment by damcou** [comment]
Thanks a lot for this feedback @Thundar ! And happy to see that it seems to get better on your side ;)

Are you still seeing issues related to store assignments ?

**Comment by Thundar** [comment]
@damcou Just looking at the indexes I see no issue about categories that are supposed to be enabled in the right store views in _products indexes.

There are some missing path in _categories indexes and there are additional disabled categories in _products indexes, but I think this two things will be irrelevant when the "category filters" for the `include_in_menu=1` will be completed in frontend. Please let me know if you need additional details about them, as they could be off topic now.

**Comment by damcou** [comment]
Hello @Thundar ,

Just checking if everything is ok on your side now.
I confirm that the disabled categories won't appear in the indices as they are not available in Magento as well, in any case.
Let me know if you see any problems now.
Best.
Damien

**Comment by Thundar** [comment]
Hello @damcou , starting from today we got this error during compilation on the working branch. Released version is still ok.
`Compilation was started.
Errors during compilation:
	Algolia\AlgoliaSearch\Model\ResourceModel\Query\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Magento\Framework\Model\ResourceModel\Db\AbstractDb; File: 
/opt/atlassian/pipelines/agent/build/vendor/algolia/algoliasearch-magento-2/Model/ResourceModel/Query/Grid/Collection.php`

**Comment by damcou** [comment]
Hello @Thundar, Thanks a lot for having spotted this.
Seems that a line was accidentaly removed in this class during the last commit, it should be fixed on develop, now.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue, feel free to respond and re-open the issue. Thank you!

**Comment by Thundar** [comment]
This issue is solved in _develop_ branch, we're still waiting for the next release to have it in production. Thanks
