### ISSUE TITLE
Magento 2.3.2 : Autocomplete results configurable product prices showing $0.00

### ISSUE THREAD

**Issue by sriharsha184** [algolia/algoliasearch-magento-2#890]
After upgrading to Magento 2.3.2 Version,Configurable products with $0.00 is showing in Instant search result page.
Earlier this issue was fixed,But after upgrading to M.2.3.2 and Algolia 1.11.3 issue was raised again.

URL for fix : https://github.com/algolia/algoliasearch-magento-2/pull/527

**Comment by sriharsha184** [comment]
@damcou Thanks for response.
We have upgraded Magento version from 2.2.2 to 2.3.2 .Currently we are not using MSI.
Can you please guide us on  preventing index if child products of configurable product is out of stock.So that,it will not appear in instant search.

**Comment by sriharsha184** [comment]
@damcou 

I have digged into this and found that configurable products are indexing even though it's child are out of stock.But,child products are not indexing.Need to prevent configurable product to index if child are out of stock.

Thanks.

**Comment by damcou** [comment]
Hello there,

This issue has been resolved in another thread, see there : https://github.com/algolia/algoliasearch-magento-2/issues/951

Feel free to apply to your Magento instance if needed. 
The next version will be released in January 2020.

Thanks for your feedback.
Best.
