### ISSUE TITLE
Object size checking - not actual hadcoded size

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#904]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Current object size limit is hardcoded to 20kb, but based on documentation it`s limit different for Algolia plans(here https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records/):
- 10 KB for Pro, Starter, or Free accounts
- 20 KB for legacy (Essential and Plus)  

**Bug: What is the expected behavior?**
This constant should be replaced to variable and it should be depend on Application Algolia plan. 

**Bug: What is the proposed solution?**
The best way, it`s implement logic for get Plan info (name, limitations)
 and based on these information - implement checking object before push object. Of course, may need to extend API library or endpoint for getting that data for checking.

**Comment by bsuravech** [comment]
Hi @vmalyk, 

Thanks for reporting and offering a solution. We have already introduced a check against plan level to set the max record size per account. You can review some of the code here:

https://github.com/algolia/algoliasearch-magento-2/blob/develop/Helper/ConfigHelper.php#L1083-L1113

This was introduced in release 1.11.0, in PR #746.  Let us know if you have any questions regarding the above. Thanks!
