### ISSUE TITLE
Error in product indexing on Magento 2.3.3 Commerce / B2B

### ISSUE THREAD

**Issue by adamrandazzo** [algolia/algoliasearch-magento-2#907]
**Bug: What is the current behavior?**
Just installed the latest 1.12 version and attempted to do a reindex. I received the following error when trying to reindex algolia_products:

```
$ bin/magento index:rein algolia_products 
Algolia Search Products indexer process unknown error:
Warning: count(): Parameter must be an array or an object that implements Countable in /var/vhosts/domain.com/dev/vendor/algolia/algoliasearch-magento-2/Helper/ProductDataArray.php on line 26
```
**Bug: What is the expected behavior?**
The index should complete without errors

**Bug: What is the proposed solution?**
Check to make the item is an array and isn't null. Wrap this around the code:

```
if (is_array($items)) {

}
```

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.3.3 Commerce / B2B edition

**Comment by bsuravech** [comment]
Hi @adamrandazzo, 

Thanks for reporting the issue regarding the countable error thrown on the PHP 7.2 version. We've created a PR to help address the issue which you can review #915. Let me know if you have any questions regarding the above.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue, feel free to respond and re-open the issue. Thank you!
