### ISSUE TITLE
Elastic Search 6 Compatibility

### ISSUE THREAD

**Issue by jasuten** [algolia/algoliasearch-magento-2#916]
**Bug: What is the current behavior?**
When Elastic search 6 is used as the Catalog search engine, the results do not come from Algolia.

**Bug: What is the expected behavior?**
The search results should come from Algolia

**Bug: What is the proposed solution?**
It looks like the preferences for Elastic search 5 were added into the extension previously. We added the following into our di.xml file:

    
    <type name="Magento\Search\Model\AdapterFactory">
        <arguments>
            <argument name="adapters" xsi:type="array">
                <item name="elasticsearch6" xsi:type="string">Algolia\AlgoliaSearch\Adapter\Algolia</item>
            </argument>
        </arguments>
    </type>

**Comment by damcou** [comment]
Hello there,

This issue is already on our radar and we are currently working on a compability module that will allow the extension to be working on top of Elasticsearch.
This should be available in January 2020.

Feel free to reopen the issue if you have additional questions.
Best.
Damien
