### ISSUE TITLE
Error: Exception: Warning: Illegal string offset

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#917]
Hi.

I'm using Magento 2.3.1, when I ran the reindex command. I got this error: 
ERROR: Exception:
                    Warning: Illegal string offset 'attribute' in /var/www/production/vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php on line 1052 in /var/www/production/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/production/vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php(1052): Magento\Framework\App\ErrorHandler->handler(2, 'Illegal string ...', '/var/www/produc...', 1052, Array)
#1 /var/www/production/vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php(647): Algolia\AlgoliaSearch\Helper\ConfigHelper->addIndexableAttributes('a:9:{s:18:"_150...', Array, '0')
#2 /var/www/production/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php(295): Algolia\AlgoliaSearch\Helper\ConfigHelper->getProductAdditionalAttributes(1)
#3 /var/www/production/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php(242): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->getAdditionalAttributes(1)
#4 /var/www/production/vendor/algolia/algoliasearch-magento-2/Helper/Data.php(306): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->getProductCollectionQuery(1, Array)
#5 [internal function]: Algolia\AlgoliaSearch\Helper\Data->rebuildStoreProductIndex(1, Array)
#6 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php(83): call_user_func_array(Array, Array)
#7 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(220): Algolia\AlgoliaSearch\Model\Job->execute()
#8 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(179): Algolia\AlgoliaSearch\Model\Queue->run(200)
#9 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Indexer/QueueRunner.php(56): Algolia\AlgoliaSearch\Model\Queue->runCron()
#10 /var/www/production/vendor/magento/module-indexer/Model/Indexer.php(413): Algolia\AlgoliaSearch\Model\Indexer\QueueRunner->executeFull()
#11 /var/www/production/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer->reindexAll()
#12 /var/www/production/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(87): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#13 /var/www/production/vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/production/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/production/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/production/vendor/magento/framework/Console/Cli.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/production/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/production/bin/magento(23): Symfony\Component\Console\Application->run()
#19 {main}

Can you please have a look?

**Comment by damcou** [comment]
Duplicated (https://github.com/algolia/algoliasearch-magento-2/issues/958)
