### ISSUE TITLE
Algolia_AlgoliaSearch breaks Magento_GoogleShoppingAds admin page

### ISSUE THREAD

**Issue by Pirosauro** [algolia/algoliasearch-magento-2#919]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Algolia_AlgoliaSearch breaks Magento_GoogleShoppingAds admin page. (https://devdocs.magento.com/extensions/google-shopping-ads/)

**Bug: What is the expected behavior?**
Navigate to Marketing > Advertising Channels > Google Shopping ads. A page should appear, unfortunately AlgoliaSearch includes prototype (legacy_build) which breaks the page load.

**Bug: What is the proposed solution?**
.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.4 
Algolia_AlgoliaSearch (algolia/algoliasearch-magento-2) 1.12.1 
Magento_GoogleShoppingAds 3.0.1

**Comment by damcou** [comment]
Hi there, 
The fix has been merged, feel free to apply to your Magento instance if needed. 
The next version will be released in January 2020.

Thanks for your feedback.
 Best.
