### ISSUE TITLE
composer installation issue

### ISSUE THREAD

**Issue by sherazkhan302** [algolia/algoliasearch-magento-2#920]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**
When i try to install algolia for magetno 2 vis composer its giving the following error

  Problem 1
    - algolia/algoliasearch-magento-2 1.12.1 requires algolia/algoliasearch-client-php >=1.27.0 <2.0 -> satisfiable by algolia/algoliasearch-client-php[1.27.0,1.28.0, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - algolia/algoliasearch-magento-2 1.12.0 requires algolia/algoliasearch-client-php >=1.27.0 <2.0 -> satisfiable by algolia/algoliasearch-client-php[1.27.0,1.28.0, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for algolia/algoliasearch-magento-2 ^1.12 -> satisfiable by algolia/algoliasearch-magento-2[1.12.0, 1.12.1].

**Bug: What is the expected behavior?**
Algolia installed successfully

**Bug: What is the proposed solution?**

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
magento 2.3.3

**Comment by bsuravech** [comment]
Hi @sherazkhan302! We've replied to your support ticket and will address your issue there. 

Closing out for HS ticket #202961.
