### ISSUE TITLE
Autocomplete displaying all SKUs (parent & child product SKUs)

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#923]
Hello.

Can you please investigate why all the SKUs are displaying in the autocomplete section? http://prntscr.com/pz3mg7

I expected to display simple products SKUs and configurable parent product SKUs only.

I'm using
Algolia 1.12.1
Magento 2.3.1
PHP 7.2.24

**Comment by damcou** [comment]
Hello @luan123z ,
For the configurable product, we index the parent and the children inside the sku attribute, so if you want to display every product and take into account the fact that it can be configurable, you have to check if there's more than one sku.
You can do something like this : 

{{#sku.0}}
                    {{{ sku.0.value }}}
                {{/sku.0}}
                {{^sku.0}}
                    {{{ sku.value }}}
                {{/sku.0}}

**Comment by luan123z** [comment]
hi @damcou 

Is it possible to use the "If else" condition?
I would like to retrieve {{type_id}}
If its value is "configurable", display some text. Otherwise, display other text.

**Comment by damcou** [comment]
Hi @luan123z .

Not sure if it's possible, here is the documentation of the template engine : https://mustache.github.io/mustache.5.html

To check if the product is configurable, you can still check if sku.0 exists (configurable skus are indexed as an array) and display whatever text you need in such case.
