### ISSUE TITLE
getLastCheck causes segfault on server

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#941]
Our backend suddenly gave a 502 after flushing the cache.

After following processes on the server, I found that it segfaulted. I `strace`-d the process and this is what I found;

```
read(12, "", 8192)                      = 0
read(12, "", 8192)                      = 0
close(12)                               = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2052c00000
madvise(0x7f2052c00000, 2097152, MADV_HUGEPAGE) = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2052a00000
madvise(0x7f2052a00000, 2097152, MADV_HUGEPAGE) = 0
access("/data/web/releases/20191203111529/vendor/magento/theme-adminhtml-backend/Magento_Security/templates/page/activity_link.phtml", F_OK) = -1 ENOENT (No such file or directory)
access("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml/templates/page/activity_link.phtml", F_OK) = 0
lstat("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml/templates/page/activity_link.phtml", {st_mode=S_IFREG|0664, st_size=721, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml/templates/page", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml/templates", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/magento/module-security/view", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml/templates/page/activity_link.phtml", {st_mode=S_IFREG|0664, st_size=721, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/magento/module-security/view/adminhtml/templates/page/activity_link.phtml", {st_mode=S_IFREG|0664, st_size=721, ...}) = 0
access("/data/web/releases/20191203111529/vendor/magento/theme-adminhtml-backend/Magento_Backend/templates/page/report.phtml", F_OK) = -1 ENOENT (No such file or directory)
access("/data/web/releases/20191203111529/vendor/magento/module-backend/view/adminhtml/templates/page/report.phtml", F_OK) = 0
lstat("/data/web/releases/20191203111529/vendor/magento/module-backend/view/adminhtml/templates/page/report.phtml", {st_mode=S_IFREG|0664, st_size=402, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/magento/module-backend/view/adminhtml/templates/page/report.phtml", {st_mode=S_IFREG|0664, st_size=402, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/magento/module-backend/view/adminhtml/templates/page/report.phtml", {st_mode=S_IFREG|0664, st_size=402, ...}) = 0
access("/data/web/releases/20191203111529/vendor/magento/theme-adminhtml-backend/Algolia_AlgoliaSearch/templates/tracking.phtml", F_OK) = -1 ENOENT (No such file or directory)
access("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/tracking.phtml", F_OK) = 0
lstat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/tracking.phtml", {st_mode=S_IFREG|0644, st_size=12978, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/tracking.phtml", {st_mode=S_IFREG|0644, st_size=12978, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/tracking.phtml", {st_mode=S_IFREG|0644, st_size=12978, ...}) = 0
access("/data/web/releases/20191203111529/vendor/magento/theme-adminhtml-backend/Algolia_AlgoliaSearch/templates/common.phtml", F_OK) = -1 ENOENT (No such file or directory)
access("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/common.phtml", F_OK) = 0
lstat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/common.phtml", {st_mode=S_IFREG|0755, st_size=15629, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/common.phtml", {st_mode=S_IFREG|0755, st_size=15629, ...}) = 0
stat("/data/web/releases/20191203111529/vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/common.phtml", {st_mode=S_IFREG|0755, st_size=15629, ...}) = 0
poll([{fd=8, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(8, "*3\r\n$4\r\nHGET\r\n$45\r\nzc:k:831_ALGOLIASEARCH_NOTIFICATION_LASTCHECK\r\n$1\r\nd\r\n", 73, MSG_DONTWAIT, NULL, 0) = 73
poll([{fd=8, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 1 ([{fd=8, revents=POLLIN}])
recvfrom(8, "$", 1, MSG_PEEK, NULL, NULL) = 1
poll([{fd=8, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=8, revents=POLLIN}])
recvfrom(8, "$-1\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 5
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x55c400001406} ---
write(5, "Process 12095 (version 9.2.0.247) received signal 11: segmentation violation\n", 77) = 77
write(5, "process id 12095 fatal signal (SIGSEGV, SIGFPE, SIGILL, SIGBUS, ...)  - stack dump follows (code=0x7f2065e87000 bss=0x7f2066158b3c):\n", 133) = 133
futex(0x7f207c169110, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f207907d680, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x55c400001406} ---
+++ killed by SIGSEGV +++

```

The `831_ALGOLIASEARCH_NOTIFICATION_LASTCHECK` part prompted me to look at the `\Algolia\AlgoliaSearch\Model\ExtensionNotification::getLastCheck` method. I don't have time to dive into this right now so I worked around this by having `\Algolia\AlgoliaSearch\Model\ExtensionNotification::checkVersion()` early-return `null`.

**Comment by damcou** [comment]
Hello @peterjaap ,

Thanks for reaching out.
Is it happening on your production environment ? What kind of access restriction do you have on your admin ?

**Comment by peterjaap** [comment]
@damcou yes. Nothing fancy, just the normal login (no 2FA or IP check).

**Comment by alex-james** [comment]
We are seeing the same issue on a staging envionment

**Comment by peterjaap** [comment]
@alex-james probably yes, older versions of PHP are known to segfault on json_decode (for various reasons). What version are you running? We're at 7.1.33 now, upgrade to M2.3.3 and PHP 7.3 along with is is planned for this month...

**Comment by peterjaap** [comment]
Might be better to refactor `getLatestVersionFromRepository()` into using Guzzle - it's a Magento dependency so why rely on cURL when we have an abstraction that catches these weird errors?

**Comment by alex-james** [comment]
@peterjaap We are running 7.1.26 so likely to be the same issue you are seeing in 7.1.30

**Comment by damcou** [comment]
Thanks a lot for your inputs and suggestions @peterjaap and @alex-james , we'll have a look at it with the team ASAP :) .

**Comment by damcou** [comment]
Hi @peterjaap and @alex-james .

I made some changes in the class, I followed your advice and used Guzzle, could you please give it a try and tell me if you're still experiencing the issue ?

PR : https://github.com/algolia/algoliasearch-magento-2/pull/949

Thanks in advance.
Best.

**Comment by wbyrnetx** [comment]
I just got done reading through a PHP-FPM coredump, which led me to Algolia\AlgoliaSearch\Model\ExtensionNotification::checkVersion as well.

Ubuntu 18.04.3 LTS PHP 7.1.33-2

**Comment by 0livier** [comment]
Hey @wbyrnetx . Is it reproductible? If yes, is the #949 PR supplied by @damcou fixing things on your side?

**Comment by wbyrnetx** [comment]
We deployed algoliasearch-magento-2 version 1.12.1 yesterday. After doing so, logging into the admin panel resulted in a 502 response and a core dump from PHP-FPM. I was able to reproduce the issue every time I tried to go to the admin panel. We reverted back to version 1.11.2 and have not seen the issue since.

I have not tried reproducing in a staging environment yet.

I'll give #949 guzzle a try, but I have never run into issue with the standard PHP curl functions and json_decode. Many of our other modules in Magento utilize those functions. I'm not convinced that it's json_decode's fault alone. I don't have any evidence of this, but I have a feeling that it may have to do with the combined use of file_get_contents + stream_context_create + json_decode in getLatestVersionFromRepository. My recommendation would be to try using the standard curl functions ([curl_exec](https://www.php.net/manual/en/function.curl-exec.php)) to make the HTTP request.

**Comment by 0livier** [comment]
Many thanks for the extra information William. Much appreciated!

**Comment by damcou** [comment]
Hi everybody here,

I added the last changes today.
If everything is approved, we'll merge it very soon and it should be available in the coming release in January 2020.

Thanks again to all of you!
Best.

**Comment by webamondo** [comment]
I also have this issue rolling back to 1.12.0  worked for me.

I tried to create a patch out of the PR but that too failed. Fingers crossed the next release comes out soon!

**Comment by danemacmillan** [comment]
Release in February 2020?

**Comment by bsuravech** [comment]
Hi everyone! 

PR#949 for GuzzleHTTP changes has been release in version [1.13.0](https://github.com/algolia/algoliasearch-magento-2/releases/tag/1.13.0). If you haven't upgraded to our latest version, please feel free to do so. 

If you have any further questions or issues with upgrading, please let us know by shooting us a message at [support@algolia.com](mailto:support@algolia.com).
