### ISSUE TITLE
Add new Configuration indexer to Magento CLI

### ISSUE THREAD

**Issue by danemacmillan** [algolia/algoliasearch-magento-2#945]
It would be great to expose a new indexer in the Magento CLI to allow pushing up configuration changes made in the Algolia module via the Magento2 admin.

Currently, these are the indexers available to run:

```
algolia_products                         Algolia Search Products
algolia_categories                       Algolia Search Categories
algolia_pages                            Algolia Search Pages
algolia_suggestions                      Algolia Search Suggestions
algolia_additional_sections              Algolia Additional Sections
algolia_queue_runner                     Algolia Search Queue Runner
algolia_delete_products                  Algolia Search - Delete inactive products
```

We have the queue running, so whenever products are changed, the changes get indexed (sent to Algolia).

However, whenever configuration changes are made, such as adding new product attributes or exposing them as facets in the UI, that information is not immediately pushed up. A full Products or Category index is required in order for Algolia to push up any configuration changes. It's clear as day in the code:

<img width="895" alt="Screen Shot 2019-12-06 at 10 47 19 AM" src="https://user-images.githubusercontent.com/4390491/70336067-82bd1b80-1816-11ea-9cb9-95fda852c0ff.png">

This is after running a category indexer:

<img width="1339" alt="Screen Shot 2019-12-06 at 10 37 08 AM" src="https://user-images.githubusercontent.com/4390491/70337529-450dc200-1819-11ea-8582-9b6548338005.png">

The same two configuration change indexes for each store also gets added when running a full product index.

Given how expensive it is to push information into Algolia, we'd like to set up a cron that regularly pushes up configuration changes so our merchandising department does not need to communicate with developers every other day. We're averaging about 10M search requests a month, and 7M indexing operations, so it's tedious to have to get everything reindexed when all that's needed are configuration changes.

I propose, then, that a new Algolia indexer is added, which exclusively calls the non-exposed `saveConfigurationToAlgolia` indexer to the Magento CLI: 

```
algolia_configuration                     Algolia's Magento Search Configuration 
```

I suppose the counterargument to implementing this feature would be: "Why would you ever want an active configuration change that is not also reflected in the all the indexed Product or Category data that would need to be updated to pull in that new information?" To that, I would simply say we can tolerate a level or delay when it comes to older products not carrying this data, and instead just slowly getting it as merchandisers make changes to the catalog, which would mean all those changed products *will* get the newly-configured data.

**Comment by bsuravech** [comment]
Hi @danemacmillan,

My apologies in the delay in response. Thanks for the feedbacks regarding exposing the indexer in the Magento backoffice as well as the suggestion for the configuration indexing. To assure that when we index, we are using the current settings configured, we fire the saveConfigurationToAlgolia incase there were changes made in between indexing. For your usecase, this might be unnecessary. We are going to port your feedback over to our productboard for consideration.

If you have any further questions or feedback for us, please feel free to shoot us a message at [support@algolia.com](mailto:support@algolia.com) and say that this is feedback for our Magento team. Thanks!
