### ISSUE TITLE
Not passing storeId to isIndexingEnabled() in IndexMover::moveIndex*

### ISSUE THREAD

**Issue by morgannilsson** [algolia/algoliasearch-magento-2#946]
moveIndex and moveIndexWithSettings:

        if ($this->baseHelper->isIndexingEnabled() === false) {

Compare to IndicesConfigurator::saveConfigurationToAlgolia: 

        if ($this->baseHelper->isIndexingEnabled($storeId) === false) {

**Comment by damcou** [comment]
Hello @morgannilsson ,

I had a look at your issue.
The only place where the class [IndexMover](https://github.com/algolia/algoliasearch-magento-2/blob/develop/Model/IndexMover.php) is used in in the class https://github.com/algolia/algoliasearch-magento-2/blob/develop/Model/Indexer/Product.php (moveIndexWithSetSettings being only used at [line124](https://github.com/algolia/algoliasearch-magento-2/blob/develop/Model/Indexer/Product.php#L124) .

We already check the enablement of the indexing for each store at the beginning of the "store loop" here : https://github.com/algolia/algoliasearch-magento-2/blob/develop/Model/Indexer/Product.php#L124

I'll close this issue but feel free to reopen it if you have additional questions.
Thanks for your feedback.

Best.
