### ISSUE TITLE
Remove separate cron in crontab for queue indexing

### ISSUE THREAD

**Issue by dverkade** [algolia/algoliasearch-magento-2#947]
**Current situation**

Currently Algolia needs a separate cron job to be installed when the option "Enable Indexing Queue" is enabled. See screenshot. 

![image](https://user-images.githubusercontent.com/1058480/70435879-485ab500-1a88-11ea-8887-787a2c857f37.png)

**Expected behaviour**

Magento offers two different ways to cope with this. The indexers them self can run on a "update by schedule" basis, where only the changes needed for the update are processed. This functionality can be used in order to remove setting up a separate cron. 

Magento offers the ability to run crons automatically with the Magento_Cron module. Use this functionality when the setting "Enable Indexing Queue" is enabled and run the cron job. This way there's no need to setup a separate cron job in order to make Algolia work.

**Comment by bsuravech** [comment]
Hi @dverkade, thanks for your feedback regarding the indexing queue configuration. 

We are aware of the Magento_Cron module as an alternative solution for manually creating a cron job. I believe the original reason why this wasn't implemented through Magento_Cron was to be able to customize the interval at which the indexing queue can run. It is recommended to be set at every 5 minutes but this can be adjusted to the needs and resources of our users. 

As you mentioned, the Indexing Queue Runner is an indexer. It is possible to have it run through Update on Schedule which is run every minute as an alternative. 

To address your last statement, it is not required to have the Indexing Queue enabled. This is a deferred processing method to optimising batching records and reducing operational calls to Algolia. The feature is recommended for stores that have more frequent catalog changes. 

I have ported over your feedback to our product board for consideration for future improvements to the extension. Thanks for submitting!
