### ISSUE TITLE
Arrays in attribute data converted to strings

### ISSUE THREAD

**Issue by sammarcus** [algolia/algoliasearch-magento-2#95]
Hi,

I intentionally populated some attributes with their entire value as an array since there were several distinct strings for a single attribute.

Example:

``` php
["string1","string2","string3"]
```

However, when the extension processes this it is escaping my quotes and just encapsulating the whole thing as a string. The record reflects:

``` php
"[\"string1\",\"string2\",\"string3\"]"
```

This conversion prevents us from taking advantage of the reason why they should be in arrays in the first place (namely proximity relevance). Algolia of course supports arrays, but are there best practices to indexing these values from Magento while preserving their intended data structure?

**Comment by maxiloc** [comment]
Can you give us more details about this attribute.
How it is configured in magento, how it is configured for algolia, ... ?
So that we can try to reproduce it.

**Comment by sammarcus** [comment]
I am primarily adding additional keywords as the data in the attribute. The only two possible attribute system formats are either _Text Field_ or _Text Area_, since custom text can not be entered in a free flow format for any other kind of attribute. In the interest of completeness, I have tried both Field and Area and experienced the same outcome with the extension.

![image](https://cloud.githubusercontent.com/assets/8689264/19922950/56c9abc2-a0bb-11e6-90a0-b8605e0ec37b.png)

![image](https://cloud.githubusercontent.com/assets/8689264/19922960/64b9b86c-a0bb-11e6-9c78-023554ab4eae.png)

In the actual `eav_attribute` Magento  table I observed the following properties for the two basic newly created text attributes, the most relevant being that they have two different backend types:

<table border="1" cellpadding="0" cellspacing="0">
<tr><th>attribute_id</th><th>entity_type_id</th><th>attribute_code</th><th>attribute_model</th><th>backend_model</th><th>backend_type</th><th>backend_table</th><th>frontend_model</th><th>frontend_input</th><th>frontend_label</th><th>frontend_class</th><th>source_model</th><th>is_required</th><th>is_user_defined</th><th>default_value</th><th>is_unique</th><th>note</th></tr>
<tr><td>195</td><td>4</td><td>bucket_field</td><td>NULL</td><td>NULL</td><td>varchar</td><td>NULL</td><td>NULL</td><td>text</td><td>bucket_field</td><td>NULL</td><td>NULL</td><td>0</td><td>1</td><td>NULL</td><td>0</td><td>NULL</td></tr>
<tr><td>196</td><td>4</td><td>bucket_area</td><td>NULL</td><td>NULL</td><td>text</td><td>NULL</td><td>NULL</td><td>textarea</td><td>bucket_area</td><td>NULL</td><td>NULL</td><td>0</td><td>1</td><td>NULL</td><td>0</td><td>NULL</td></tr>
</table>


----------


Once these are created and attached to a product, I add these attributes through the extension so Algolia will consider them as it indexes the product:

![image](https://cloud.githubusercontent.com/assets/8689264/19922839/d8b73538-a0ba-11e6-9b36-0db0ef4d71fe.png)

Next. I return to the product and populate these two attributes with an array. I am simply typing text in an array format in the Magento product interface:

![image](https://cloud.githubusercontent.com/assets/8689264/19923356/564a3796-a0bd-11e6-9877-ea48d687857f.png)

I then save the product and double check the entity tables to verify they are saved as I have literally typed them.

Here is `catalog_product_entity_text`:
<table border="1" cellpadding="0" cellspacing="0">
<tr><th>value_id</th><th>attribute_id</th><th>store_id</th><th>entity_id</th><th>value</th></tr>
<tr><td>15324</td><td>196</td><td>0</td><td>7512</td><td>[\"REL2S40SC\", \"ICN2S40N\", \"R2S40TP\", \"GE240RSMVN\", \"B234SR120MA\", \"B234SR277MA\", \"B240R120HP\", \"B240R277HP\", \"KTEB240UVTPPIC\", \"HL240RSUVW\", \"EP240RSMV\", \"VE240120HRP\", \"RM2S35TP\", \"RM-2SP301TP\", \"Mark III R2S40-1-TP\", \"446LRTCP \", \"RELB-2S40-SC\"]</td></tr>
</table>

And, here is `catalog_product_entity_varchar` table:

<table border="1" cellpadding="0" cellspacing="0">
<tr><th>value_id</th><th>attribute_id</th><th>store_id</th><th>entity_id</th><th>value</th></tr>
<tr><td>132874</td><td>195</td><td>0</td><td>7512</td><td>[\"REL2S40SC\", \"ICN2S40N\", \"R2S40TP\", \"GE240RSMVN\", \"B234SR120MA\", \"B234SR277MA\", \"B240R120HP\", \"B240R277HP\", \"KTEB240UVTPPIC\", \"HL240RSUVW\", \"EP240RSMV\", \"VE240120HRP\", \"RM2S35TP\", \"RM-2SP301TP\", \"Mark III R2S40-1-TP\", \"446LRTCP \", \"RELB-2S40-SC\"]</td></tr>
</table>

As expected, the textual data in `value` column in both of these tables is literally an array, and it preserved correctly when the product is saved.

---------------------
As soon as I saved the product, the extension performs an `addObject` request on my behalf to my master. Here is the contents of this:

```json
{
  "requests": [
    {
      "action": "addObject",
      "body": {
        "objectID": 7512,
        "name": "Stringed Name",
        "visibility_search": 1,
        "visibility_catalog": 1,
        "categories": [
        ],
        "categories_without_path": [
        ],
        "in_stock": 1,
        "ordered_qty": 0,
        "stock_qty": 1,
        "sku": "XXQ",
        "price": {
          "USD": {
            "default": 234,
            "default_formated": "$234.00",
            "special_from_date": false,
            "special_to_date": false
          }
        },
        "created_at": "2016-11-02 09:03:04",
        "bucket_area": "[\"REL2S40SC\", \"ICN2S40N\", \"R2S40TP\", \"GE240RSMVN\", \"B234SR120MA\", \"B234SR277MA\", \"B240R120HP\", \"B240R277HP\", \"KTEB240UVTPPIC\", \"HL240RSUVW\", \"EP240RSMV\", \"VE240120HRP\", \"RM2S35TP\", \"RM-2SP301TP\", \"Mark III R2S40-1-TP\", \"446LRTCP \", \"RELB-2S40-SC\"]",
        "bucket_field": "[\"REL2S40SC\", \"ICN2S40N\", \"R2S40TP\", \"GE240RSMVN\", \"B234SR120MA\", \"B234SR277MA\", \"B240R120HP\", \"B240R277HP\", \"KTEB240UVTPPIC\", \"HL240RSUVW\", \"EP240RSMV\", \"VE240120HRP\", \"RM2S35TP\", \"RM-2SP301TP\", \"Mark III R2S40-1-TP\", \"446LRTCP \", \"RELB-2S40-SC\"]",
        "type_id": "simple"
      },
      "objectID": "7512"
    }
  ]
}
```

Here is where the main concern is. What was previously entered as an array at every step of the way has since been unexpectedly transformed and encapsulated as a massive string, with all `"` being automatically escaped by `\`. This is problematic for many reasons, namely that because this is transformed in flight, there is essentially no way to store any text attribute as an array inside an Algolia JSON record in its current state with this Magento extension.

Of course, the data can be modified in the record by other means after the extension has already called for an index.

```json
{
  "name": "Stringed Name",
  "visibility_search": 1,
  "visibility_catalog": 1,
  "categories": [],
  "categories_without_path": [],
  "in_stock": 1,
  "ordered_qty": 0,
  "stock_qty": 1,
  "sku": "XXQ",
  "price": {
    "USD": {
      "default": 234,
      "default_formated": "$234.00",
      "special_from_date": false,
      "special_to_date": false
    }
  },
  "created_at": "2016-11-02 09:03:04",
  "bucket_area": "[\"REL2S40SC\", \"ICN2S40N\", \"R2S40TP\", \"GE240RSMVN\", \"B234SR120MA\", \"B234SR277MA\", \"B240R120HP\", \"B240R277HP\", \"KTEB240UVTPPIC\", \"HL240RSUVW\", \"EP240RSMV\", \"VE240120HRP\", \"RM2S35TP\", \"RM-2SP301TP\", \"Mark III R2S40-1-TP\", \"446LRTCP \", \"RELB-2S40-SC\"]",
  "bucket_field": "[\"REL2S40SC\", \"ICN2S40N\", \"R2S40TP\", \"GE240RSMVN\", \"B234SR120MA\", \"B234SR277MA\", \"B240R120HP\", \"B240R277HP\", \"KTEB240UVTPPIC\", \"HL240RSUVW\", \"EP240RSMV\", \"VE240120HRP\", \"RM2S35TP\", \"RM-2SP301TP\", \"Mark III R2S40-1-TP\", \"446LRTCP \", \"RELB-2S40-SC\"]",
  "type_id": "simple",
  "objectID": "7512"
}
```

If I tamper with the record directly, the array is respected and preserved, because Algolia records of course support arrayed structures. In this image I manually changed `bucket_area` to an array — you can see this visually designated because the enclosing brackets are colored red.

![image](https://cloud.githubusercontent.com/assets/8689264/19924229/6c6c2f4e-a0c1-11e6-938a-04a306da680f.png)

But the success is short lived as the Magento extension will simply overwrite these the next time it indexes.

So, how is it possible to pass array values on to an Algolia record using the Magento extension and if this is not possible, are there any feasible workaround to allow for this type of data to be kept as an array in the record?

**Comment by sammarcus** [comment]
and also, some additional details from one more table about the 2 new attributes I just created in Magento:

 **_catalog_eav_attribute_**

<table border="1" cellpadding="0" cellspacing="0">
<tr><th>attribute_id</th><th>frontend_input_renderer</th><th>is_global</th><th>is_visible</th><th>is_searchable</th><th>is_filterable</th><th>is_comparable</th><th>is_visible_on_front</th><th>is_html_allowed_on_front</th><th>is_used_for_price_rules</th><th>is_filterable_in_search</th><th>used_in_product_listing</th><th>used_for_sort_by</th><th>apply_to</th><th>is_visible_in_advanced_search</th><th>position</th><th>is_wysiwyg_enabled</th><th>is_used_for_promo_rules</th><th>is_required_in_admin_store</th><th>is_used_in_grid</th><th>is_visible_in_grid</th><th>is_filterable_in_grid</th><th>search_weight</th><th>additional_data</th></tr>
<tr><td>195</td><td>NULL</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>NULL</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>1</td><td>1</td><td>NULL</td></tr>
<tr><td>196</td><td>NULL</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>NULL</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>1</td><td>1</td><td>NULL</td></tr>
</table>

**Comment by JanPetr** [comment]
Hello @sammarcus,
thank you for the details and sorry for late answer.

Even though you are writing array syntax into textareas, it's still considered as string. It cannot be interpreted as array as it'd mean huge security issue, when you'd be allowed to write code into input fields.

Here I'd suggest you to to change attribute type to something like multi-select box and select proper values one by one, that it'll be considered as array.
Or you can use the [extension's custom event](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L789) and add these values programatically or cast the attributes to array there. 

But it's not something we can do out-of-box in the extension.

**Comment by sammarcus** [comment]
Thanks @JanPetr. For the purposes of the particular attributes that I need to do this with, multi-select would not be feasible (or at least it would certainly not be realistic). Am I correct in that Algolia's attribute to snippet feature will not work correctly if these are not in a proper array? Can you speak to some of the implications of having these in a string / how it is distinguishing one word from the next when it displays the matching snippet?

In designing my data I confirmed on your end a few times that arrays were the preferred way to store this kind of data for several reasons (proximity, snippeting, etc), so I see it as a significant limitation of the extension that it cannot respect the array format if it is desired as the rest of Algolia operates under it needing to be in an array.

I am most concerned about not being able to accurately process the snippeting as that is a crucial feature. If you can think of any possible workarounds regarding how snippets are processed that I can use strings and still have a highlighted snippet displayed correctly (use n many spaces between each word, use a special character like a period, etc) that would be really helpful. 

Is this string conversion happening in ProductHelper file you referenced? I quickly reviewed it and was not able to narrow down where it would be occurring, could you point to where it is happening so I can play with that? I am also reviewing the custom event you mentioned and also looking in to manually rewriting these values afterwards with `.partial_update_object` but it would not be nearly as convenient to make indexing a two step process.

Thank you!

**Comment by JanPetr** [comment]
Hello @sammarcus,
I can imagine why it's inconvenient to have it as multi select.
But it's not issue of the extension. The attribute is always string. Even in your database it's still a string, which has PHP array syntax. And this is how we index it - as string which has format of PHP code. 

In order to index it as array, we'd need to interpret those code as PHP. But we cannot do that at all as it does not have to always contain harmless array. It may contain real PHP code and it's HUGE security issue for your store and your server in general.

If you want to use it just for snippets you can add the code as simple string with spaces:
`CODE1 CODE2 CODE3`. And than set this attribute to attributesToSnippet in Algolia dashboard and specify nbOfWords to 1. So only the one matching word will be snippeted. Documentation is here: https://www.algolia.com/doc/api-client/php/parameters#attributestosnippet

Would that work for you?

**Comment by sammarcus** [comment]
Thanks @JanPetr. I understand and appreciate the security implications of unsterilized data coming in. Not to be splitting hairs — and this may be my lack of fully understanding how Magento utilizes `varchar` and `text` entity tables — but based on what the values are showing, it really does appear to be an array of strings in those tables:

![image](https://cloud.githubusercontent.com/assets/8689264/20194650/302df08e-a761-11e6-9b83-e2142b8a6210.png)

In any case, while proximity would be nice, not having it is not a huge deal. My most pressing concern was having snippets being calculated correctly and spaces seem to work fine for the most part. Where it starts to get tricky is for circumstances where the single value has a special character. My data has a lot of obscure product numbers so this is not unusual for me; can you discuss some of the implications around snippet calculation with `-`, `/` and `\` in the value? In experimentation it seems the snippet considers these stop points and does not return the other portion of the value.

Example query: `GE232MAXL-Ultra`
Returned snippet: `Ultra`

This occurs when `attributesToSnippet` is set to display only 1 word, of course. I can't increase it to 2 words because then when a query does not have a special character, the user will be shown one pertinent value and a second one that happens to be neighbors with the first.

Other possible workarounds: Remove all of the values that have exotic characters and make an entirely new attribute for these special values. Either set typo tolerance to be very generous on these (so it will still match) and entirely remove all the characters from the values, resulting in the snippet being singular but just having dropped the special character. Not sure that would even work, though, and it would certainly be a truly last resort 😬 

Note: I have tried tinkering with separatorsToIndex` but it doesn't seem to have an obvious impact on snippet calculation unfortunately.

**Comment by sammarcus** [comment]
Another concern I had was that I am getting snippet return values for all the searchable attributes I have displayed in my hit.

Basically I have four additional custom attributes that are searchable and set to display in my hit. Very rough portrayal:

```html
First Attribute
<br>
{{{ _snippetResult.attribute_1.value }}}

Second Attribute
<br>
{{{ _snippetResult.attribute_2.value }}}

Third Attribute
<br>
{{{ _snippetResult.attribute_3.value }}}

Fourth Attribute
<br>
{{{ _snippetResult.attribute_4.value }}}
```

This results in two issues. When there is a match in one of the four, the other three labels always display (obvious because I have hardcoded them in 🙂) but, it is also just pulling the first "word" in the string for the other and showing it for those as well (albeit, not highlighted). I know this has little to do with my original Issue but does Algolia support a way to retrieve which attribute is being matched so I can not implement it like I have done? And secondly, how to stop it from lazily showing words for attributes that it was not a match for?

Maybe I am doing this totally wrong, very open to suggestions on how to ultimately accomplish an elegant, clean Hit that clearly displays 1) why it was a match, and 2) back it up with highlighted + snippeted text 🙏

**Comment by sammarcus** [comment]
Just for visualization if it helps, the below Hit actually demonstrates all of the concerns. Query was `GE232MAXL-Ultra` and you can see the other 3 attributes that aren't matched are still shown. I know it's because I put them in there :) but wasn't sure how else to dynamically include the right one in the hit 

![image](https://cloud.githubusercontent.com/assets/8689264/20198633/aa1011d6-a773-11e6-9bf3-1df49257ea5b.png)

(non matching attributes still just fall back to show the first "word" as the returned snippet value instead of nothing)

**Comment by sammarcus** [comment]
Hi Algolia team, do you have any ideas on this? Happy to move to email as well. Thank you!

**Comment by sammarcus** [comment]
Hi guys, I really could use your feedback on this and haven't heard back in awhile. Is there a mechanism to fetch only the attribute that caused the match? I don't want to show irrelevant attributes that were not responsible for the matched result but not sure if Algolia supports that/how that could be implemented?

**Comment by JanPetr** [comment]
Hello @sammarcus,
sorry, it was really busy couple of days lately.

I will get back to you later today. Please bear with us for a little while.

**Comment by JanPetr** [comment]
Hello @sammarcus,

withing `_snippetResult` you have also `matchLevel` attribute. You can use it to see if the Axis 2 or Axis 3 is matched and if you should display it.

See the screenshot:
![screenshot 2016-11-17 12 07 36](https://cloud.githubusercontent.com/assets/1058144/20387032/7b6c5f60-acbe-11e6-8e44-d5fc58d465b5.png)

You can see that only `snippet_attribute1` is matched and highlighted. Others have `matcheLevel: none`. So you can skip it's rendering.

I created a demo for you so you can play with it - https://jsfiddle.net/JanPetr/Lth00e0e/1/

**Comment by JanPetr** [comment]
Hello @sammarcus,
since I didn't hear from you for a while I'm closing the issue.

If you'll need any more help feel free to reopen.

**Comment by toddhainsworth** [comment]
Hi @JanPetr I might be seeing a similar issue.

I have a multiselect in this case (where @sammarcus used a textarea, so this might not be the same?) where someone using the admin area can select different styles for a product ('floral', 'spicy', 'chocolatey', etc...).

This is saved as 'floral,spicy,chocolatey' in the database and Magento can parse this and display the values correctly on the backend however when Algolia is trying to validate this against the values returned by `getAllOptions` on the Backend Source model by using `\Magento\Eav\Model\Entity\Attribute\Source\AbstractSource::getOptionText` it's trying to compare 'floral' (a label from the result of `getAllOptions`) with 'floral,spicy,chocolatey'.

I expect multiselects will always fail here unless only one option is selected (which would result in 'floral' being the database value for example).

If this is unrelated I'm happy to create a new issue and link to this one! :smile:

**Comment by toddhainsworth** [comment]
In the meantime I've written a plugin to tackle multiselect values if they're not present within the array that is sent to the API. I can provide details if needed and/or submit a PR with the workaround/possible fix :smile:
