### ISSUE TITLE
Collapse Mobile Search - Luma Theme

### ISSUE THREAD

**Issue by sb-bob-lessard** [algolia/algoliasearch-magento-2#950]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Luma theme for Magento 2 out-of-the-box displays a magnifying glass in the header, and upon clicking on the icon, the search box then becomes visible just below the header (previously hidden). Upon selecting the magnifying glass a 2nd time (while the search box is visible), the search box then disappears. This is particularly important on mobile due to the limited screen real estate and above-the-fold content. However, with Algolia search for Magento 2, the full search box is always visible, breaking the Luma theme and reducing the screen space for above the fold content.

**Bug: What is the expected behavior?**
The search box on mobile to function like the Luma theme search box. Only displaying when the user clicks on the magnifying glass.
  
**Bug: What is the proposed solution?**
Adjust default styling and create javascript to mimic Luma theme for the search box on mobile.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento ver. 2.3.3
Algolia ver. 1.11.3

**Comment by bsuravech** [comment]
Hi @sb-bob-lessard, thanks for the feedback and suggestion regarding the mobile UI for the autocomplete search field. I'm going to port this feedback over to our product board for consideration as future improvement to our extension.
