### ISSUE TITLE
Filter results incorrect (configurable-simple links) [BUG]

### ISSUE THREAD

**Issue by stephan-cream** [algolia/algoliasearch-magento-2#951]
**What is the situation**
When configurable products are indexed to Algolia, all of it's simple variants (regardless of stock) are synced towards Algolia.
Regardless of what is configured in "Stores -> Configuration -> Algolia Search -> Products: Index out of stock options for configurable products"

**Example**
- I have product "A" which is configurable and has variants based on the attribute 'size'.
- I have product "B", "C" and "D" which are simples, each with their own size.
- Product "B" has a size of 1 and has no stock.
- Product "C" has a size of 2 and is in stock.
- Product "D" has a size of 3 and is in stock.
- Configuration "Index out of stock options for configurable products" is set to **No**.

**Expected Result**
- Product "A" is synced in Algolia.
- Product "A" has the configurable attribute 'size'.
- The attribute 'size' for product "A" has two out of three values, namely the sizes 2 and 3.
`size: ['2', '3']`

**Actual Result**
- Product "A" is synced in Algolia.
- Product "A" has the configurable attribute 'size'.
- The attribute 'size' for product "A" has three out of three values, namely the sizes 1, 2 and 3.
`size: ['1', '2', '3']`

**Aditional Information**
In the following helper `vendor/algolia/algoliasearch-magento-2/Helper/ConfigHelper.php` there is code which retrieves the aforementioned configuration from "Index out of stock options for configurable products", however this code is not used anywhere within the entirety of the project.
`public function indexOutOfStockOptions($storeId = null)`

**Proposed Solution**
Implement the above mentioned function somewhere within the logic of retrieving the configurable attribute options for a configurable product.
I would assume this would be somewhere in `vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php`?
 
**System Information**
Occurs in all versions of Magento. (currently on 2.3.3)
Occurs in all versions of the Algolia extension. (currently on 1.12.1)

**Comment by cgcullen** [comment]
https://secure.helpscout.net/conversation/1029466952/213917?folderId=1106367

**Comment by stephan-cream** [comment]
Pardon?

**Comment by 0livier** [comment]
Hi Stephan, please disregard the message above, it's a reference to our support tracking system where we received the request from Matthijs.

**Comment by damcou** [comment]
Hi @stephan-cream ,

Thanks for reaching out.
I had a look at your message, and you seem to be right about the `indexOutOfStockOptions` method, its use seems to have been forgotten in a previous refactoring. I'll have a look and try to handle it ASAP.

But it's suprising that you get this result because the extension should now natively remove the subProducts which has no stock, see here : https://github.com/algolia/algoliasearch-magento-2/blob/develop/Helper/Entity/ProductHelper.php#L562-L567

All the subproducts go through the `canProductBeReindexed` method which defines if a product can be reindexed or not, and remove it if it's not the case. So in your example, if the subproduct B has no stock, it should be removed.
I check on a configurable product of the Magento sample data and it seems to work as expected.
Could you please check if this product (B) remains in the `$subProducts` array ?

Thanks again.
Best.

**Comment by stephan-cream** [comment]
Hi @damcou ,

It is true that it won't show up as an option on the configurable when the configuration 'show out of stock' is set to 'No'.
However the situation is as follows:
- We want to show out of stock products (mainly for simple products) so all products which are at least enabled are shown in search results.
- We don't want filters to show out of stock options (mainly for configurables).

In this case the option "Index out of stock options for configurable products" would suit that logic perfectly, but this feature is unimplemented.

With kind regards,

Stephan

**Comment by damcou** [comment]
@stephan-cream ,

The configuration **Stores -> Configuration -> Algolia Search -> Products: Index out of stock options for configurable products** will be related to configurable product options in any case.

If you want to index simple products with no stock, you should consider setting the configuration **Stores -> Configuration ->  Catalog -> Inventory -> Display out of stock products** to "yes" if possible, the extension takes this setting into account.

Best regards.

**Comment by stephan-cream** [comment]
@damcou ,

That is exactly the situation.
We have "Display out of stock product" set to "Yes".
Which works like expected, showing simples that are out of stock in the search results.

However like i described before, "Index out of stock options for configurable products" is set to "No" which has no effect, as was confirmed.

The only problem we are having right now is that when applying a filter, for example the 'size: 1', it will also show configurable products of which the simple option is out of stock for.

My comment was solely to point out that **canProductBeReindexed** can not be used for our situation, as this would also prevent simple products from being shown in the search results if they are out of stock.

**Comment by damcou** [comment]
@stephan-cream , ok thanks for the clarification, it makes sense.

Can you try to change these lines : 

https://github.com/algolia/algoliasearch-magento-2/blob/develop/Helper/Entity/ProductHelper.php#L1146%C2%A7L1148

```
        if (!$this->configHelper->getShowOutOfStock($storeId)) {
            $isInStock = $this->productIsInStock($product, $storeId);
        }
```
to 

```
        if (!$this->configHelper->getShowOutOfStock($storeId)
            || (!$this->configHelper->indexOutOfStockOptions($storeId) && $isChildProduct === true)) {
            $isInStock = $this->productIsInStock($product, $storeId);
        }
```
And tell me if this behaviour seems ok to you.
Thanks in advance.
Best.

**Comment by stephan-cream** [comment]
@damcou 

This change has the correct behaviour.

With kind regards,

Stephan

**Comment by matthijsburki** [comment]
Great to hear! When will this fix be available in an officiel release?

Kind regards,

Matthijs Burki





Leeuwenhoekstraat 134
2652 XL Berkel & Rodenrijs 

010-7536097
www.cream.nl

**Comment by damcou** [comment]
@stephan-cream and Maathijs,

I created a PR with the change.
It should be available in our next release.

Thanks again for your feedback.
Best.
Damien

**Comment by matthijsburki** [comment]
Van 24 dec t/m 1 januari 2020 ben ik even op vakantie. Graag bespreek ik lopende of komende tickets/zaken/campagnes vanaf 2 januari weer met jullie door.

**Comment by AntonIcube** [comment]
Hi, I have some problem and I have update algolia to the last version and add fixing code like @damcou  suggest. But configurable product prices still showing $.0. Do you have any suggestion?
 Thanks

Anton
