### ISSUE TITLE
Got error while running reindex

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#955]
Hello>

I'm using Magento 2.3.1 with PHP 7.2.24 with the latest version of Algolia Search installed.
However, during running reindex command, I've got this error (please see below)

2019-12-20T21:30:50+00:00 ERROR: Exception: 
                    Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Algolia\AlgoliaSearch\Helper\Data' does not have a method 'saveConfigurationToAlgolia' in /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php on line 83 in /var/www/production/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'call_user_func_...', '/var/www/produc...', 83, Array)
#1 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php(83): call_user_func_array(Array, Array)
#2 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(220): Algolia\AlgoliaSearch\Model\Job->execute()
#3 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(179): Algolia\AlgoliaSearch\Model\Queue->run(200)
#4 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Indexer/QueueRunner.php(56): Algolia\AlgoliaSearch\Model\Queue->runCron()
#5 /var/www/production/vendor/magento/module-indexer/Model/Indexer.php(413): Algolia\AlgoliaSearch\Model\Indexer\QueueRunner->executeFull()
#6 /var/www/production/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer->reindexAll()
#7 /var/www/production/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(87): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#8 /var/www/production/vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/production/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/production/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/production/vendor/magento/framework/Console/Cli.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/production/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/production/bin/magento(23): Symfony\Component\Console\Application->run()
#14 {main}
2019-12-20T21:30:50+00:00 ERROR: Exception: 
                    Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Algolia\AlgoliaSearch\Helper\Data' does not have a method 'saveConfigurationToAlgolia' in /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php on line 83 in /var/www/production/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'call_user_func_...', '/var/www/produc...', 83, Array)
#1 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php(83): call_user_func_array(Array, Array)
#2 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(220): Algolia\AlgoliaSearch\Model\Job->execute()
#3 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(179): Algolia\AlgoliaSearch\Model\Queue->run(200)
#4 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Indexer/QueueRunner.php(56): Algolia\AlgoliaSearch\Model\Queue->runCron()
#5 /var/www/production/vendor/magento/module-indexer/Model/Indexer.php(413): Algolia\AlgoliaSearch\Model\Indexer\QueueRunner->executeFull()
#6 /var/www/production/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer->reindexAll()
#7 /var/www/production/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(87): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#8 /var/www/production/vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/production/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/production/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/production/vendor/magento/framework/Console/Cli.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/production/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/production/bin/magento(23): Symfony\Component\Console\Application->run()
#14 {main}
32 jobs processed in 51 seconds.

**Comment by bsuravech** [comment]
Hi @luan123z, 

If you have recently upgraded your extension version, it is recommended that you clear your indexing queue jobs and reindex your data again. This is because some job methods have either change names or have been deprecated. I would try clearing your indexing queue and reindexing again. 

Let us know if that clears up the errors for you.
