### ISSUE TITLE
Reindex error

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#958]
Hello support

I've got this error to appear on the SSH Terminal when I run reindex 

2019-12-20T21:30:50+00:00 ERROR: Exception: 
                    Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Algolia\AlgoliaSearch\Helper\Data' does not have a method 'saveConfigurationToAlgolia' in /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php on line 83 in /var/www/production/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'call_user_func_...', '/var/www/produc...', 83, Array)
#1 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Job.php(83): call_user_func_array(Array, Array)
#2 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(220): Algolia\AlgoliaSearch\Model\Job->execute()
#3 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Queue.php(179): Algolia\AlgoliaSearch\Model\Queue->run(200)
#4 /var/www/production/vendor/algolia/algoliasearch-magento-2/Model/Indexer/QueueRunner.php(56): Algolia\AlgoliaSearch\Model\Queue->runCron()
#5 /var/www/production/vendor/magento/module-indexer/Model/Indexer.php(413): Algolia\AlgoliaSearch\Model\Indexer\QueueRunner->executeFull()
#6 /var/www/production/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer->reindexAll()
#7 /var/www/production/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(87): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#8 /var/www/production/vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/production/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/production/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/production/vendor/magento/framework/Console/Cli.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/production/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/production/bin/magento(23): Symfony\Component\Console\Application->run()
#14 {main}

---

I'm using Magento 2.1.3
PHP 7.2.24

Can you please have  a look?

**Comment by bsuravech** [comment]
Hi @luan123z, 

This is the same issue that you reported in #924 and in #955. Can you please confirm that you have followed the recommend suggestions in those PRs? Additionally, we have discontinued support for Magento 2.1.3 starting the v1.12.0 version. Can you confirm what your extension version is?

**Comment by bsuravech** [comment]
Hi @luan123z,

We are going to close this issue due to inactivity. If you have further issues or questions, please feel free shoot us a message at [support@algolia.com](mailto:support@algolia.com).
