### ISSUE TITLE
Categories events incongruent documentation

### ISSUE THREAD

**Issue by Thundar** [algolia/algoliasearch-magento-2#960]
**Categories events incongruent documentation**

**Bug: What is the current behavior?**

https://www.algolia.com/doc/integration/magento-2/customize/custom-back-end-events/?language=php#dispatching-after-fetching-categorys-attributes-for-indexing

From documentation lines:
> $category as data in Magento\Framework\DataObject object
> $categoryObject as Magento\Catalog\Model\Category

while in code has:
`$transport = new DataObject($data);`
...
`['category' => $category, 'categoryObject' => $transport]`

So `categoryObject` is a `DataObject` and `category` is a `Category`.

**Bug: What is the expected behavior?**
Documentation coherent to code.

**Bug: What is the proposed solution?**
Invert documentation variables.

**Comment by bsuravech** [comment]
Hi @Thundar! Good catch! We'll add this change to our next documentation update! Thanks for reporting!

**Comment by bsuravech** [comment]
Hi @Thundar,

I hope you are doing well! My apologies on the delay in the follow up. We have made those changes to our documentation. Please feel free to check out these changes when you have a moment. 

https://www.algolia.com/doc/integration/magento-2/customize/custom-back-end-events/?language=php#dispatching-after-fetching-categorys-attributes-for-indexing

Thanks!
