### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by magegirl** [algolia/algoliasearch-magento-2#961]
Bonjour,
J'ai 4 websites et 4 comptes algolia que j'ai configuré sur chaque store, mais à l'indexation tout se retrouve uniquement sur le premier compte.

**Comment by bsuravech** [comment]
Hi @magegirl,

My apologies on the delayed response. The extension for Magento 2 currently isn't compatible with using multiple application IDs. It is only looking at the default configuration. As storeviews have a unique identifiers, all your stores for your separate websites will have their own index within the first account. If you have any further questions, please feel free to shoot us a email at [support@algolia.com](mailto:support@algolia.com).
