### ISSUE TITLE
Thumbnail image for configurable product is wrong

### ISSUE THREAD

**Issue by gibbotronic** [algolia/algoliasearch-magento-2#962]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**
Algolia indexes a product and always includes the product's image for the thumbnail_url field. For configurable products it reads the image of the first child product that has an image, even if the configurable product itself has an image.
It therefore harvests (and shows) the wrong image for the product.

eg. I have a barrier product, SKU 12270:
<img width="331" alt="configurable product" src="https://user-images.githubusercontent.com/54802707/71983578-03f53d00-321f-11ea-8fe3-00adf1a911ee.png">
It has some variations:
![variations](https://user-images.githubusercontent.com/54802707/71983604-10799580-321f-11ea-99d7-13c107ade3c4.png)
It also has its own image:
![configurable product images](https://user-images.githubusercontent.com/54802707/71983616-18d1d080-321f-11ea-95d5-45c121b7c5d7.png)
If you search for this product, you get the FIRST child even though the configurable product has its own image:
<img width="475" alt="wrong results" src="https://user-images.githubusercontent.com/54802707/71983649-28e9b000-321f-11ea-8162-47aedf9c2975.png">

**Bug: What is the expected behavior?**
It should show the configurable product's image, or if there is none, show the first child product that has an image.

It should show this:
<img width="316" alt="expected" src="https://user-images.githubusercontent.com/54802707/71983681-356e0880-321f-11ea-821a-7fd7fffda5cc.png">
You can see the images for a product if you use a query, eg. `select p.sku, e.attribute_code, g.value, v.position from catalog_product_entity_media_gallery g left outer join catalog_product_entity_media_gallery_value v on g.value_id = v.value_id left outer join eav_attribute e on g.attribute_id = e.attribute_id left outer join catalog_product_entity_media_gallery_value_to_entity m on m.value_id = g.value_id left outer join catalog_product_entity p on m.entity_id = p.entity_id where v.store_id = 1 and p.sku = '12270' order by p.sku asc, v.position asc`

**Bug: What is the proposed solution?**
vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php
  private function addImageData
calls
  $customData['thumbnail_url'] = $this->imageHelper ->init($product, 'product_thumbnail_image') ->getUrl();
Image helper is vendor/algolia/algoliasearch-magento-2/Helper/Image.php

vendor/algolia/algoliasearch-magento-2/Helper/Image.php
```getConfigurableProductImage``` is the offending function. It gets a collection of child products and returns the first image that it comes across.
The ordering of the child products follows the ordering of the products in Magento's UI (not sure on the order - think it is SKU, so 12270-BW is first before 12270-RW, for example).

Oddly, function ```getProductImage``` calls ```getConfigurableProductImage``` if the product is configurable, but **_already_** has an image URL for it (which is the one we want). It then goes and calls ```getConfigurableProductImage``` anyway.

I think the function should be changed from:

```
private function getProductImage(\Magento\Catalog\Model\Product\Image $model)
{
    $imageUrl = $this->getProduct()->getData($model->getDestinationSubdir());
    if ($this->getProduct()->getTypeId() == ProductTypeConfigurable::TYPE_CODE) {
        $imageUrl = $this->getType() !== 'image' && $this->getConfigurableProductImage() ?
            $this->getConfigurableProductImage() : $this->getProduct()->getImage();
    }

    return $imageUrl;
}
```

to

```
private function getProductImage(\Magento\Catalog\Model\Product\Image $model)
{
    $imageUrl = $this->getProduct()->getData($model->getDestinationSubdir());
    if (($imageUrl === null || strlen($imageUrl) == 0) && $this->getProduct()->getTypeId() == ProductTypeConfigurable::TYPE_CODE) {
        $imageUrl = $this->getType() !== 'image' && $this->getConfigurableProductImage() ?
            $this->getConfigurableProductImage() : $this->getProduct()->getImage();
    }

    return $imageUrl;
}
```

For testing, I am reindexing a product via Magento's admin panel, so the call stack is:
```
Algolia\AlgoliaSearch\Helper\Image->getConfigurableProductImage (vendor/algolia/algoliasearch-magento-2/Helper/Image.php:104)
Algolia\AlgoliaSearch\Helper\Image->getProductImage (vendor/algolia/algoliasearch-magento-2/Helper/Image.php:92)
Algolia\AlgoliaSearch\Helper\Image->initBaseFile (vendor/algolia/algoliasearch-magento-2/Helper/Image.php:73)
Algolia\AlgoliaSearch\Helper\Image->applyScheduledActions (vendor/magento/module-catalog/Helper/Image.php:473)
Algolia\AlgoliaSearch\Helper\Image->getUrl (vendor/algolia/algoliasearch-magento-2/Helper/Image.php:45)
Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->addImageData (vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php:727)
Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->getObject (vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php:505)
Algolia\AlgoliaSearch\Helper\Data->getProductsRecords (vendor/algolia/algoliasearch-magento-2/Helper/Data.php:507)
Algolia\AlgoliaSearch\Helper\Data->rebuildStoreProductIndexPage (vendor/algolia/algoliasearch-magento-2/Helper/Data.php:636)
Algolia\AlgoliaSearch\Helper\Data->rebuildStoreProductIndex (vendor/algolia/algoliasearch-magento-2/Helper/Data.php:326)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->checkAndReindex (vendor/algolia/algoliasearch-magento-2/Controller/Adminhtml/Reindex/Save.php:222)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->execute (vendor/algolia/algoliasearch-magento-2/Controller/Adminhtml/Reindex/Save.php:99)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->execute (generated/code/Algolia/AlgoliaSearch/Controller/Adminhtml/Reindex/Save/Interceptor.php:24)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->dispatch (vendor/magento/framework/App/Action/Action.php:108)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->dispatch (vendor/magento/module-backend/App/AbstractAction.php:231)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->Magento\Framework\Interception\{closure:/home/344161.cloudwaysapps.com/dbmmccsbmn/public_html/vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
WeltPixel\GoogleTagManager\Plugin\Utility->aroundDispatch (vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php:76)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->Magento\Framework\Interception\{closure:/home/344161.cloudwaysapps.com/dbmmccsbmn/public_html/vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch (vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->Magento\Framework\Interception\{closure:/home/344161.cloudwaysapps.com/dbmmccsbmn/public_html/vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:135)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save\Interceptor->dispatch (generated/code/Algolia/AlgoliaSearch/Controller/Adminhtml/Reindex/Save/Interceptor.php:39)
Magento\Framework\App\FrontController\Interceptor->processRequest (vendor/magento/framework/App/FrontController.php:159)
Magento\Framework\App\FrontController\Interceptor->dispatch (vendor/magento/framework/App/FrontController.php:99)
Magento\Framework\App\FrontController\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:/home/344161.cloudwaysapps.com/dbmmccsbmn/public_html/vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Framework\App\FrontController\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Framework\App\FrontController\Interceptor->dispatch (generated/code/Magento/Framework/App/FrontController/Interceptor.php:26)
Magento\Framework\App\Http\Interceptor->launch (vendor/magento/framework/App/Http.php:137)
Magento\Framework\App\Bootstrap->run (vendor/magento/framework/App/Bootstrap.php:261)
{main} (index.php:39)
```

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.3.3
Algolia Magento version 1.12.1

**Comment by bsuravech** [comment]
Hi @gibbotronic! Thanks for the very thorough issue you reported and for your proposed solution regarding the configurable product image. I think this is a good correction to add to our next release. We encourage contribution here and would love to see your suggestion in a pull request if you have a moment. In any case, we're going to create an internal ticket to work on this in an upcoming sprint. Thank you!

**Comment by gibbotronic** [comment]
Thanks for merging my suggested change.

Is there chance of getting any upgrade or service "reward" from Algolia for finding and fixing this bug as we are users of your product? I only ask because attempting to get assistance via support was met with a "you must pay for support!" email after 1 request, which I found disconcerting.

(I would imagine that declining to offer an upgrade or service reward for finding and fixing bugs in this code would send quite a negative message and potentially dissuade future customers from bothering to investigate and/or offer fixes?)

**Comment by bsuravech** [comment]
Hi @gibbotronic,

I hope you are doing well. My apologies for the delay in response. At this time, the extension does not have a bug reward in place. We're going to port this feedback over internally to see if this is something we can set up for our open source products. We appreciate your feedback and your assistance. If you have any further feedback or suggestions, you can reach out to us over at [support@algolia.com](mailto:support@algolia.com).
