### ISSUE TITLE
Improper Bootstrap Usage on Product Listing Page

### ISSUE THREAD

**Issue by razoyodev** [algolia/algoliasearch-magento-2#963]
**Bug: What is the current behavior?**
On the Algolia Product Listing Page (PLP), the product item grid does not properly implement the Bootstrap grid. Although the column classes are used, they are used on the wrong element (the child div of ais-hits--item rather than ais-hits--item itself) and the row class is not used at all. Because of this, the default Bootstrap flex/layout styling is overridden and the divs with erroneous column classes are floated. The consequence is that the Bootstrap flex rules cannot be used, and the containing elements have no height as overflow cannot be set without breaking the layout (screenshot below). Using float this way is bad practice.
(For styles see: [view/frontend/web/internals/algoliasearch.css:1200-1238](https://github.com/algolia/algoliasearch-magento-2/blob/develop/view/frontend/web/internals/algoliasearch.css#L1200))

**Bug: What is the expected behavior?**
Bootstrap grids should be implemented properly using their documentation and floats should not be used for flex/grid layout: https://getbootstrap.com/docs/4.0/layout/grid/

**Bug: What is the proposed solution?**
- Follow the Bootstrap documentation and apply the column classes to the ais-hits--item div.
- Add the row class to the ais-hits div
- Get rid of hacky CSS that floats the columns and overrides Bootstrap's grid styles

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia 1.12.x
Magento 2.2.6

**Screenshots**
Column classes are applied to the wrong element:
![2020-01-08--1578509733_1359x604_scrot](https://user-images.githubusercontent.com/19999877/72006881-2d5d9b00-3216-11ea-9643-e94b06148c26.png)

After overflows are set on the elements, the layout breaks:
![2020-01-08--1578509951_1359x603_scrot](https://user-images.githubusercontent.com/19999877/72007230-d99f8180-3216-11ea-81c2-7b38907241c5.png)

**Comment by bsuravech** [comment]
Hi @razoyodev, 

Thanks for submitting! I hope you are doing well and my apologies on the delay in response. This is really good feedback and something that I've added to our productboard for consideration for future improvements. If you have any further feedback or issues, please feel free to reach us at [support@algolia.com](mailto:support@algolia.com).
