### ISSUE TITLE
Algolia config not defined 

### ISSUE THREAD

**Issue by niihal** [algolia/algoliasearch-magento-2#970]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**

**Bug: What is the expected behavior?**

**Bug: What is the proposed solution?**

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

**Comment by niihal** [comment]
![image](https://user-images.githubusercontent.com/38681948/73064150-5cd10080-3ec2-11ea-8123-ce41911f586e.png)

**Comment by bsuravech** [comment]
Hi @niihal,

Can you check if view/frontend/templates/internals/configuration.phtml template has been added to your layout? 

In our layout, the block template is referenced to the `head.additional` block. 

```
        <referenceBlock name="head.additional">
            <block class="Algolia\AlgoliaSearch\Block\Configuration" name="algolia.internals.configuration" template="Algolia_AlgoliaSearch::internals/configuration.phtml"/>
        </referenceBlock>
```

**Comment by bsuravech** [comment]
Hi @niihal, 

I hope you are doing well and that you got your issue resolved. We are going to close out the GitHub issue.  If you have any further questions or feedback, please free to shoot us a message at[ support@algolia.com](mailto: support@algolia.com). Thank you!
