### ISSUE TITLE
Reindex SKU's notice when reindexing is disabled

### ISSUE THREAD

**Issue by peterjaap** [algolia/algoliasearch-magento-2#980]
![image](https://user-images.githubusercontent.com/431360/74677678-4b290300-51b9-11ea-9141-6f5e57251337.png)

This screen says;

```
You will be notified if there is any reason why your product can't be reindexed.

It can be :

Product is disabled.
Product is deleted.
Product is out of stock.
Product is not visible.
Product is not related to the store.
```

However, when this setting is set to Enable indexing is set to No;

![image](https://user-images.githubusercontent.com/431360/74677710-61cf5a00-51b9-11ea-8ce9-b6be9fa753a6.png)

There will be no notice at all. We should add a notice saying "The SKU is not reindexed because indexing is disabled."

**Comment by bsuravech** [comment]
Hi @peterjaap,

I hope you're doing well! My apologies for the delayed response on this. This is a good recommendation and something we should improve on for this usecase. We've forwarded your feedback for consideration for future improvements. Thanks!
