### ISSUE TITLE
algolia_delete_products indexer deletes all products

### ISSUE THREAD

**Issue by satishgadhave** [algolia/algoliasearch-magento-2#988]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When 'algolia_delete_products' indexer is run, it deletes products in all but first (id = 1) website even though products are enabled and in-stock. (We have multi-website and multi-store setup with MSI enabled)

**Bug: What is the expected behavior?**
'algolia_delete_products' indexer should not delete enabled and in-stock products in any website.

**Bug: What is the proposed solution?**
The reason we found is: 
All stores are iterated in DeleteProducts Indexer and as we have MSI enabled, getProductCollectionQuery in ProductHelper adds join on specific 'inventory_stock_?' table.

Its expected to join stock table assigned to current website (sales channel) in loop. 
We found that it always join stock table of default store. 

When we traced further, storeManager is used to get the current store and it always returns default store (even for other stores). This means indexer would find a mismatch for all products in algolia index and Magento store which leads to the deletion of all products in index.

The solution we propose is to set the store explicitly in storeManager at:
File: Model/Indexer/DeleteProduct.php
in the foreach loop: foreach ($storeIds as $storeId) 
like: $this->storeManager->setCurrentStore($storeId);

Let me know if you want PR for this.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento: 2.3.1
Algolia extension: 1.10.0

**Comment by damcou** [comment]
Hello @satishgadhave ,

Looks like the issue here is that you use MSI.
We recently released a compatibility module to handle it : https://www.algolia.com/doc/integration/magento-2/how-it-works/magento-feature-compatibility/?language=php#magento-inventory-msi

As mentioned in the documentation, you'll first have to update the module to - at least - 1.12.x to be able to use it.

**Comment by satishgadhave** [comment]
@damcou 
Thanks for the info!
I see that, the issue has been handled by explicitly passing required storeId in plugin code there:
$websiteId = $this->storeManager->getStore(**$storeId**)->getWebsiteId();

Glad that it matches my workaround in the current module. We can not upgrade to 1.12.X immediately. So, for now we have added this fix in the extended module.

**Suggestion:** 
Refenence / Information to these add-on modules ([algolia/algoliasearch-inventory-magento-2](https://github.com/algolia/algoliasearch-magento-2)) should be added on readme of this parent module (algolia/algoliasearch-magento-2)
