### ISSUE TITLE
Packagist TAG is messed up

### ISSUE THREAD

**Issue by qsolutions-pl** [algolia/algoliasearch-magento-2#992]
When you install Algolia for Magento 2 using composer:

`composer require algolia/algoliasearch-magento-2 `

It does install latest version based on TAGS defined on packagist website, which is here:

https://packagist.org/packages/algolia/algoliasearch-magento-2

However, that TAG version (1.13) does not have all code updates, for example:
https://github.com/algolia/algoliasearch-magento-2/blob/1.12.1/Helper/Entity/PageHelper.php

has code changes to fetch proper CMS page URL for multistore setup with different domains
you can compare it with this file:
https://github.com/algolia/algoliasearch-magento-2/blob/1.13.0/Helper/Entity/PageHelper.php
- it does not have this changes. 

This was major issue, broke entire CMS page setup on 2 production sites after running composer update to fetch latest code. 

Please fix and make sure all latest code is in latest TAG version .

**Comment by bsuravech** [comment]
Hi @qsolutions-pl,

Thanks for submitting and my apologies for the delay in response. Between the 1.12.1 and 1.13.0 versions of the PageHelper, it seems that the changes for multistore setup has been updated and not omitted as you can see here:

https://github.com/algolia/algoliasearch-magento-2/commit/d3ce9fb47253fb6fde88563e528a60aa11a60bbd#diff-8e772f015722d1050c400c01e3c12cdf

If you are still experiencing this issue, there is currently an open PR (#1012) from a community member to help improve the issue with multistore URLs for pages that is currently under review. Once it has passed our review and testing, this PR will be included in our next release. 

If you have any feedback or further issues, please feel free to reach us at [support@algolia.com](mailto:support@algolia.com).
