### ISSUE TITLE
Huge algoliaBundle.min.js file size

### ISSUE THREAD

**Issue by bramvanderholst** [algolia/algoliasearch-magento-2#993]
The agoliaBundle.min.js file (https://github.com/algolia/algoliasearch-magento-2/blob/develop/view/frontend/web/internals/algoliaBundle.min.js) is over 500kb!

This huge file size significantly decreases performance & pagespeed score.

It seems to include all sorts of third party dependencies like jQuery, lodash etc. 

As M2 already uses jQuery, is it really necessary to add it to the Agolia bundle as well?
As for lodash, is it really necessary to add that library (in its entirety)?

**Comment by bsuravech** [comment]
Hi @bramvanderholst,

Thank you for submitting your feedback. We are aware the bundle size concerns. We will discuss with our instantsearch/autocomplete.js teams for their recommendations on how to better optimise the bundle as most of the dependencies derive from those libraries. I have ported your issue to our productboard for future consideration for improvements. Thanks!
