### ISSUE TITLE
Regarding conflict issue

### ISSUE THREAD

**Issue by aartipatel6495** [algolia/algoliasearch-magento-2#995]
Currently, Algolia\AlgoliaSearch\Model\Layer\Filter\Attribute.php file conflicting with WeltPixel\LayeredNavigation\Model\Layer\Filter\Attribute.php file.

How can we resolve conflicting issues?

**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**

**Bug: What is the expected behavior?**

**Bug: What is the proposed solution?**

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

**Comment by aartipatel6495** [comment]
Please check the below comments
Bug: What is the current behavior?
**Comment**: Currently If we enable Algolia to search extension Multiple select options not working in welt pixel layered navigation.
Bug: What is the expected behavior?
**Comment** : Algolia search and Welt pixel layered navigation multi-select functionality should be working at same time. 
Bug: What is the proposed solution?
**Comment:** We have tried to add  Algolia module dependency in  Welt pixel layered navigation but not working.
Feature: What is your use case for such a feature?
**Comment**: We need to use Algolia search and welt pixel module at same time.
Feature: What is your proposed configuration entry? The new option to add? What is the behavior?
**Comment:**:  conflicting issue occurring because of Algolia\AlgoliaSearch\Model\Layer\Filter\Attribute.php same file using in WeltPixel\LayeredNavigation\Model\Layer\Filter\Attribute.php file.

What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.
**Comment:** Currently we are using this Algolia version: 1.13.0

**Comment by bsuravech** [comment]
Hi @aartipatel6495 ,

Thanks for submitting your issue. At this time, the extension is not compatible with the third party Welt Pixel extension for layered navigation. We do not consider this a bug issue but more as feedback for compatibility. We will send your feedback over to our productboard for consideration for improvement. 

If you have any issues or further feedback, please feel free to send them to [support@algolia.com](mailto:support@algolia.com).
